juicedata/juicefs

- .github/ISSUE_TEMPLATE/support.md
- README.md
- README_CN.md
> Discussion link

- README.md
- README_CN.md
Signed-off-by: Xuanwo <github@xuanwo.io>
> docs: Add QingStor Object Storage into Supported List

- README.md
Some spelling and grammar mistakes are corrected.
> Update README.md for some grammar mistakes

- pkg/vfs/writer.go
> Revert "The lock should not be released immediately after it is acquired"

- pkg/redis/redis.go
- pkg/redis/redis_test.go
The transaction in Redis is based on optimistic lock on keys, retry the transaction if there is any conflict.
When there is a high content on same key,  it could fail after 10 tries.
This behavior could be reproduced by random write on big file:
```
fio --name=big-file-multi-write  --rw=randwrite --refill_buffers --bs=4k --size=100M --numjobs=1 --end_fsync=1
```
This PR increase the number of retry, and also added random backoff between them to reduce the chance of failed transaction.
Close #33
> retry transactions with random backoff

- .github/workflows/verify.yml
> add Github Actions as CI

- cmd/mount.go
- pkg/redis/redis.go
This PR added the data part for compaction, read the slices and write into a bigger one.
> Implement data compaction

- pkg/vfs/vfs_unix.go
golangci-lint reports there are unnecessary `fmt.Sprintf` call in this function. I just rewrite it to use `strings.Builder` when looking at it.
> Use strings.Builder to build the attr string

- pkg/chunk/cached_store.go
- pkg/chunk/disk_cache.go
A line was removed by mistake.
This PR also cleanup the code to to download a object.
> fix broken block cache

- .github/workflows/verify.yml
> Add a lint job to run golangci-lint

- cmd/main.go
This PR is for #18 .
The command line flags can be passed by mount options like `flagName` for boolean flag and `flagName=flagValue` for non boolean flag.
1. Add a symbolic link `/sbin/mount.juicefs` to the `juicefs` binary exetuable. If the `juicefs` executable placed under `/bin/` directory: `sudo ln -s /bin/juicefs /sbin/mount.juicefs` 
2. Using _mount_ command such as:
`mount -t juicefs REDIS-URL MOUNTPOINT -o maxUpload=50,writeback,cacheSize=2048`
this command arguments would be transformed to:
`juicefs -d mount --maxUpload=50 --writeback --cacheSize=2048 REDIS-URL MOUNTPOINT`
3. If we want the volume auto mount when server restart, we can append the following line to `/etc/fstab`:
```
REDIS-URL MOUNTPOINT _netdev,maxUpload=50,writeback,cacheSize=2048 0 2
```
> support called by mount command and /etc/fstab on Linux

- .goreleaser.yml
fix https://github.com/juicedata/homebrew-tap/issues/1
> add brews in goreleaser

- .goreleaser.yml
> add linux-arm64 binary build

- pkg/redis/redis.go
> delete xattr data when removing files

- pkg/meta/redis.go
> allow update access key and secret key

- cmd/version.go
- pkg/chunk/cached_store.go
- pkg/chunk/disk_cache.go
- pkg/utils/alloc.go
- pkg/utils/buffer.go
- pkg/utils/compress.go
- pkg/utils/cond.go
- pkg/utils/logger.go
- pkg/utils/utils.go
improved `golint` coverage to 60%   [issue](https://github.com/juicedata/juicefs/issues/77)
to test the coverage setup `goreportcard` on local machine and  run `goreportcard-cli`
> Go reportcard fix

- pkg/meta/redis.go
Fix #94 .
When running on my development environment, it took about 6.x seconds to "open and immediately close 1000 files" in Python. After the change, it only took about 4.x to 5.x seconds.
> Fix #94, use lua script when possible to reduce redis calls

- pkg/fuse/context.go
- pkg/meta/context.go
- pkg/meta/redis.go
- pkg/meta/redis_test.go
This PR increase the number retry in redis client, also enable cancelation.
> retry commands after failure with redis

- README.md
- README_CN.md
Since we already support this feature
> Remove K8s CSI driver from roadmap

- go.mod
- go.sum
- pkg/object/swift.go
1. Add swift object storage support, current only support "v1" auth method
2. The bucket url (--bucket option) format is:   http://BucketName.1.2.3.4[:port]
> Add swift object storage support

- README.md
- docs/command_reference.md
* add Command Reference doc
* add entry in README
> add command reference doc

- cmd/mount.go
I can't find the format of commit message.
If I got sth wrong, plz correct me. : )
> Fix wrong value assignment for StorageConfig.SecretKey

- cmd/main.go
- cmd/umount.go
- docs/command_reference.md
> add umount sub-command

- .github/workflows/release.yml
- .goreleaser.yml
> build static linked

- pkg/vfs/accesslog.go
> improve performance of accesslog

- .goreleaser.yml
1. fix `ldflag` to pass version
2. change archive name template: use `-` replace `_`
> goreleaser: fix ldflags and change archive name template

- pkg/meta/redis.go
After deletion of chunks, it failed to remove the tracking list, which has to be cleared every minutes, could cause high CPU usage every minute or after mounted.
Close #148
> fix tracking for chunk deletion

- docs/hadoop_java_sdk_cn.md
- sdk/java/pom.xml
- sdk/java/src/main/java/io/juicefs/FlinkFileSystemFactory.java
- sdk/java/src/main/resources/META-INF/services/org.apache.flink.core.fs.FileSystemFactory
add FlinkFileSystemFactory so that we can juist config Juicefs in flink client, not all the cluster
> hadoop: add FlinkFileSystemFactory

- README.md
- README_CN.md
- docs/en/redis_best_practices.md
> Add doc: Redis best practices

- docs/en/how_to_setup_object_storage.md
- docs/en/redis_best_practices.md
> Update doc: add recommended managed Redis service

- README.md
- README_CN.md
- cmd/format.go
- cmd/sync.go
- docs/en/command_reference.md
- docs/en/comparison_with_others.md
- docs/en/encrypt.md
> Update data encryption related docs

- go.mod
- go.sum
> replace minio to remove broken metrics from MinIO

- pkg/object/README.md
- pkg/object/eos.go
> Add support for China Mobile Cloud (ECloud) Object Storage

- cmd/main.go
- cmd/rmr.go
- pkg/meta/interface.go
- pkg/utils/utils_unix.go
- pkg/vfs/handle.go
- pkg/vfs/internal.go
- pkg/vfs/vfs.go
> remove directory recursively

- README.md
- README_CN.md
- docs/en/faq.md
- docs/en/fuse_mount_options.md
- docs/en/how_to_setup_object_storage.md
- docs/zh_cn/faq.md
> Add FUSE mount options doc

- .github/workflows/release.yml
- .gitignore
- .goreleaser.yml
- go.sum
> Build windows binary and hadoop sdk in release workflow

- cmd/mount.go
- cmd/mount_unix.go
- cmd/mount_windows.go
> public metrics after fork()

- cmd/gc.go
- cmd/main.go
- pkg/meta/interface.go
- pkg/meta/redis.go
- pkg/object/interface.go
- pkg/sync/sync.go
- pkg/sync/sync_test.go
> Collect garbage in object store

- .travis.yml
- cmd/fsck.go
- cmd/gateway.go
- cmd/gc.go
- cmd/main.go
- cmd/mount.go
- fstests/Makefile
- pkg/meta/interface.go
- pkg/meta/redis.go
- pkg/meta/redis_test.go
- pkg/object/encrypt.go
- sdk/java/libjfs/main.go
Added to a tool `juicefs fsck` to check consistency of file system. 
Right now, only the existence of blocks are checked, others will be added later.
Closes #249
> Check consistency of file system

- cmd/gateway.go
- cmd/mount.go
- pkg/chunk/cached_store.go
- pkg/chunk/disk_cache.go
- pkg/chunk/store_test.go
- sdk/java/libjfs/main.go
> Sync stagging block in writeback mode

- pkg/chunk/cached_store.go
> add metrics for block cache

- go.sum
- pkg/object/ceph.go
> fix building with librados

- Makefile
- cmd/sync.go
- pkg/object/ceph.go
- pkg/object/file.go
- pkg/object/sftp.go
https://github.com/juicedata/juicesync/issues/108 related.
`juicesync` use packages from `juicefs`, `juicefs sync` should also support Windows platform.
> sync support windows

- README.md
- README_CN.md
- cmd/format.go
- docs/en/command_reference.md
- docs/en/comparison_with_others.md
> Disable data compression by default

- sdk/java/src/main/java/io/juicefs/utils/NodesFetcher.java
> hadoop: change http handler to static var to avoid possible resource leak

- cmd/mount.go
- cmd/mount_windows.go
- pkg/meta/redis.go
- pkg/meta/redis_test.go
- pkg/winfsp/winfs.go
> Support Case Insensitive in Windows

- cmd/rmr.go
- pkg/fs/fs.go
- pkg/object/file.go
- pkg/object/sftp.go
- pkg/utils/utils_windows.go
- pkg/vfs/internal.go
- pkg/vfs/vfs.go
- pkg/winfsp/trace.go
- pkg/winfsp/winfs.go
Currently, we can't list the content of root, because the 2 virtual files.
> Fix listing files in root in Windows

- go.mod
- pkg/vfs/internal.go
- pkg/vfs/vfs.go
> expose metrics using virtual file /.stats

- cmd/gateway.go
- cmd/gc.go
- cmd/main.go
- cmd/mount.go
This PR also change the default address of metrics to localhost:9567
Closes #325
> Added a option to disable debug agent

- docs/en/how_to_use_on_kubernetes.md
- Change default value of `reclaimPolicy` from `Delete` to `Retain`
- Add troubleshooting guide (depends on https://github.com/juicedata/juicefs-csi-driver/pull/87)
- Fix typo
>  Update "How to use on K8s" doc: more details and troubleshooting guide

- cmd/main.go
- cmd/profile.go
> Add `profile` command to analyze access log

- README.md
- README_CN.md
- docs/en/hadoop_java_sdk.md
- docs/en/how_to_sync_the_same_account.md
- docs/zh_cn/faq.md
> Fix typo in "Sync Account on Multiple Hosts" doc

- README.md
- README_CN.md
- docs/en/fault_diagnosis_and_analysis.md
> Update doc: add "Operations Profiling" link to fault_diagnosis_and_analysis.md

- cmd/main.go
- cmd/status.go
- pkg/meta/config.go
close #365 
For now only volume setting is retrieved. More information(sessions, usage etc.) might be added later.
> Add `status` command to show settings

- cmd/gateway.go
close #370 
Reported-by: DanielQujun <qujun@tiduyun.com>
> Fix "gateway ListObjects returns no entry"

- cmd/benchmark.go
- pkg/chunk/cached_store.go
- pkg/chunk/disk_cache.go
- pkg/meta/sql.go
> add more metrics for block cache

- cmd/mount.go
> use absolute path for SQLite

- pkg/chunk/disk_cache.go
- pkg/chunk/disk_cache_test.go
> remove limit on number of cached blocks

- pkg/meta/redis.go
- pkg/meta/redis_test.go
- pkg/meta/sql.go
This PR could save one or two query to database for most changes to file system.
Closes #391
> update stats in background

- docs/en/command_reference.md
- docs/zh_cn/command_reference.md
> Update command ref doc: add `status` and `warmup` subcommands

- pkg/meta/redis_test.go
- pkg/meta/redis_unix.go
- pkg/meta/sql.go
- pkg/meta/sql_unix.go
- pkg/meta/sql_windows.go
> support posixlock for SQL engine

- README.md
fix how_juicefs_store_files.md link can not redirect problem
> Doc: fix how_juicefs_store_files.md link can not redirect problem

- go.mod
- go.sum
> upgrade gopsutil to v3.21.3

- pkg/fs/fs.go
The owner of file should be able to change the group of file to one of the group it belongs to.
Also, ReaddirPlush requires EXECUTE permission on the directory. Readlink does not require anything.
> allow owner to change group

- docs/zh_cn/case.md
Add some links in use case list for Chinese doc
> add some use case links for Chinese doc

- ADOPTERS.md
- ADOPTERS_CN.md
- README.md
- README_CN.md
* add adopter list in English
* move compatible project list to the use case part of docs/
> add adopter list in English

- cmd/gateway.go
- cmd/mount.go
- cmd/mount_unix.go
- docs/en/command_reference.md
- docs/zh_cn/command_reference.md
- pkg/fs/fs.go
- pkg/meta/config.go
- pkg/meta/interface.go
- pkg/meta/redis.go
- pkg/meta/sql.go
- pkg/vfs/fill.go
- pkg/vfs/helpers.go
- pkg/vfs/vfs.go
- pkg/vfs/vfs_unix.go
- sdk/java/libjfs/main.go
- sdk/java/src/main/java/io/juicefs/JuiceFileSystemImpl.java
> support read-only mode

- docs/en/case.md
- docs/zh_cn/case.md
- add use cases in English page
- remove blank title
> add English usecases, remove blank title in Chinese usecase page

- docs/en/how_to_setup_object_storage.md
- docs/zh_cn/how_to_setup_object_storage.md
> docs: Add docs for Vultr Object Storage

- cmd/benchmark.go
> cmd/bench: add -p/--threads options to run benchmarks in parallel

- docs/en/databases_for_metadata.md
- docs/zh_cn/databases_for_metadata.md
- go.mod
- pkg/meta/interface.go
- pkg/meta/redis_test.go
- pkg/meta/sql.go
- pkg/meta/sql_test.go
> meta: support PostgreSQL as the meta engine

- cmd/dump.go
- cmd/mount.go
- cmd/mount_unix.go
- docs/en/command_reference.md
- docs/zh_cn/command_reference.md
- pkg/meta/config.go
- pkg/meta/redis.go
- pkg/meta/sql.go
> Add a option to mount a sub-directory

- .github/workflows/verify.yml
- .travis.yml
- pkg/meta/sql_test.go
> ci: test with mysql and pg in travis

- cmd/mount.go
- docs/en/cache_management.md
- docs/en/command_reference.md
Chinese translation will in another PR.
> Docs: Add "Metadata Cache in Client"

- go.mod
- go.sum
- pkg/object/object_storage_test.go
- pkg/object/webdav.go
> support webdav as backend

- cmd/mount.go
- cmd/mount_unix.go
- cmd/mount_windows.go
- docs/en/command_reference.md
- docs/en/fault_diagnosis_and_analysis.md
- docs/zh_cn/command_reference.md
- docs/zh_cn/fault_diagnosis_and_analysis.md
- go.mod
- go.sum
> logging into file in background mode

- pkg/object/file.go
> speedup listing files

- cmd/gateway.go
- cmd/mount.go
- pkg/chunk/cached_store.go
- pkg/chunk/store_test.go
- pkg/object/bwlimit.go
- pkg/object/object_storage_test.go
- sdk/java/libjfs/main.go
- sdk/java/src/main/java/io/juicefs/JuiceFileSystemImpl.java
> Added limit for upload/download bandwidth 

- pkg/object/file.go
Currently, the Put() always call MkdirAll() and Remove() temp file, where are not need for common path (successful Put).
This PR changed it to call them when necessary.
> optimize PUT for file to avoid syscall

- docs/en/redis_best_practices.md
- docs/zh_cn/redis_best_practices.md
- pkg/meta/redis.go
Closes #612 
This is a BREAKING change, should be highlighted in release notes.
> change the password in url to redis server

- docs/en/how_to_use_on_kubernetes.md
- docs/zh_cn/how_to_use_on_kubernetes.md
update p8s config for mount pod which csi driver create.
> update p8s config in doc

- pkg/meta/tkv.go
- pkg/meta/tkv_mem.go
- pkg/meta/tkv_tikv.go
> cleanup zero refs and deleted files

- pkg/fs/fs.go
- pkg/fs/fs_test.go
> Fixed Seek() and mixed read/write in Go SDK

- docs/en/README.md
> Fix link to FAQ in docs/en/README.md

- pkg/meta/redis.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
A transaction could be restarted because of conflict, so we should not start a goroutine inside the transaction.
> start a goroutine after transaction finish

- pkg/meta/redis.go
- pkg/meta/slice.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
This PR cleanup the duplicated code for compaction, and fixed a bug in it (out of slice bound)
> cleanup compaction

- docs/en/databases_for_metadata.md
- docs/zh_cn/databases_for_metadata.md
add metadata engines list as a table of content
> add ToC for metadata engine document

- pkg/meta/sql.go
> fix collate in MySQL 5.6

- pkg/meta/redis_lock.go
- pkg/meta/redis_test.go
> fix pid of locked region

- cmd/profile.go
> cmd/profile: set interval to 0 when replaying a log file will generate

- cmd/mount.go
- pkg/chunk/alg.go
- pkg/chunk/cached_store.go
- pkg/chunk/disk_cache.go
- pkg/chunk/mem_cache.go
According to the discussion in #730 , we add a new parameter to delay upload staging file.
> Delay upload staging file when writeback enabled 

- pkg/sync/sync.go
> sync: Retry three times to avoid infinite loop

- pkg/object/eos.go
- pkg/object/jss.go
- pkg/object/minio.go
- pkg/object/oos.go
- pkg/object/qiniu.go
- pkg/object/s3.go
- pkg/object/scw.go
- pkg/object/space.go
- pkg/object/wasabi.go
> object: disable S3 sha256 to reduce CPU usage

- pkg/chunk/mem_cache.go
> chunk: add write metric for memory cache; writeHist is not added since

- pkg/meta/redis.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
In case of broken metadata, the attributes of inode could be lost, then we should be able to remove the broken file/directory.
> remove broken file/dir

- ADOPTERS.md
- ADOPTERS_CN.md
- add some adopters include Megvii, PaddlePaddle, UniSound, Geneway
- add ecosystem update, include Python SDK from Megvii, paddle-operator integration
> add new adopters and ecosystem update

- cmd/mount.go
- pkg/meta/interface.go
- pkg/meta/redis.go
- pkg/meta/redis_test.go
- pkg/meta/sql.go
- pkg/meta/sql_test.go
- pkg/meta/tkv.go
- pkg/meta/tkv_test.go
> meta: close current session when umounting

- pkg/object/obs.go
- pkg/object/webdav.go
> object: use bufpool for obs and webdav

- cmd/stats.go
> cmd/stats: ignore negative values

- cmd/format.go
- pkg/object/ceph.go
add JFS_ prefix in NO_CHECK_OBJECT_STORAGE env
> add JFS_ prefix in env

- cmd/format.go
- docs/en/quick_start_guide.md
- docs/zh_cn/quick_start_guide.md
PR #709 updated the log of MinIO
> Docs: update mount log in quick start guide

- cmd/gateway.go
- cmd/mount_unix.go
- docs/en/hadoop_java_sdk.md
- docs/zh_cn/hadoop_java_sdk.md
- pkg/fs/fs.go
- pkg/fuse/fuse.go
- pkg/vfs/vfs.go
- sdk/java/libjfs/main.go
- sdk/java/src/main/java/io/juicefs/JuiceFileSystemImpl.java
This PR added metadata cache for Java SDK and S3 gateway to speedup path resolving.
> add entry cache for Java SDK and S3 gateway

- docs/zh_cn/LTP_compatibility_test.md
- docs/zh_cn/README.md
> Docs: add LTP compatibility test to ToC

- docs/en/how_to_use_on_kubernetes.md
- docs/zh_cn/how_to_use_on_kubernetes.md
P.S. Chinese version is not synchronized with English version. There isn't _Mounting JuiceFS in container_ part in English version
> add ToC to K8s docs

- cmd/bench.go
> cmd/bench: remove default benchmark PATH

- docs/zh_cn/hadoop_java_sdk.md
> Docs: update TPC-DS benchmark

- .github/workflows/wintest.yml
> CI: test jfs on windows

- pkg/chunk/disk_cache.go
> cache: force sync upload if local disk is too full for writeback

- cmd/fsck.go
- cmd/gc.go
- pkg/meta/interface.go
- pkg/meta/redis.go
- pkg/meta/redis_test.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
> fsck: list broken files

- pkg/meta/redis.go
- pkg/meta/types.go
This pr can save 20% of memory when executing the dump command
> write to json file by stream

- pkg/compress/compress_test.go
```
ok      github.com/juicedata/juicefs/pkg/compress       0.464s  coverage: 91.7% of statements
```
> improve test coverage for pkg/compress

- pkg/utils/alloc_test.go
- pkg/utils/buffer_test.go
- pkg/utils/clock_test.go
- pkg/utils/cond.go
- pkg/utils/cond_test.go
- pkg/utils/logger.go
- pkg/utils/logger_test.go
- pkg/utils/memusage_test.go
- pkg/utils/rusage_test.go
- pkg/utils/utils.go
- pkg/utils/utils_test.go
This PR increase the code coverage of pkg/utils to 88%
> improve test coverage in pkg/utils

- pkg/usage/usage_test.go
- pkg/utils/rusage_test.go
> improve test coverage for pkg/usage

- cmd/gateway.go
- cmd/mount.go
- pkg/vfs/backup.go
- pkg/vfs/backup_test.go
- sdk/java/libjfs/main.go
- sdk/java/src/main/java/io/juicefs/JuiceFileSystemImpl.java
> mount: add `--backup-meta` to periodically backup metadata to object storage

- pkg/chunk/cached_store.go
- pkg/vfs/accesslog.go
- pkg/vfs/accesslog_test.go
- pkg/vfs/compact_test.go
- pkg/vfs/fill.go
- pkg/vfs/fill_test.go
- pkg/vfs/helpers_test.go
```
ok      github.com/juicedata/juicefs/pkg/vfs    4.652s  coverage: 32.6% of statements
```
related to #989
> Add unit tests for pkg/vfs

- pkg/meta/load_dump_test.go
- pkg/meta/redis.go
- pkg/meta/tkv.go
- pkg/meta/tkv_mem.go
- pkg/meta/tkv_prefix.go
- pkg/meta/tkv_tikv.go
Convert *prefixClient, *tikvClient type clients to *memkv, the subsequent operations remain unchanged
> speed up metadata dumping and loading for Tikv V2

- pkg/meta/tkv_tikv.go
The old method cannot pass error
> fix recovery error

- pkg/meta/redis.go
- pkg/meta/tkv.go
Add a progress bar for redis and tikv's make snap operation
> Add a progress bar for redis and tikv's make snap operation

- pkg/object/hdfs.go
should replace this if statement with an unconditional strings.TrimSuffix
> fix golangci-lint err

- cmd/gateway.go
- pkg/fs/fs.go
- pkg/fs/fs_test.go
- sdk/java/libjfs/main.go
This PR bring the coverage of pkg/fs to 86.2%
closes #991
> improve test coverage for pkg/fs

- cmd/mount_test.go
- go.mod
- go.sum
- pkg/meta/metrics_test.go
> Meta test improve

- .travis.yml
- pkg/meta/tkv_test.go
> add TiKV test

- pkg/meta/load_dump_test.go
- pkg/meta/metadata.sample
- pkg/meta/redis.go
pkg/meta: add more test for meta
> pkg/meta: add more test for meta

- .travis.yml
- pkg/object/object_storage_test.go
> add minio svc to travis

- pkg/meta/base.go
- pkg/meta/redis.go
- pkg/meta/tkv.go
> Remove duplicate code

- docs/en/how_to_use_on_kubernetes.md
- docs/en/juicefs_on_docker.md
- docs/zh_cn/how_to_setup_object_storage.md
- docs/zh_cn/how_to_use_on_kubernetes.md
- docs/zh_cn/juicefs_on_docker.md
- Fix missing English translate in K8s docs
- Remove duplicated TOC in page
> Docs: fix missing English translate in K8s docs

- .travis.yml
- cmd/bench.go
- cmd/bench_test.go
- cmd/mount_test.go
- cmd/status_test.go
- cmd/sync_test.go
- cmd/warmup.go
- cmd/warmup_test.go
> cmd: add test for cmd

- cmd/main.go
> cmd: fix mount via fstab 

- pkg/meta/redis.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
rollback part of the change in #1035
> use the attribute from fs.Open()

- go.mod
- go.sum
- pkg/fuse/fuse.go
- pkg/fuse/fuse_test.go
- pkg/vfs/vfs.go
This brings the coverage of pkg/fuse to 80%
> Add unit test for pkg/fuse/

- cmd/gateway.go
- integration/Makefile
- integration/integration_test.go
- integration/s3gateway_test.sh
- pkg/gateway/gateway.go
1. support multi-bucket mode of s3 gateway
2. support list object  use --recursive
3. add s3gateway test
> Add integration test for S3 gateway

- pkg/meta/redis.go
- pkg/meta/sql.go
> Don't emit warning log if trash inode is not found

- cmd/gateway.go
fix s3 gateway ls use recursive
> fix s3 gateway ls use recursive

- integration/s3gateway_test.sh
s3gateway test compatible with macOS
> s3gateway test compatible with macOS

- docs/zh_cn/administration/fault_diagnosis_and_analysis.md
This PR only contains Chinese doc, English doc will be in another PR.
> Docs: add doc about how to get pprof information

- pkg/utils/utils.go
> fix progressbar display

- integration/s3gateway_test.sh
add get object errno regression test
#1158
> add get object errno regression test

- pkg/meta/redis.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
> meta: fix nlink of parentDst in rename

- cmd/config.go
- cmd/destroy.go
- cmd/main.go
- pkg/meta/interface.go
- pkg/meta/redis.go
- pkg/meta/redis_test.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
> cmd: add `destroy` to clean up all data & metadata of a volume

- cmd/mount.go
- sdk/java/libjfs/main.go
> metrics: expose only JuiceFS metrics to prometheus

- README.md
- README_CN.md
> doc: fix broken link

- docs/en/grafana_template_k8s.json
fix issue: https://github.com/juicedata/juicefs/issues/1181
> docs: Fix grafana dashboard template mistake(#1181)

- pkg/vfs/vfs.go
> vfs: Delete unused code

- pkg/object/s3.go
First, set the region of the object storage compatible with the s3 protocol from the environment variable
> set the region of the object storage compatible with the s3 protocol from the env

- cmd/sync.go
- pkg/sync/cluster.go
- pkg/sync/cluster_test.go
- pkg/sync/sync.go
- pkg/sync/sync_test.go
> sync: simplify the code and use progress bar from utils

- .github/workflows/pjdfstest.yml
- .travis.yml
the issue refers to https://github.com/juicedata/juicefs/issues/1306
> use fixed version repo in actions

- pkg/chunk/disk_cache.go
In Windows, Rename will fail if the file is still open.
> close file before rename

- cmd/gc.go
- pkg/meta/redis.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
> meta: add progress bar for CompactAll

- docs/en/reference/command_reference.md
- docs/en/reference/how_to_setup_object_storage.md
- docs/zh_cn/reference/command_reference.md
- docs/zh_cn/reference/how_to_setup_object_storage.md
- Add `--check-all` and `--check-new` options to command reference doc
- Add description about the format of source and destination path of `juicefs sync` command
> Docs: add `--check-all` and `--check-new` options to command ref doc

- pkg/chunk/cached_store.go
- pkg/chunk/disk_cache.go
> chunk: add metrics for number of rawstaging blocks

- .travis.yml
1. enable minio test switch
2. fix the version of the dependent program in ci
> Enable minio test switch and fix the version of the dependent program in ci

- docs/en/reference/how_to_setup_object_storage.md
- docs/zh_cn/reference/how_to_setup_object_storage.md
> docs: set up proxy object storage

- pkg/vfs/vfs.go
- pkg/vfs/vfs_unix.go
> Fix access to trash dir

- docs/en/reference/how_to_setup_metadata_engine.md
- docs/zh_cn/reference/how_to_setup_metadata_engine.md
the `juicefs mount` command missing mount point
> doc: fix the `juicefs mount` command missing mount point

- docs/en/getting-started/installation.md
- docs/zh_cn/getting-started/installation.md
> improve cross-compiling doc

- .travis.yml
Judging service status by testing port connectivity
> CI check service status

- pkg/meta/interface.go
- pkg/meta/interface_test.go
> use `META_PASSWORD` env and omit unnecessary characters

- pkg/meta/interface.go
- pkg/meta/interface_test.go
- pkg/meta/redis.go
Refactoring code and adjust environment variable priorities
> meta: refactoring code and adjust environment variable priorities

- deploy/juicefs-s3-gateway.yaml
update s3 gateway image to latest version in deploy yaml
> update image in gateway deploy yaml

- pkg/meta/redis.go
Part solution to #1115 
When mounting in read-only mode, a JuiceFS client can read from Redis Sentinel-controlled replicas to distribute workloads:
```
$ juicefs mount redis://mymaster,localhost:26379?route-read=replica /mnt/jfs/ --read-only
```
Note:
1. It works ONLY in read-only mode
2. The query string `route-read=replica` is required, otherwise JuiceFS will connect to the master
3. Each JuiceFS client may connect to several replicas since it maintains a connection pool
4. It is possible that client got old metadata, because Redis replica dose async replication
> meta/redis: support read-only clients connecting to a random replica

- docs/en/getting-started/for_local.md
I assume the link was setup wronly.
> docs: minor fix for_local.md on link to database

- go.mod
- go.sum
- pkg/utils/logger.go
- pkg/utils/progress.go
Based on [mbp](github.com/vbauerster/mpb) v7.0.3 version code modification, add write interface to it, to achieve the effect that the progress bar and the log will not overlap each other
> progress bar add write interface

- docs/en/README.md
Try to improve the English introduction.
> docs: fix readme.md

- cmd/format.go
- docs/en/reference/how_to_setup_object_storage.md
- docs/zh_cn/reference/how_to_setup_object_storage.md
- pkg/object/restful.go
add environment variation `TLS_INSECURE_SKIP_VERIFY` to support skip https certificate verify
close #1451
> support skip https certificate verify

- sdk/java/src/main/java/io/juicefs/JuiceFileSystemImpl.java
when multiple version juicefs-hadoop.jar in the env, may cause load the wrong libjfs.so
> hadoop: fix libjfs.so load bug

- README.md
- docs/en/README.md
Hi, I am trying to update the `README.md` in the root folder and sync with the `readme.md` in docs-en.  We have also added one more button under the top logo that can redirect to the community docs. Please check if it is suitable. :)
> doc: fix readme.md part1

- pkg/object/ibmcos.go
- pkg/object/ks3.go
- pkg/object/obs.go
- pkg/object/qingstor.go
- pkg/object/s3.go
- pkg/object/swift.go
- pkg/utils/utils.go
> s3: set ContentType when putting object

- pkg/meta/base.go
- pkg/meta/redis.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
> continue dump when encountering non-fatal errors

- pkg/meta/base.go
- pkg/meta/benchmarks_test.go
- pkg/meta/interface.go
- pkg/meta/redis.go
- pkg/meta/redis_test.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
- pkg/vfs/vfs.go
> meta: return EROFS as soon as possible

- README.md
Went through the remained part of readme.md and made a few changes
> fix readme.md part2

- README.md
- docs/en/introduction/architecture.md
- docs/en/introduction/introduction.md
* Proofread `architecture.md` and made a few changes to the text;
* Compared and checked the architecture sections in `juicefs/READ.me` and `introduction.md` to make them consistent. 
* Corrected a few lines that I misunderstood in the above two sections.
> check docs-architecture

- docs/en/benchmark/operations_profiling.md
link: https://github.com/juicedata/docs/issues/22
> proofread: operations_profiling.md

- pkg/utils/cond.go
> fix busy lock in condition

- .github/workflows/wintest.yml
https://github.com/juicedata/juicefs/runs/5490529774?check_suite_focus=true
> CI：repair wintest err

- docs/en/benchmark/metadata_engines_benchmark.md
link: https://github.com/juicedata/docs/issues/21
> proofread: metadata_engines_benchmark.md

- pkg/meta/base.go
- pkg/meta/redis.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
1. don't ignore errors, instead log them
2. continue cleaning when error occurs, but mark it failed
3. keep the session entry if the procedure is marked as failed
> meta: check errors in doCleanStaleSession, and distinguish between close/clean

- CODE_OF_CONDUCT.md
Refer to the practice of [tidb](https://github.com/pingcap/community/blob/master/CODE_OF_CONDUCT.md) and https://www.contributor-covenant.org/version/2/1/code_of_conduct/
> doc update code of conduct

- docs/en/benchmark/performance_evaluation_guide.md
link: https://github.com/juicedata/docs/issues/23
@AIXjing Would you please review this PR if you have time? Thank you!
> proofread: performance_evaluation_guide.md

- docs/en/getting-started/for_local.md
- docs/en/getting-started/installation.md
- docs/en/introduction/architecture.md
- docs/en/introduction/introduction.md
@rayw000  Hi, Ray! Could you take a look at all the changes made in this document at your convenience? Thank you~  😄
> proofread docs: for_local.md

- ADOPTERS.md
- ADOPTERS_CN.md
add UniSound, YIMIAN, NetEase Games in adopter list
> add Community Adopters

- pkg/meta/redis.go
- pkg/meta/redis_test.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
> meta: don't update parent attribute if it's a trash directory

- pkg/meta/info.go
- pkg/meta/info_test.go
If it is an old version it should not continue to run
> check redis version

- .github/workflows/pjdfstest.yml
we can trigger the workflow on the action workflow context.
> add workflow_dispatch to trigger workflow manualy

- docs/en/benchmark/mdtest.md
link: https://github.com/juicedata/docs/issues/30
@AIXjing Here comes another review request. Thank you for your time. :)
> proofread: mdtest.md

- docs/en/benchmark/fio.md
link: https://github.com/juicedata/docs/issues/29
@AIXjing Here comes another review request. Thank you for your time :)
> proofread: fio.md

- .github/workflows/codeql-analysis.yml
- .github/workflows/elastictest.yml
- .github/workflows/ltpfs.yml
- .github/workflows/ltpsyscallshead.yml
- .github/workflows/ltpsyscallsmiddle.yml
- .github/workflows/ltpsyscallstail.yml
- .github/workflows/mysqltest_bigtable.yml
- .github/workflows/mysqltest_smalltable.yml
- .github/workflows/mysqltest_smalltablelocal.yml
- .github/workflows/mysqltest_smalltablelocalchangedir.yml
- .github/workflows/pjdfstest.yml
- .github/workflows/redis_compile.yml
- .github/workflows/sysbench_smallfile_randrw.yml
- .github/workflows/sysbench_smallfile_seqrw.yml
- .github/workflows/tpcds.yml
- .github/workflows/verify.yml
- .github/workflows/wintest.yml
add workflow_dispatch to trigger workflow manually
> add workflow_dispatch to trigger workflow manually

- cmd/fsck.go
- cmd/gc.go
- cmd/mount.go
- cmd/mount_test.go
- pkg/chunk/cached_store.go
- pkg/chunk/cached_store_test.go
- pkg/fs/fs_test.go
- pkg/meta/base.go
- pkg/meta/config.go
- pkg/meta/redis_test.go
- pkg/meta/sql_test.go
- pkg/meta/tkv_test.go
- pkg/vfs/compact_test.go
- pkg/vfs/vfs_test.go
- sdk/java/libjfs/main.go
> chunk: move MaxDeletes from meta to chunk package

- docs/en/getting-started/for_distributed.md
@rayw000 Could you take a look at this proofread when you have time? Thanks~ 😊
> proofread: for_distributed.md

- docs/en/benchmark/stats_watcher.md
link: https://github.com/juicedata/docs/issues/32
@AIXjing Here comes another review request. Thank you for your time :)
> proofread: stats_watcher.md

- pkg/meta/redis_test.go
> test/meta: make unit tests more stable

- pkg/meta/redis.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
> meta: call compactChunk again immediately if force is true

- docs/en/deployment/juicefs_on_docker.md
link: https://github.com/juicedata/docs/issues/24
Hi @AIXjing , could you please review this PR? Thank you! 😁
> proofread: juicefs_on_docker.md

- .github/workflows/codeql-analysis.yml
- .github/workflows/elastictest.yml
- .github/workflows/ltpfs.yml
- .github/workflows/ltpsyscallshead.yml
- .github/workflows/ltpsyscallsmiddle.yml
- .github/workflows/ltpsyscallstail.yml
- .github/workflows/mysqltest_bigtable.yml
- .github/workflows/mysqltest_smalltable.yml
- .github/workflows/mysqltest_smalltablelocal.yml
- .github/workflows/mysqltest_smalltablelocalchangedir.yml
- .github/workflows/pjdfstest.yml
- .github/workflows/redis_compile.yml
- .github/workflows/sysbench_smallfile_randrw.yml
- .github/workflows/sysbench_smallfile_seqrw.yml
- .github/workflows/tpcds.yml
> add user name and pull request title in slack message

- pkg/object/webdav.go
> webdav: fix  sync commond not working  when dst is webdav

- .github/workflows/fio_benchmark.yml
ref: https://juicefs.com/docs/zh/cloud/single_node_benchmark
> refactor and add more fio benchmarks from jfs document

- .github/workflows/codeql-analysis.yml
- .github/workflows/elastictest.yml
- .github/workflows/fio_benchmark.yml
- .github/workflows/ltpfs.yml
- .github/workflows/ltpsyscallshead.yml
- .github/workflows/ltpsyscallsmiddle.yml
- .github/workflows/ltpsyscallstail.yml
- .github/workflows/mysqltest_bigtable.yml
- .github/workflows/mysqltest_smalltable.yml
- .github/workflows/mysqltest_smalltablelocal.yml
- .github/workflows/mysqltest_smalltablelocalchangedir.yml
- .github/workflows/pjdfstest.yml
- .github/workflows/redis_compile.yml
- .github/workflows/sysbench_smallfile_randrw.yml
- .github/workflows/sysbench_smallfile_seqrw.yml
- .github/workflows/tpcds.yml
- .github/workflows/version_compatible.yml
- cmd/format.go
> update slack message UI.

- pkg/meta/redis.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
> meta: lock counters when loading entries

- .travis.yml
https://app.travis-ci.com/github/juicedata/juicefs/builds/248705624
Above url shows the failure ,but the nc loop did not indicate the failed process.
> CI:nc loop cannot show the specific err

- docs/en/deployment/how_to_use_on_kubernetes.md
- docs/en/tutorials/juicefs_on_kubesphere.md
- docs/en/tutorials/juicefs_on_rancher.md
- docs/zh_cn/deployment/how_to_use_on_kubernetes.md
> fix csi chart url

- .github/workflows/verify.yml
https://github.com/juicedata/juicefs/runs/5844494706?check_suite_focus=true
> CI:golangci error

- .github/workflows/encoding.yml
initial version to add workflow-dispatch.
> add encoding test workflow

- docs/en/deployment/s3_gateway.md
- docs/zh_cn/deployment/s3_gateway.md
> doc: add documentation for using the built-in juicefs version

- docs/en/deployment/hadoop_java_sdk.md
@davies @rayw000 大概翻译了一下，有一些专业词儿不确定对不对，还需要你们看一下 😊 谢谢
> translate hadoop_java_sdk.md kafka connect

- .travis.yml
- pkg/object/object_storage_test.go
- pkg/object/tikv.go
> implement List() for TiKV

- cmd/format.go
- pkg/meta/sql.go
> cmd/format: check error of loading setting and delete uuid object if initializing meta failed

- .travis.yml
- pkg/object/object_storage_test.go
- pkg/object/redis.go
- pkg/object/swift.go
> implement listall api for redis 

- pkg/meta/redis.go
Two clean functions should be OK without this fix since they are issues from old clients. But `CompactAll` is a necessary.
> meta/redis: fix parsing chunk key in CompactAll

- cmd/flags.go
- cmd/mount.go
> cmd: support using integer for duration flags

- docs/en/getting-started/for_local.md
> fix typo in quick start doc

- pkg/meta/redis.go
> meta: load into Redis cluster

- pkg/meta/sql.go
> meta: use upsert to update xattr for PG

- .github/workflows/codeql-analysis.yml
- .github/workflows/elastictest.yml
- .github/workflows/encoding.yml
- .github/workflows/fio_benchmark.yml
- .github/workflows/ltpfs.yml
- .github/workflows/ltpsyscallshead.yml
- .github/workflows/ltpsyscallsmiddle.yml
- .github/workflows/ltpsyscallstail.yml
- .github/workflows/mysqltest_bigtable.yml
- .github/workflows/mysqltest_smalltable.yml
- .github/workflows/mysqltest_smalltablelocal.yml
- .github/workflows/mysqltest_smalltablelocalchangedir.yml
- .github/workflows/pjdfstest.yml
- .github/workflows/redis_compile.yml
- .github/workflows/sync.yml
- .github/workflows/sysbench_smallfile_randrw.yml
- .github/workflows/sysbench_smallfile_seqrw.yml
- .github/workflows/tpcds.yml
- .github/workflows/tpch_clickhouse.yml
- .github/workflows/version_compatible.yml
Reverts juicedata/juicefs#1857.
> Revert "don't send slack on workflow_dispatch event"

- docs/en/comparison/juicefs_vs_alluxio.md
I find some typos and grammar errors and try to fix them. If I'm wrong, please let me know!
> fix typos and grammar errors

- docs/en/reference/command_reference.md
@davies Could you give a quick review on this proofread? only minor changes. Thanks! :)
> proofread command_reference.md

- pkg/meta/sql.go
> meta/sql: retry transaction after too many connections

- .github/workflows/tpch_clickhouse.yml
- .github/workflows/tpch_clickhouse_local.yml
**### fix du err**
du: cannot access '/data/jfs/store/9da/9da74d9d-b36c-4945-bd04-60d50bc[18](https://github.com/juicedata/juicefs/runs/6056110481?check_suite_focus=true#step:13:18)a40/tmp_merge_[19](https://github.com/juicedata/juicefs/runs/6056110481?check_suite_focus=true#step:13:19)95_369_400_1': No such file or directory
du: cannot access '/data/jfs/store/9da/9da74d9d-b36c-4945-bd04-60d50bc18a40/tmp_merge_1994_365_401_1': No such file or directory
du: cannot access '/data/jfs/store/9da/9da74d9d-b36c-4945-bd04-60d50bc18a40/tmp_merge_1997_367_403_1': No such file or directory
du: cannot access '/data/jfs/store/9da/9da74d9d-b36c-4945-bd04-60d50bc18a40/tmp_merge_1992_366_405_1': No such file or directory
More details refer to https://github.com/juicedata/juicefs/runs/6056110481?check_suit …
> CI: Add another clickhouse test using local disk to generate data

- pkg/meta/load_dump_test.go
- pkg/meta/redis.go
> meta/redis: fix loading into redis cluster

- pkg/vfs/vfs.go
> show correct length of .config

- pkg/vfs/vfs.go
> keep length of .stats as 0

- docs/en/benchmark/metadata_engines_benchmark.md
- docs/zh_cn/benchmark/metadata_engines_benchmark.md
ETCD -> etcd
reference the official site https://etcd.io
> fix incorrect case

- .github/workflows/tpch_clickhouse.yml
- .github/workflows/tpch_clickhouse_mode.yml
gcc -O -DDBNAME=\"dss\" -DLINUX -DDB2  -DSSBM  -O -o qgen build.o bm_utils.o qgen.o rnd.o varsub.o text.o bcd2.o permute.o speed_seed.o -lm
/usr/bin/ld: bm_utils.o: in function `yes_no':
bm_utils.c:(.text+0x5e): warning: the `gets' function is dangerous and should not be used.
*** invalid open call: O_CREAT or O_TMPFILE without mode ***: terminated
/home/runner/work/_temp/6a3efe4e-40bc-472f-8e7e-2ea28d81cb36.sh: line 5: 12322 Aborted                 (core dumped) ./dbgen -s 10 -T l -q
Error: Process completed with exit code 134.
https://github.com/juicedata/juicefs/runs/6084906534?check_suite_focus=true
> CI:tpch generate data err

- .github/workflows/tpch_clickhouse_mode_local.yml
The hosted runner: GitHub Actions 50 lost communication with the server. Anything in your workflow that terminates the runner process, starves it for CPU/Memory, or blocks its network access can cause this error.
More details may refer to https://github.com/juicedata/juicefs/actions/runs/2232077024 .
> CI: add a compared clickhouse action

- cmd/flags.go
- cmd/main.go
- docs/en/administration/fault_diagnosis_and_analysis.md
- docs/zh_cn/administration/fault_diagnosis_and_analysis.md
- go.mod
- go.sum
[Pyroscope](https://github.com/pyroscope-io/pyroscope) is an open source continuous profiling platform. It will help our:
+ Find performance issues and bottlenecks in your code
+ Resolve issues with high CPU utilization
+ Understand the call tree of your application
+ Track changes over time
> support pyroscope 

- .github/workflows/fio_benchmark.yml
eg, change size from 1G to 1M to test fast.
> support change size and nrfiles when dispatch fio workflow manually

- docs/en/deployment/how_to_use_on_kubernetes.md
Ref: https://github.com/juicedata/docs/issues/31
@AIXjing would you please review this PR when you get time? Thank you!
> proofread: how_to_use_on_kubernetes.md

- docs/en/deployment/how_to_use_on_kubernetes.md
- docs/zh_cn/deployment/how_to_use_on_kubernetes.md
- Updated documentation to align with the documentation on the CSI Driver project homepage
- Directs users to the CSI Driver's project homepage for more information
> Docs: update K8s user guide doc

- cmd/config.go
- cmd/destroy.go
- cmd/format.go
- cmd/fsck.go
- cmd/gateway.go
- cmd/gc.go
- cmd/mount.go
- pkg/object/object_storage_test.go
- sdk/java/libjfs/main.go
> reload configuration for data storage

- cmd/sync.go
> Misspelling

- docs/en/getting-started/for_local.md
- docs/zh_cn/getting-started/for_local.md
Perhaps, default path of Windows OS should be added!
> default path of Windows OS in doc is missing

- docs/en/deployment/s3_gateway.md
proofread: s3_gateway.md
Fix: https://github.com/juicedata/docs/issues/40
Hi @AIXjing , would you please review this PR when you get time? Thank you~
> proofread: s3_gateway.md

- pkg/meta/base.go
- pkg/meta/interface.go
- pkg/meta/redis.go
- pkg/meta/redis_test.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
- pkg/vfs/vfs.go
> meta: truncate trash entry name if it's too long

- pkg/meta/tkv.go
> meta/tkv: fix value of delSliceKey

- pkg/meta/info.go
- pkg/meta/redis.go
> meta/redis: check config 'maxmemory-policy'

- pkg/sync/sync.go
> no warning for mtime if it's not supported

- docs/en/tutorials/juicefs_on_colab.md
Let's add a tutorial doc for using juicefs in Colab :)
> docs: add colab tutorial

- pkg/meta/sql.go
> meta/sql: retry transaction for duplicate key in PG

- .github/workflows/codeql-analysis.yml
> Migrate to CodeQL v2

- pkg/meta/sql.go
- pkg/meta/sql_lock.go
- pkg/object/sql.go
> meta/sql: read database inside transaction

- cmd/gateway.go
- pkg/gateway/gateway.go
> clean up expired temporary files

- pkg/meta/redis_test.go
- pkg/meta/sql.go
> meta/sql: fix mount with read-only

- pkg/meta/base.go
- pkg/meta/interface.go
- pkg/meta/redis.go
- pkg/meta/redis_test.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
> meta: add parentKey to track all parents of a file

- .github/workflows/tpch_clickhouse.yml
- .github/workflows/tpch_clickhouse_limitcache.yml
- .github/workflows/tpch_clickhouse_mode.yml
- .github/workflows/tpch_clickhouse_mode_local.yml
https://github.com/juicedata/juicefs/actions/runs/2345918626
> CI: fix clickhouse generate data err

- cmd/objbench.go
add content check for downloaded files in object storage performance tests
> cmd/objbench: add content check 

- pkg/meta/base.go
- pkg/meta/redis.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
> meta: skip updating sliceRef if id is 0

- pkg/meta/sql.go
> meta/sql: fix retriable error message

- pkg/meta/sql.go
When select a few rows for update, the order of locks is not deterministic, it can result in deadlock.
This PR add a order for these queries to avoid deadlock.
closes #2099
> meta/sql: fix deadlock in PG

- cmd/mdtest.go
- pkg/meta/sql.go
> meta/sql: dump metadata in a single transaction

- pkg/object/file.go
- pkg/object/filesystem_test.go
> obj/file: Head of file should return File

- docs/en/administration/metadata/postgresql_best_practices.md
Added example for setting md5 method in pg_hba.conf
> Update postgresql_best_practices.md with example of md5 method

- pkg/chunk/cached_store.go
> chunk/store: keep cache after uploading staging blocks

- .github/workflows/aitests.yml
- .github/workflows/aitests_limitcache.yml
https://github.com/juicedata/juicefs/runs/6579559615?check_suite_focus=true
> CI:fix aitest timeout err

- cmd/load.go
- pkg/meta/base.go
- pkg/meta/redis.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
- pkg/utils/utils.go
> improve error message for load

- pkg/meta/redis.go
> meta/redis: check length of pipeline after loading every entry

- docs/en/development/io_processing.md
Hi @AIXjing , could you review this PR when you get time? Thank you!
link: https://github.com/juicedata/docs/issues/67
> translate io_processing.md

- pkg/object/sftp.go
> fix auth of sftp with multiple keys

- cmd/format.go
- cmd/gc.go
- cmd/mount.go
- cmd/warmup.go
- pkg/sync/config.go
- pkg/sync/sync.go
> check range of parameters

- cmd/rmr.go
- cmd/warmup.go
- pkg/meta/utils.go
- pkg/vfs/fill.go
> vfs: increase counter even if error occurred

- go.mod
- go.sum
> fix gateway list objects api

- pkg/meta/redis.go
> meta/redis: handle lua result from Redis v7.0+

- pkg/meta/sql.go
> add a workaround for CockroachDB

- pkg/chunk/disk_cache.go
> Fix stats of cached space in writeback mode

- pkg/meta/redis.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
> meta: add delayed slice only when chunkid > 0

- pkg/meta/base.go
- pkg/meta/redis.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
> fix index underflow in 32bit arch

- .github/workflows/tpch_clickhouse.yml
- .github/workflows/tpch_clickhouse_local.yml
> CI:fix clickhouse test err

- cmd/fsck.go
> cmd/fsck: fix object name for Head method

- go.mod
- go.sum
- pkg/object/webdav.go
> object/webdav: replace webdav client

- cmd/info.go
> cmd/info: Add an filter to exclude inode 0

- cmd/info.go
- cmd/info_test.go
- pkg/utils/utils.go
- pkg/vfs/internal.go
> cmd/info: make output more human friendly

- docs/en/tutorials/juicefs_on_colab.md
- docs/zh_cn/tutorials/juicefs_on_colab.md
> doc: improve juicefs_on_colab doc

- cmd/format.go
> obj: fix skip tls verify

- .github/workflows/release.yml
- sdk/java/pom.xml
need to added secret:
```
OSSRH_USERNAME
OSSRH_TOKEN
MAVEN_GPG_PRIVATE_KEY
MAVEN_GPG_PASSPHRASE
```
> hadoop: auto publish to maven center repo

- docs/en/reference/how_to_setup_object_storage.md
- docs/zh_cn/reference/how_to_setup_object_storage.md
> docs: add tips for TiKV

- docs/en/reference/how_to_setup_metadata_engine.md
- docs/zh_cn/reference/how_to_setup_metadata_engine.md
- pkg/meta/redis.go
- pkg/meta/utils.go
> meta/redis:support unix socket for redis

- pkg/fuse/context.go
> fuse/context: ignore interrupt within one second

- pkg/meta/base_test.go
- pkg/meta/redis.go
- pkg/meta/redis_lock.go
> meta/redis: fix unlock on not-existed lock

- README.md
- README_CN.md
- docs/en/faq.md
- docs/zh_cn/faq.md
- Update Chinese version README
- Update FAQ about Redis Cluster
- Add integration testing badge
> Docs: update Chinese version README

- pkg/object/ks3.go
> object/ks3: use virtual hosted-style for ks3

- pkg/meta/base.go
- pkg/meta/interface.go
> cmd/info: support get trash info

- .github/workflows/tpcds.yml
close https://github.com/juicedata/juicefs/issues/2339
> CI:fix tpcds err

- go.mod
- go.sum
> util: progressbar total equals current max

- .github/workflows/ltpfs.yml
https://github.com/juicedata/juicefs/runs/7364739989?check_suite_focus=true
https://github.com/juicedata/juicefs/runs/7397520505?check_suite_focus=true
> CI:fix ltpfs test failure

- docs/en/administration/metadata/postgresql_best_practices.md
@davies 稍微改动了一下，能否帮我review一下 :)  thx
L23-29 在中文文档上好像不一致，不知是否需要把中文文档update 一下？
> proofread:postgresql_best_practices.md

- docs/en/introduction/comparison/juicefs_vs_s3ql.md
proofread juicefs_vs_s3ql.md
Hi @AIXjing , could you please review this PR when you get time? Thanks!
> proofread juicefs_vs_s3ql.md

- docs/en/introduction/comparison/juicefs_vs_alluxio.md
close: https://github.com/juicedata/docs/issues/100
Hi @AIXjing , could you please review this PR when you have time? Thank you!
> proofread: alluxio

- cmd/mdtest.go
reference https://github.com/juicedata/jfs/issues/1274
> fix total files in mdtest

- README.md
- README_CN.md
> Docs: Fix wrong link

- README.md
- README_CN.md
- docs/en/community/integrations.md
- docs/en/introduction/README.md
- docs/zh_cn/community/integrations.md
- docs/zh_cn/introduction/README.md
Chinese version (Bilibili video):
> Docs: add JuiceFS introduction video to docs

- README.md
- README_CN.md
This should NOT be merged until the release of v1.0-GA.
> doc/README: update the status from beta to production ready

- docs/en/guide/cache_management.md
Hi @AIXjing , could you please review this PR when you get time? Thank you~
link to: https://github.com/juicedata/docs/issues/117
> proofread: cache_management.md

- docs/en/development/data_structures.md
I added a few more suggestions from Section 3.2 which I left last time. :)
> coninue:proofread

- README.md
Update README.md  add Qiniu Cloud Object Storage (Kodo)
> Update README.md  add Qiniu Cloud Object Storage (Kodo)

- pkg/chunk/cached_store.go
Once the cache manager is created, it may find staging blocks and start to upload them, which will crash if the metrics is not initialized.
close #2418
> init metrics before creating cache manager

- README.md
- README_CN.md
> fix juicefs on win 404 url

- docs/en/administration/destroy.md
link to: https://github.com/juicedata/docs/issues/124
Hi @AIXjing , could you please review this PR when you get time? Thank you!
> proofread: destroy.md

- docs/en/administration/sync_accounts_between_multiple_hosts.md
- docs/en/administration/upgrade.md
- docs/en/guide/quota.md
Hi @rayw000, could you please review this when you have time? Thanks :P
> proofread: sync_accounts and upgrade

- docs/en/deployment/hadoop_java_sdk.md
- docs/zh_cn/deployment/hadoop_java_sdk.md
juicefs.open-cache
juicefs.io-retries
juicefs.no-bgjob
juicefs.backup-meta
juicefs.heartbeat
juicefs.writeback
> hadoop-doc: add more docs for input params

- pkg/utils/clock_test.go
> CI: fix flaky TestClock

- docs/en/administration/monitoring.md
@rayw000  Could you please take a look at this document when you have time? Thank you~
> proofread:monitoring.md

- docs/en/deployment/hadoop_java_sdk.md
- docs/zh_cn/deployment/hadoop_java_sdk.md
- sdk/java/src/main/java/io/juicefs/JuiceFileSystem.java
- sdk/java/src/test/java/io/juicefs/JuiceFileSystemTest.java
use superfs for trash emptier to avoid permission issue
> hadoop: use superuser for trash emptier

- .github/workflows/unittests.yml
> CI: add main tigger to unittest

- sdk/java/src/main/java/io/juicefs/JuiceFileSystemImpl.java
- sdk/java/src/test/java/io/juicefs/JuiceFileSystemTest.java
Also compatible with hadoop2.6
> hadoop: compatible with hdfs for dfs.blocksize

- docs/en/administration/sync_accounts_between_multiple_hosts.md
- docs/en/reference/posix_compatibility.md
- docs/zh_cn/administration/sync_accounts_between_multiple_hosts.md
- docs/zh_cn/reference/posix_compatibility.md
closes https://github.com/juicedata/juicefs/issues/2559
> ACL is supported while extended ACL is not

- pkg/sync/sync.go
> cmd/sync: ignore invalid pattern

- cmd/bench.go
- cmd/objbench.go
- cmd/profile.go
- cmd/stats.go
- pkg/utils/logger.go
- pkg/utils/utils.go
Do not display colors in Windows.
close #2558
> fix windows color print

- docs/en/guide/how_to_set_up_metadata_engine.md
- docs/zh_cn/guide/how_to_set_up_metadata_engine.md
- pkg/meta/interface.go
- pkg/meta/interface_test.go
> meta/pg: fix pg socket connection

- docs/en/guide/how_to_set_up_metadata_engine.md
As discussed at https://github.com/juicedata/juicefs/discussions/2615
> [Docs] Document PRAGMA statements on SQLite3

- integration/Makefile
- integration/ioctl_test.sh
> CI: add integration test for ioctl

- pkg/object/minio.go
Signed-off-by: pigletfly <wangbing.adam@gmail.com>
fixes of https://github.com/juicedata/juicefs/issues/2671
> feat: set minion region via env

- docs/en/guide/how_to_set_up_object_storage.md
- docs/zh_cn/guide/how_to_set_up_object_storage.md
improve https://github.com/juicedata/juicefs/pull/2673
> doc: improve minio doc

- pkg/object/hdfs.go
To solve an application problem, when I try to do single copy, I found this hardcoded.
> feat[hdfs]: Support self-configuring the dfs.replication

- Makefile
Signed-off-by: pigletfly <wangbing.adam@gmail.com>
> docs: add cross compiling comments for windows

- cmd/gateway.go
- cmd/mdtest.go
- cmd/mount.go
- pkg/chunk/cached_store.go
- sdk/java/libjfs/main.go
> fix zero cache size .config display

- docs/zh_cn/introduction/README.md
> Docs: fix iframe hight of the introduction video

- pkg/utils/logger.go
- pkg/utils/logger_syslog.go
> fix thread safety in logger

- pkg/vfs/backup.go
> vfs/backup: use OS temp file instead of /tmp

- docs/en/grafana_template.json
- docs/en/grafana_template_k8s.json
> fix grafana template go goroutines

- go.mod
- go.sum
> dependency: use stable version of go-sqlite3

- go.mod
- go.sum
> cmd/gateway: fix gateway 1.18 compatibility

- pkg/meta/sql.go
> meta/sql: fix get session

- .github/actions/clickhouse/action.yml
- .github/workflows/tpch_clickhouse.yml
Refer to the action https://github.com/juicedata/juicefs/actions/runs/3033259025/jobs/4881365370 .
> CI:fix git clone err

- cmd/objbench.go
> create bucket first when run objebench with skip-functional-tests

- docs/en/guide/how_to_set_up_object_storage.md
- docs/zh_cn/guide/how_to_set_up_object_storage.md
> doc: improve Storj doc

- .github/scripts/testVersionCompatible.py
- .github/scripts/utils.py
- .github/workflows/version_compatible_hypo.yml
- .gitignore
test result: https://github.com/juicedata/juicefs/actions/runs/3094713607
> CI: add mysql and postgres as storage in version compatible test

- .github/actions/load/action.yml
- .github/workflows/load.yml
Reverts juicedata/juicefs#2790
> Revert "CI:rm load bagerdb test"

- docs/en/administration/fault_diagnosis_and_analysis.md
- docs/en/reference/command_reference.md
- docs/zh_cn/administration/fault_diagnosis_and_analysis.md
- docs/zh_cn/reference/command_reference.md
> docs: doctor command reference

- .github/workflows/load.yml
test result: https://github.com/juicedata/juicefs/actions/runs/3155769950/jobs/5134791640
> CI: add fdb to load test

- go.mod
- go.sum
> fix gateway 1.18 compatibility (#2734)

- docs/en/guide/cache_management.md
As discussed at https://github.com/juicedata/juicefs/discussions/2841
> doc: add note about writeback mode

- cmd/sync.go
- cmd/sync_test.go
- docs/en/development/data_structures.md
- docs/en/guide/sync.md
- docs/en/reference/command_reference.md
- docs/zh_cn/guide/sync.md
- docs/zh_cn/reference/command_reference.md
> cmd/sync: the sync command adds the session token feature

- pkg/meta/redis.go
- pkg/meta/slice.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
> meta: check whether the value of slices is corrupt

- cmd/dump.go
- cmd/dump_test.go
- cmd/load.go
> load/dump a gzip compressed JSON file

- .github/workflows/tpcds.yml
https://github.com/juicedata/juicefs/actions/runs/3358974577/jobs/5566523800
> CI: fix tpcds test failure.

- docs/en/deployment/s3_gateway.md
- docs/zh_cn/deployment/s3_gateway.md
As shown in the title.
- doc(deployment/s3_gateway): added daemon-support (en)
- doc(deployment/s3_gateway): added daemon-support (zh-cn)
> [Docs/deployment/s3_gateway] Add daemon support

- cmd/main.go
> ignore log when the level equals info

- docs/zh_cn/faq.md
经过一番梳理，把 FAQ 中的问题分成了以下几个类目：
- 一般问题
- 元数据相关问题
- 对象存储相关问题
- 性能相关问题
- 访问相关问题
cc @davies @SandyXSD
> Docs: update the layout of zh_cn/faq.md

- integration/s3gateway_test.sh
- pkg/gateway/gateway.go
> gateway: fix s3gateway head dir return 200 but expect 404

- docs/en/reference/command_reference.md
- docs/zh_cn/reference/command_reference.md
> update desc of shards

- docs/en/getting-started/README.md
- docs/en/getting-started/installation.md
- docs/en/introduction/README.md
- docs/zh_cn/getting-started/README.md
- docs/zh_cn/getting-started/installation.md
- docs/zh_cn/introduction/README.md
closes https://github.com/juicedata/docs/issues/305
> fix pagination links

- pkg/object/bos.go
> object/bos: set http or https using an endpoint provided by the user

- sdk/java/src/main/java/io/juicefs/JuiceFileSystemImpl.java
- sdk/java/src/test/java/io/juicefs/JuiceFileSystemTest.java
1. old while condition code will cost a lot of time
2. use directbuffer is as quick as heapbuffer and will avoid copy from native to java heap if the pass-in ByteBuffer is direct
speed up from 479.85 MB/s to 5692.05 MB/s when read 128KB once a time in 1 thread circumstance
> hadoop: speed up read

- cmd/dump.go
- cmd/gateway.go
- cmd/mdtest.go
- cmd/mount.go
- cmd/status.go
- pkg/meta/base.go
- pkg/meta/interface.go
- pkg/meta/load_dump_test.go
- pkg/meta/redis.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
- pkg/meta/utils.go
> meta: adjust root inode after loading format

- .github/scripts/setup-hdfs.sh
- .github/workflows/mutate-test.yml
- .github/workflows/unittests.yml
> CI: ensure HDFS service is ready

- sdk/java/libjfs/main.go
- sdk/java/pom.xml
- sdk/java/src/main/java/io/juicefs/JuiceFileSystemImpl.java
- sdk/java/src/test/java/io/juicefs/JuiceFileSystemTest.java
mvn test-compile org.pitest:pitest-maven:mutationCoverage
> hadoop: add pitest

- sdk/java/libjfs/main.go
close https://github.com/juicedata/juicefs/issues/3038
> add timeout for pushgateway

- pkg/meta/sql.go
Close https://github.com/juicedata/juicefs/issues/2645 and https://github.com/juicedata/juicefs/issues/2681
According to https://github.com/mattn/go-sqlite3/issues/274, writing operations of sqlite3 conflict with all other operations, not only `Mknod`. This problem causes "database is locked" errors in some cases. So, this PR set global lock for the sqlite3 transaction.
```bash
> juicefs bench -p 128 /mnt/jfs
```
- no global lock
- with global lock
> set global lock for sqlite3 transaction

- integration/s3gateway_test.sh
The new version of awscli corrects the error code on Mac from 254 to 255.
> CI: change error code of mac to 255

- pkg/object/s3.go
> fix oracle ep parse error

- cmd/flags.go
- docs/en/deployment/hadoop_java_sdk.md
- docs/en/reference/command_reference.md
- docs/zh_cn/deployment/hadoop_java_sdk.md
- docs/zh_cn/reference/command_reference.md
- sdk/java/src/main/java/io/juicefs/JuiceFileSystemImpl.java
> cmd: increase default value of max-deletes from 2 to 10

- cmd/mount.go
> cmd/mount: add exit message

- pkg/fuse/fuse.go
> print more friendly error message when fuse not installed

- pkg/meta/base.go
- pkg/meta/base_test.go
- pkg/meta/redis.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
- pkg/meta/tkv_badger.go
- pkg/meta/tkv_etcd.go
- pkg/meta/tkv_fdb.go
- pkg/meta/tkv_mem.go
- pkg/meta/tkv_prefix.go
- pkg/meta/tkv_test.go
- pkg/meta/tkv_tikv.go
> meta: limit cleanupDelayedSlices by time

- pkg/meta/tkv_tikv.go
> meta/tikv: add pid info in tikv log

- pkg/object/obs.go
> object/obs: ignore etag check when obs enable encrypted

- cmd/gateway.go
> gateway&webdav: clean session when gateway or webdav service exit

- pkg/chunk/disk_cache.go
> cleanup cached objects during scaning

- docs/zh_cn/community/adopters.md
- docs/zh_cn/community/articles.md
> add adopters, and articles

- .github/workflows/unittests.yml
- integration/s3gateway_test.sh
The error code of the old and new versions of awscli is different, causing gateway test failure.
> CI: fix error code

- docs/en/security/encrypt.md
> [docs] Data encryption: Fix typo

- pkg/object/oss.go
ref https://github.com/juicedata/juicefs/commit/6ffdc4ff429c35789a5ba7bdba63df2848385db8
close #3136
> object/oss: support http proxy form env

- docs/en/grafana_template.json
- docs/en/grafana_template_k8s.json
> add grafana panel for staging block

- docs/en/grafana_template.json
- docs/en/grafana_template_k8s.json
> Set yaxes to 0 for the Transaction Restart, Compacted Data and Compaction plane

- .github/workflows/check-doc.yaml
- README.md
- README_CN.md
Ref: https://github.com/badges/shields/issues/8671
> Doc: fix badger display

- pkg/meta/config.go
> cmd/status: show trashday even it is zero

- integration/s3gateway_test.sh
ref https://github.com/juicedata/jfs/pull/1647
> imporve gateway test

- cmd/debug.go
Ignore unexpected entries from lsof
ref https://github.com/juicedata/jfs/pull/1639
> ignore lsof output include `lsof: no pwd entry for UID xxx`

- pkg/meta/sql.go
recreated session after some fault #3183
> recreated session after some fault

- pkg/meta/base.go
- pkg/meta/interface.go
- pkg/meta/redis.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
> meta: recreate the session with info if it was cleaned before

- pkg/object/obs.go
> object/obs: fix obs encrypt check

- docs/en/deployment/s3_gateway.md
- docs/zh_cn/deployment/s3_gateway.md
should be consistent with the one in the helm template https://github.com/juicedata/charts/blob/e0cfbb8cd4144795b8fdac906358a40bff4c285a/charts/juicefs-s3-gateway/templates/ingress.yaml#L1
> docs: should be 'enabled'

- docs/en/deployment/hadoop_java_sdk.md
- docs/en/reference/command_reference.md
- docs/zh_cn/deployment/hadoop_java_sdk.md
- docs/zh_cn/reference/command_reference.md
related:
* https://github.com/facebook/docusaurus/issues/3822
* https://github.com/facebook/docusaurus/issues/8591
> avoid using TabItem with a single child

- pkg/meta/redis.go
> disable server name check for sentinel

- cmd/format.go
ref https://github.com/juicedata/juicefs/pull/3235/commits/74c4a668ff3528b5b7d62a80755b9fd5e61c71e1
> cmd/format: update hash prefix desc

- cmd/sync.go
> remove the password from the sync process display

- pkg/object/minio.go
> object/minio: add query parameters to the minio object storage

- pkg/meta/redis.go
> fix incorrect nil check on doRename with redis

- pkg/object/obs.go
> object/obs: fix obs list encode

- cmd/objbench.go
- go.mod
- go.sum
- pkg/object/cos.go
- pkg/object/object_storage_test.go
- pkg/object/obs.go
- pkg/object/prefix.go
- pkg/object/qingstor.go
- pkg/object/restful.go
- pkg/object/tos.go
- pkg/utils/utils.go
1. fix obs & tos range get
2. check get response status code  ref https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Range
3. improve objbench cmd
> object/obs&tos : fix range get

- pkg/object/sql.go
> object/sql: fix SQL parameter types

- go.mod
- go.sum
> meta/badger: update BadgerDB to v3.2103.5

- cmd/format.go
- cmd/load.go
> cmd/load: support load encrypted file

- cmd/objbench.go
- pkg/object/object_storage_test.go
close #3306
CI fixed by  #3310
> cmd/objbench: check list error

- pkg/object/bos.go
- pkg/object/cos.go
- pkg/object/ibmcos.go
- pkg/object/interface.go
- pkg/object/ks3.go
- pkg/object/object_storage.go
- pkg/object/object_storage_test.go
- pkg/object/obs.go
- pkg/object/oss.go
- pkg/object/prefix.go
- pkg/object/qingstor.go
- pkg/object/s3.go
- pkg/object/scs.go
- pkg/object/tos.go
> add uploadPartCopy api

- go.mod
- go.sum
A user reported that when synchronizing files from the server to Minio, an error occurred after more than an hour of synchronization, with an error message indicating "SSH_FX_FAILURE." 
This may also be related to the issue https://github.com/rclone/rclone/issues/5806
close #3320
> object/sftp: upgrade sftp

- .markdownlint-cli2.jsonc
- docs/zh_cn/introduction/README.md
There are two change in this PR:
1. Repalce the <BilibiliEmbedRenderer /> tag with the native iframe tag, but remain the settings.
2. Switch off the autoplay action.
> Docs: keep the intro video not play automatically

- pkg/meta/redis.go
> meta/redis: log the error command for scans

- pkg/meta/redis.go
A pipeline inside a Redis transaction will end current transaction, so we can't use pipeline to read data.
> meta/redis: fix transacion of copy_file_range

- pkg/meta/redis.go
> meta/redis: support tls-ca-cert-file

- Makefile
- cmd/fsck_test.go
- cmd/info_test.go
- cmd/main.go
- cmd/warmup_test.go
> CI: try increasing the GOMAXPROCS for unittests

- cmd/format.go
> cmd/format: remove testing dir after test

- pkg/chunk/disk_cache.go
- pkg/chunk/disk_cache_test.go
> metric: fix `stageBlockBytes` calculation method

- pkg/meta/base.go
- pkg/meta/base_test.go
- pkg/meta/interface.go
> cmd/fsck: returns non-zero status code if there's error occurred during the fsck

- pkg/meta/base_test.go
- pkg/meta/redis.go
https://github.com/juicedata/juicefs/actions/runs/4571811668/jobs/8071710842
`
base_test.go:2204: added space: 65536
`
> test: fix testclone test

- .github/workflows/unittests.yml
- Makefile
Reverts juicedata/juicefs#3463
> Revert "CI: run unit tests parallel"

- go.mod
- go.sum
> upgrade version of go-fuse: catch and recover panic

- .github/workflows/unittests.yml
- pkg/meta/tkv_test.go
> CI: install etcd in action

- cmd/object.go
- pkg/sync/sync.go
> sync/jfs: log the error when it fails to delete a temp file

- cmd/main.go
> cmd/sync: do not edit  original os.Args

- .github/workflows/unittests.yml
- Makefile
- pkg/meta/base_test.go
- pkg/meta/load_dump_test.go
- pkg/meta/sql_test.go
- pkg/meta/tkv_test.go
- pkg/object/object_storage_test.go
This PR keeps the unit test run time under 10 minutes.
> CI: split unit test

- pkg/fs/fs.go
- pkg/fs/fs_test.go
> fix possible data race in pkg/fs

- pkg/meta/redis.go
Adding some connection pool parameters of redis。
> fix: add redis options of conn pool

- pkg/meta/redis.go
when redis failed to ping, record error log.
> fix: add error log for redis ping

- pkg/meta/dump.go
- pkg/meta/load_dump_test.go
- pkg/meta/metadata-sub.sample
- pkg/meta/metadata.sample
- pkg/meta/redis.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
> quota: support dump and load

- pkg/meta/base.go
> meta: fix wrong parent inode for hardlinked files in updateParentStat

- cmd/bench.go
- cmd/debug.go
- cmd/mount.go
- cmd/mount_unix.go
- cmd/profile.go
- cmd/rmr.go
- cmd/stats.go
- cmd/umount.go
- pkg/meta/interface.go
- pkg/vfs/vfs.go
> cmd/mount: add `prefix-internal` option to prefix internal files by .jfs

- .github/scripts/apt_install.sh
https://manpages.debian.org/buster/apt/apt.8.en.html#SCRIPT_USAGE_AND_DIFFERENCES_FROM_OTHER_APT_TOOLS
> Switch to apt-get

- .github/workflows/bash/rm_fs
> CI/ltptest: add rwtest03 back

- .github/workflows/verify.yml
> CI: improve ceph test

- cmd/objbench.go
Assume that user `nobody` exists on any unix system.
close #3639
> cmd/objbench: lookup nobody group first

- pkg/sync/download_test.go
> ci/testdownload:close parallelDownloader

- cmd/debug.go
set default log limit and return error when find more than one mount process
> cmd/debug: set default log limit 

- pkg/meta/redis.go
When the meta engine is Redis Cluster, it will retry all the transactions if any syscall.Errno returned.
This PR avoid the un-useful retry.
closes #3294
> meta/redis: fix retry transactions in Redis Cluster

- cmd/flags.go
- pkg/meta/tkv.go
- sdk/java/src/main/java/io/juicefs/JuiceFileSystemImpl.java
> meta/tkv: skip update nlink of dir after retried 20 times

- cmd/clone.go
- pkg/meta/base_test.go
- pkg/meta/redis.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
> cmd/clone: fix clone mode

- pkg/meta/base.go
- pkg/meta/base_test.go
- pkg/meta/config.go
- pkg/meta/sql_test.go
- pkg/meta/tkv_test.go
- test.sh
> make dir stat flush period configrable

- cmd/format.go
We should use `config` command instead.
> remove --upload-limit/--download-limit from format command

- pkg/vfs/internal.go
> cmd/rmr: only warning for error of InvalidateEntry

- pkg/meta/base.go
> don't check volume quota for hardlink

- pkg/meta/base.go
> fix quota staging usage loss

- pkg/meta/tkv.go
> meta/tkv: fix the issue that the same slice may be appended for multiple times

- cmd/sync.go
- pkg/object/hdfs.go
- pkg/object/object_storage_test.go
Reverts juicedata/juicefs#3717
> Revert "cmd/sync: fix duplicated path in HDFS"

- pkg/meta/sql.go
- pkg/meta/tkv.go
> volume quota: fix temporary usage loss in memory

- cmd/objbench.go
- pkg/object/file.go
> object/file: convert relative paths to absolute paths first

- pkg/meta/base.go
> cmd/fsck: fix check for root inode

- pkg/meta/tkv.go
> meta/tkv: fix stats

- cmd/sync.go
> cmd/sync: sftp and jfs support symlink

- pkg/object/object_storage_test.go
- pkg/object/obs.go
object/obs: convert storage class `obs.StorageClassWarm` to `STANDARD_IA`
> object/obs: convert  obs storage class

- go.mod
- go.sum
> cmds: downgrade cli to v2.19.3 to keep previous behavior of help flag

- pkg/meta/base.go
> meta: fix overwritten attr after timeout

- docs/en/guide/dir-stats.md
- docs/en/guide/quota.md
- docs/zh_cn/guide/dir-stats.md
- docs/zh_cn/guide/quota.md
* translate dir-stats.md
* minor tone fix, minor improvements
> docs: translate dir-stats.md

- pkg/object/hdfs_kerberos.go
https://github.com/juicedata/juicefs/issues/3817
It works well in our cluster as below.
we can set ``KRB5KEYTAB_BASE64`` instead of ``KRB5KEYTAB``.
```sh
$ cat keytab | base64
XXXXXXXXXXXXXXXXXXXXXXXXXXXX....
$ cat juicefs-format.sh
#!/bin/bash
export HADOOP_CONF_DIR=hadoop-conf
export KRB5_CONFIG=krb5.conf
export HADOOP_USER_NAME=kyungwan-nam
export KRB5KEYTAB_BASE64="XXXXXXXXXXXXXXXXXXXXXXXXXXXX...."
export KRB5PRINCIPAL="kyungwan-nam@EXAMPLE.COM"
export JUICEFS_DEBUG=debug
juicefs format \
--storage hdfs \
--access-key kyungwan-nam \
--bucket hdfs://example/user/kyungwan-nam/jfs-test \
sqlite3://myjfs.db \
myjfs
$ /bin/sh juicefs-format.sh
2023/06/15 21:47:47.589401 juicefs[159954] <INFO>: Meta address: sqlite3://myjfs.db [interface.go:494]
2023/06/15 21:47:47.594122 juicefs[159954] …
```
> Support base64 encoded keytab for hdfs

- pkg/meta/base.go
- pkg/meta/redis.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
> meta: used cached atime even when opencache disabled

- cmd/fsck.go
> fsck: ignore chunks of delfiles

- pkg/meta/tkv_mem.go
> meta/memkv: fix the conflict between scan and write operations

- cmd/objbench.go
- pkg/object/ceph.go
> objbench: fix ceph panic when put empty file

- cmd/objbench.go
- pkg/object/ceph.go
> cmd/objbench: refactor error print

- docs/en/administration/fault_diagnosis_and_analysis.md
- docs/en/administration/metadata/redis_best_practices.md
- docs/en/deployment/s3_gateway.md
- docs/en/guide/sync.md
- docs/en/reference/command_reference.md
- docs/zh_cn/administration/fault_diagnosis_and_analysis.md
- docs/zh_cn/administration/metadata/redis_best_practices.md
- docs/zh_cn/deployment/s3_gateway.md
- docs/zh_cn/guide/sync.md
- docs/zh_cn/reference/command_reference.md
> doc: refactor command reference doc

- cmd/sync.go
> cmd/sync: sync custom endpoint env without mount point

- go.mod
- go.sum
- integration/ioctl_test.sh
- pkg/fuse/fuse.go
- pkg/vfs/vfs_unix.go
> vfs: fix ioctl result and support FS_IOC_FSGETXATTR cmd

- docs/en/introduction/comparison/juicefs_vs_alluxio.md
No need for Chinese doc updates
> docs : fix grammar issues, improve wording, add a description for juicefs_vs_alluxio.md

- docs/en/reference/command_reference.md
- docs/zh_cn/reference/command_reference.md
> doc: update `-manager-addr` doc

- .github/scripts/command/sync.sh
- .github/workflows/command.yml
- pkg/sync/sync.go
Reverts juicedata/juicefs#3941
> Revert "CI: test symlink for dir"

- pkg/utils/logger_syslog.go
Syslog could be slow or unavailable sometimes, it should not block logging.
> write syslog in background

- docs/en/getting-started/installation.md
- docs/zh_cn/getting-started/installation.md
close #https://github.com/juicedata/juicefs/issues/3975
> doc: updated install script description

- docs/en/guide/clone.md
Clarify the usage of the clone command.
> docs: Add note about space used by clone command

- pkg/object/file.go
- pkg/object/nfs.go
> fix nfs: get correct owner and group for file

- docs/en/reference/how_to_set_up_metadata_engine.md
- docs/zh_cn/reference/how_to_set_up_metadata_engine.md
> doc: improve redis documentation about `insecure-skip-verify`

- go.mod
- go.sum
- pkg/object/nfs.go
- pkg/object/object_storage_test.go
> object/nfs: fix nfs list api and readDirPlus api

- pkg/object/hdfs.go
ref https://github.com/colinmarc/hdfs/commit/f2f512db170db82ad41590c4ba3b7718b13317d2
> object/hdfs: remove the unnecessary error type conversions

- cmd/bench.go
- cmd/clone.go
- cmd/mdtest.go
- cmd/object.go
- pkg/meta/base.go
- pkg/object/file.go
- pkg/object/hdfs.go
- pkg/object/nfs.go
- pkg/object/sftp.go
> fix path in Windows

- pkg/object/oss.go
In case Aliyun ECS meta server is not available temporarily.
> oss: retry fetch STS token in newOSS()

- pkg/object/gluster.go
typo: rename all receivers to g
> typo: rename all receivers to g

- go.mod
- go.sum
- pkg/object/cos.go
> object/cos: fix multipart upload with long key

- pkg/meta/base_test.go
fix flaky test https://github.com/juicedata/juicefs/actions/runs/7138303397/job/19439637571?pr=4241
> CI: don't check space size after clone test

- .github/workflows/command.yml
will enable it when it is stable.
> CI: disable command test for pr

- cmd/object.go
> object/jfsobj: fix bug with opening files instead of creating them

- pkg/object/sftp.go
> cmd/sync: don't create dir when create sftp endpoint.

- cmd/sync.go
> cmd/sync: fix sync cmd with `sftp://`

- sdk/java/libjfs/guid.go
- sdk/java/libjfs/main.go
remove old guid from map when update
> sdk/java: fix guid update

- docs/zh_cn/guide/cache.md
> Remove duplicate paragraphs

- cmd/sync.go
- pkg/gateway/gateway.go
> sync: fix trim prefix

- pkg/meta/redis.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
> cmd/dump: change missing attribute to warning log level

- sdk/java/libjfs/main.go
- sdk/java/src/main/java/io/juicefs/JuiceFileSystemImpl.java
> hadoop: add the `cache-expire` option

- .github/workflows/resources/vdbench_big_file.conf
- .github/workflows/resources/vdbench_long_run.conf
- .github/workflows/resources/vdbench_small_file.conf
- .github/workflows/vdbench.yml
1. Use vdbench-jn parameter to verify data consistency 
2.  3. Add log check
3.   Add 20 minutes of data consistency test
> Added vdbench consistency check and result check

- .github/workflows/resources/vdbench_long_run.conf
- .github/workflows/vdbench.yml
> Reduce test data

- pkg/object/interface.go
- pkg/sync/sync.go
> fix build in 32 bit

- pkg/sync/sync.go
- pkg/sync/sync_test.go
> sync: fix match two star

- pkg/sync/sync.go
- pkg/sync/sync_test.go
> sync: fix sync filter with two star

- pkg/meta/base.go
- pkg/meta/base_test.go
> fix: skip acl check when mask is 0

- cmd/mount_unix.go
- pkg/meta/base.go
> mount: exit when the file system changes

- pkg/meta/sql.go
> fix dump trash nlink

- cmd/mount.go
- docs/en/deployment/hadoop_java_sdk.md
- docs/en/reference/command_reference.md
- docs/zh_cn/deployment/hadoop_java_sdk.md
- docs/zh_cn/reference/command_reference.md
- sdk/java/libjfs/main.go
changed the delimiter to ``;`` instead of ``,``
> Delimiter for --custom-labels need to change

- .github/scripts/command/gateway.sh
- .github/workflows/command.yml
> CI:add gateway test

- cmd/gateway.go
- cmd/mount.go
- cmd/mount_unix.go
- cmd/mount_windows.go
> gateway&webdav: correct relative path parameters when running in the background

- .github/workflows/command.yml
> CI:fix command test

- pkg/object/tos.go
https://www.volcengine.com/docs/6349/93461
> tos:adjust tos min part size

- pkg/gateway/gateway.go
> gateway：fix the way bucket paths are calculated in multi-bucket mode

- pkg/vfs/vfs.go
> fix: invalidate attr after set acl

- cmd/gateway.go
- cmd/mount_unix.go
- cmd/mount_windows.go
- cmd/webdav.go
> gateway&webdav: check the server port when running in the background to determine if the service has started normally

- pkg/chunk/cached_store.go
- pkg/vfs/writer.go
Reverts juicedata/juicefs#4694
> Revert "Prepare slice id eagerly to have a stable and predictable write buffer usage"

- pkg/meta/sql.go
> cmd/clone: set the attr should be done after checking permissions

- docs/en/deployment/s3_gateway.md
- docs/en/faq.md
- docs/en/guide/gateway.md
Via https://github.com/juicedata/juicefs/pull/4677
> docs: improve the gateway doc

- pkg/meta/dump.go
- pkg/meta/redis.go
> meta: move entryPool from redis to dump.go

- pkg/meta/dump.go
> cmd/dump: fix DumpedCounters to prevent unexpected panics

- cmd/warmup.go
- pkg/vfs/fill.go
- pkg/vfs/internal.go
> cmd/warmup: periodically refresh cache bytes progress

- cmd/mount_unix.go
> cmd/mount: fix FUSE option for ACL

- cmd/debug.go
> cmd/debug: support for information collection mode in dual-process mode

- cmd/mount_unix.go
> do not check mp when graceful upgrade

- pkg/sync/cluster.go
> sync: fix concurrent stats update in cluster mode

- pkg/vfs/backup.go
backup metadata succeed, fast mode: false, target: "s3://spark-juicefs/spark/meta/dump-2024-05-07-072350.json.gz", used 8m5.737019189s [backup.go:82]
> Backup report also outputs target path

- cmd/mount_unix.go
- pkg/vfs/accesslog.go
- pkg/vfs/handle.go
> dump the unread portion of the access log

- pkg/meta/redis.go
- pkg/meta/tkv.go
> cmd/clone: fix src mode check

- go.mod
- go.sum
> cmd/gateway: fix empty bucket display exception

- pkg/sync/cluster.go
- pkg/utils/utils.go
> sync: limit the total size of each batch task from the manager

- go.mod
- go.sum
ref https://github.com/juicedata/minio/commit/2e3d9abd61401d43fe0a724570d395f8ec191c7e
> cmd/gateway: fix gateway add and list service account

- pkg/meta/base.go
- pkg/meta/base_test.go
> meta: fix protection check for compaction

- docs/en/guide/gateway.md
- docs/zh_cn/guide/gateway.md
- docs/zh_cn/reference/command_reference.md
- Change the alias name from `myminio` to `myjfs`
- ~~Remove the `mc mb xxx` command since it doesn't support it for now~~
> Update S3 Gateway documents

- docs/en/grafana_template.json
> Update grafana dashboard

- sdk/java/src/main/java/io/juicefs/JuiceFileSystemImpl.java
fix pr https://github.com/juicedata/juicefs/pull/4407
> Hadoop: fix libjfs singleton

- docs/zh_cn/guide/gateway.md
> Docs: Update gateway.md

- cmd/mount.go
> fix: run on win

- pkg/sync/sync.go
Fix concurrent error handling in multipart copy operation
> Sync：Fix concurrent error handling in multipart copy operation

- pkg/meta/tkv_badger.go
> badger: disable badger metrics

- .github/workflows/check-doc.yaml
- docs/zh_cn/community/adopters.md
remove environment column,
add use cases,
add adopters,
> refactor adopter list, remove environment column

- pkg/meta/quota.go
> quota: fixed a bug where hardlink's quota update in the same directory was incorrect

- cmd/debug_test.go
- cmd/gc_test.go
- cmd/info_test.go
- cmd/mount_test.go
- cmd/status_test.go
- go.mod
remove convey and fix unit test
> fix: unit test

- go.mod
- go.sum
- pkg/fuse/fuse.go
- pkg/fuse/fuse_test.go
- pkg/vfs/vfs.go
ref: #5014
test:
- bench success
- restart success
> feat: update gofuse to 2.5.1

- cmd/mount_unix.go
> feat(fuse): support /dev/fd/N mount point

- pkg/meta/base.go
- pkg/meta/utils.go
> enhance(cmd): quit background task when tool exit

- go.mod
- go.sum
close https://github.com/juicedata/juicefs/issues/5047
> fix panic build with go1.23

- pkg/vfs/vfs.go
> fix/win: windows read error

- pkg/meta/base.go
- pkg/meta/base_test.go
> meta: clean symlink cache

- pkg/chunk/prefetch.go
We observed a large read amplification when user is doing an incremental but non-continuous sequential read on large amount of files. After labeling object GET requests with purpose, we found prefetching is the main cause of the read amplification.
It turns out the deduplication in `prefetcher::do` method does not work as expected especially when there is only one prefetcher (the default behavior), which caused duplicated prefetching. Instead, it's better to do deduplication before inserting into the `pending` queue.
> cache: dedup prefetch requests to avoid read amplification

- docs/en/security/encryption.md
> doc: fix wrong mount command

- pkg/meta/base_test.go
- pkg/meta/slice.go
> meta: in compaction don't skip the first slice if it's duplicated

- go.mod
- go.sum
> gateway: fix nil in list

- pkg/gateway/gateway.go
> gateway: keep leaf directory

- pkg/meta/base.go
- pkg/meta/base_test.go
- pkg/meta/quota.go
> meta: improve performance of statfs

- pkg/chunk/disk_cache.go
> cache: add log when create dir failed

- cmd/config.go
- cmd/quota.go
- pkg/meta/base.go
- pkg/meta/base_test.go
- pkg/meta/interface.go
- pkg/meta/quota.go
close https://github.com/juicedata/juicefs/issues/5179
> quota: add `--create` to create the directory if not exists

- sdk/java/src/main/java/io/juicefs/JuiceFileSystemImpl.java
Add Override for overriding and implementing methods `JuiceFileSystemImpl`
> sdk/java: Add @Override for overriding and implementing methods

- cmd/mount_unix.go
Thanks @halsbox for the feedback
close https://github.com/juicedata/juicefs/issues/5206
> cmd/mount: pass the signal to the child process

- pkg/chunk/cached_store.go
When stage disk hangs for a long time, user will get an EIO finally. We can avoid this fatal error by applying `PutTimeout` to stage writings too.
https://github.com/juicedata/juicefs/blob/fd191eadc403a30441a3aee291a8c8622b2aa32a/pkg/vfs/writer.go#L360-L362
> Add timeout for stage writings to avoid EIO when it hangs for more than 5 minutes

- docs/en/introduction/comparison/juicefs_vs_seaweedfs.md
Update juicefs_vs_seaweedfs.md via https://github.com/juicedata/juicefs/pull/5235
> docs: Update wording

- pkg/gateway/gateway.go
Reverts juicedata/juicefs#5257
> Revert "gateway: set xattr before rename to ensure consistency"

- pkg/fuse/device_linux.go
> Better to close file explicitly

- go.mod
- go.sum
> fix panic build with go1.23 (#5108)

- sdk/java/src/main/java/io/juicefs/JuiceFileSystemImpl.java
fix https://github.com/juicedata/juicefs/issues/5336
> override fs.permissions.umask-mode to juicefs.umask

- docs/en/guide/gateway.md
Via https://github.com/juicedata/juicefs/pull/5353
> docs: update wording for gateway.md

- cmd/restore.go
So that user knows where to find those restored files:
```log
restored 9 files in 2024-12-13-14 [doRestore@restore.go:141]
restored 1 files to "/shared-storage/gpu" [doRestore@restore.go:143]
restored 8 files to "/shared-storage/gpu/web_quality_model2" [doRestore@restore.go:143]
```
> cmd/restore: output restored dirs and stats

- cmd/load.go
- pkg/meta/tkv_bak.go
> cmd/load: fix kv stats

- pkg/meta/redis_bak.go
> backup/redis: remove key 'setting' from symlinks

- cmd/mount.go
- cmd/mount_unix.go
- pkg/fuse/fuse.go
- pkg/vfs/vfs.go
- pkg/vfs/vfs_test.go
close #5357
getxattr return ENODATA
setxattr/removexattr return ENOTSUP
> vfs/xattr: support filtering xattr request by label

- pkg/object/minio.go
- pkg/object/object_storage_test.go
> object/minio: support for MinIO storage class

- pkg/chunk/cached_store.go
- pkg/chunk/disk_cache.go
- pkg/chunk/disk_cache_test.go
- pkg/chunk/mem_cache.go
we don't need to open and close a cache file if we just want to check if it exists
https://github.com/juicedata/juicefs/issues/5407
> check if a cache file exists to avoid opening and closing it

- pkg/utils/general.go
> Fix `SleepWithJitter` doubles duration than expected

- pkg/meta/tkv.go
> meta/kv: fix stat when unlink an opend file

- cmd/destroy.go
- pkg/meta/base.go
- pkg/meta/base_test.go
- pkg/meta/interface.go
- pkg/meta/quota.go
- pkg/meta/redis.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
close #5455 
fix [test](https://github.com/juicedata/juicefs/actions/runs/12541171203/job/34969355871)
> meta/session: exit background tasks when close

- .github/scripts/command/graceful_upgrade.sh
Ref: https://github.com/juicedata/juicefs/issues/5448
> CI: fix graceful upgrade test

- .github/scripts/start_meta_engine.sh
- .github/workflows/rmfiles.yml
Ref: https://github.com/juicedata/juicefs/issues/5508
> CI: increase max connections for postgres.

- sdk/python/juicefs/juicefs/juicefs.py
> pysdk: fix stat

- cmd/object.go
- pkg/sync/sync.go
- pkg/utils/errors.go
> cmd/sync: skip special files in juicefs

- go.mod
- go.sum
- pkg/sync/sync.go
This could reduce Get ops to src from 2 to 1 if a verification is needed for sync.
> sync: calculate chksum in flight while copying data

- cmd/rmr.go
- pkg/fs/fs.go
- pkg/meta/base.go
- pkg/meta/base_test.go
- pkg/meta/benchmarks_test.go
- pkg/meta/interface.go
- pkg/meta/utils.go
- pkg/vfs/internal.go
The default rmr concurrency is hard coded as 50, make it a command line option
> cmd/rmr: add threads option

- cmd/warmup.go
> cmd/warmup: change display

- pkg/chunk/disk_cache.go
- pkg/chunk/mem_cache.go
> cache: remove unnecessary stagePath interface of CacheManager

- go.mod
- go.sum
> cmd/meta: update sqlite3 dependency from v1.14.16 to v1.14.24

- pkg/meta/base.go
- pkg/meta/openfile.go
- pkg/meta/redis.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
Update attr cache when Lookup to save GetAttr call
> perf update attrcache in lookup

- pkg/fs/fs.go
- pkg/vfs/vfs.go
Memory buffer usage metrics are missing in gateway
> gateway: fix missing buffer usage metrics

- pkg/vfs/reader.go
Currently, there is no limitation when accepting read requests. Users may issue a large number of concurrent read requests to JuiceFS, causing it to OOM. JuiceFS should protect itself from such usage and provide a predictable memory usage.
> Limit buffer usage for read requests to avoid oom

- .github/scripts/hypo/fs_sdk_test.py
- .github/workflows/load.yml
- sdk/java/libjfs/main.go
- sdk/python/juicefs/juicefs/juicefs.py
https://github.com/juicedata/juicefs/actions/runs/12645755982/job/35235374890?pr=5516
> sdk/python: fix gid behavior on creating new file(hadoop compatible )

- pkg/chunk/cached_store.go
We dont scan staging dir periodically, so those obsolete files remain untracked.
> Remove obsolete stage files when timeout happens

- pkg/object/sftp.go
> object/sftp: supports verification of known hosts

- pkg/vfs/accesslog.go
> fix accesslog quote char

- pkg/utils/cond.go
> // For a Timer created with NewTimer, Reset should be invoked only on
// stopped or expired timers with drained channels.
> cond: stop the timer before calling Reset

- pkg/utils/logger.go
This panic occurs almost weekly. I don't know why, so only to defend against it.
> Fix panic in log format

- pkg/meta/base.go
- pkg/meta/quota.go
- pkg/meta/redis.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
> meta/sql: fix flush quotas deadlock

- pkg/vfs/fill.go
> cmd/warmup: accelerate big file warmup

- pkg/meta/sql.go
> meta/sql: fix flush stat deadlock

- pkg/meta/redis.go
> meta/redis: fix dir lock

- pkg/sync/sync.go
> sync: delay deleting directories to avoid deleting empty directories

- sdk/java/src/main/java/io/juicefs/utils/BgTaskUtil.java
- sdk/java/src/test/java/io/juicefs/utils/BgTaskUtilTest.java
close https://github.com/juicedata/juicefs/issues/5731
> Hadoop: fix BgTaskUtilTest

- pkg/meta/redis.go
> meta/redis: batch get attr in readdir

- pkg/sync/cluster.go
> sync: the synchronous cluster mode does not support SSH password authentication

- pkg/sync/cluster.go
> cmd/sync: the synchronous cluster mode does not support SSH password authentication

- cmd/mount.go
- cmd/mount_unix.go
- pkg/fuse/fuse.go
- pkg/fuse/fuse_darwin.go
- pkg/fuse/fuse_linux.go
- pkg/utils/humanize.go
- pkg/vfs/vfs.go
> mount: add --umask to overwrite the one from app

- pkg/meta/random_test.go
> test: fix random test

- pkg/meta/redis.go
> cmd/meta: check mget error to avoid panic

- pkg/sync/sync.go
> cmd/sync: fix sorted and then delayed deletion

- pkg/sync/cluster.go
- pkg/sync/sync.go
> cmd/sync: send the directory to be delayed for deletion to the manage node

- pkg/meta/sql.go
- pkg/meta/sql_test.go
`juicefs format 'mysql://root:12345@(127.0.01:3306)/sql2?table_prefix=sql2' sql2`
close #4842
> meta/sql: support multiple file systems sharing a single db

- pkg/meta/base.go
rel https://github.com/juicedata/juicefs/issues/5784
> cmd/fsck: add a progress bar while using --path

- pkg/sync/download_test.go
> test: fix TestDownload test

- go.mod
- go.sum
ref [minio](https://github.com/juicedata/minio/pull/78#pullrequestreview-2705003770)
close #4433
> gateway: disable unused subsystems

- pkg/meta/utils.go
> cmd/rmr: fix skipTrash on file

- pkg/sync/sync.go
pick https://github.com/juicedata/juicefs/commit/2462ed5934f5a9dce8c546d313e1c6be2b4a7e5f
> cmd/sync: impprove performance of progress bar

- .github/workflows/compile.yml
- .github/workflows/fsrand.yml
- .github/workflows/gateway.yml
- .github/workflows/integrationtests.yml
- .github/workflows/ltpfs.yml
- .github/workflows/ltpsyscalls.yml
- .github/workflows/mutate-test-sdk.yml
- .github/workflows/pjdfstest.yml
- .github/workflows/pysdk.yml
- .github/workflows/rmfiles.yml
- .github/workflows/sdktest.yml
- .github/workflows/vdbench.yml
- .github/workflows/xattr.yml
> CI: fix action runner no space error

- .github/workflows/wintest.yml
- cmd/debug.go
- cmd/debug_unix.go
- cmd/debug_windows.go
- pkg/winfsp/winfs.go
* use wmic to replace the ps command
* Fixed the permission issue for the .config file
> windows: fixed debug command

- .github/workflows/wintest.yml
Run result:
https://github.com/juicedata/juicefs/actions/runs/14078906312/job/39427178693
> Windows: add sub command tests

- pkg/winfsp/winfs.go
The previous [PR](https://github.com/juicedata/juicefs/pull/5862/files) allowed getattr operations for certain special files, and the corresponding open methods for these files also need to be handled accordingly.
> windows: fix perm issue when accessing sp files

- .github/scripts/pysdk/pysdk_test.py
- pkg/fs/fs.go
- pkg/fs/fs_test.go
- pkg/vfs/fill.go
- pkg/vfs/fill_test.go
- pkg/vfs/internal.go
- pkg/vfs/vfs.go
- sdk/java/libjfs/main.go
- sdk/python/juicefs/juicefs/juicefs.py
_info_ is already implemented as summary
> sdk/python: support warmup/summary/clone/info

- pkg/chunk/disk_cache.go
`getDiskUsage` should not be called with cache lock held - this may cause high latency for other cache related operations.
In our scenario, we observed `cacheStore.load` experiences very high latency sometimes, even when the cache is still in memory. Additionally, metrics occasionally fail to scrape because `cacheStore.stats` also requires this lock.
> Fix release cache lock when calling `getDiskUsage`

- .github/scripts/start_meta_engine.sh
Reverts juicedata/juicefs#5901
> Revert "CI: limit max open connections for mysql/mariadb."

- cmd/status.go
- cmd/status_test.go
- pkg/fs/fs.go
- sdk/java/libjfs/main.go
- sdk/python/juicefs/juicefs/juicefs.py
This reverts commit 2a5a969c94161f5404deef49337145d139017822.
> Revert "pysdk: add command status (#5856)"

- pkg/vfs/fill.go
> cmd/warmup: fix concurrent issue

- .github/scripts/start_meta_engine.sh
- .github/scripts/utils.py
- .github/workflows/dump_load.yml
fix Too many connections  errors: https://github.com/juicedata/juicefs/actions/runs/14179290328/job/39721469421
2025/03/31 19:18:00.511101 juicefs[27538] <FATAL>: Meta ***(127.0.0.1)/test is not available: ping database: Error 1040: Too many connections [NewClient@interface.go:590]
> CI: set default max open conn with mysql/mariadb.

- pkg/meta/sql.go
close #5928
fix error overwrite and index in retry
> meta/sql: fix dumpDir concurrent issue

- pkg/fs/fs.go
- pkg/fs/fs_test.go
- sdk/java/libjfs/main.go
- sdk/java/src/main/java/io/juicefs/JuiceFileSystemImpl.java
- sdk/java/src/test/java/io/juicefs/JuiceFileSystemTest.java
This PR is for https://github.com/juicedata/juicefs/issues/5937
> Hadoop: hdfs command does not show the Quota for JuiceFS

- pkg/meta/base.go
> meta: fix race on deleting chunk channel

- cmd/mount.go
- cmd/mount_unix.go
- cmd/mount_windows.go
fix https://github.com/juicedata/juicefs/issues/5900
> cmd/mount: use absolute path for mount path while --update-fstab

- pkg/meta/sql.go
- pkg/meta/tkv.go
> meta: fix xattr empty value

- pkg/meta/base.go
- pkg/meta/base_test.go
- pkg/meta/random_test.go
- pkg/meta/sql.go
close #5781
only sql need lock in reset
> meta: cancel compact task if session closed

- sdk/python/examples/fsspec/main.py
- sdk/python/examples/fsspec/readme.md
- sdk/python/juicefs/juicefs/spec.py
> sdk/python: fix fsspec mkdirs

- pkg/object/qiniu.go
> object/qiniu: fix the Qiniu Cloud Object Storage GetObject API

- cmd/object.go
- pkg/object/file.go
- pkg/object/nfs.go
- pkg/object/sftp.go
> object: error returned when uid or gid cannot be found

- .github/scripts/hypo/fs_sdk_test.py
fix https://github.com/juicedata/juicefs/issues/5955
this is influenced by the previous test cases
> CI: Change the file name to exclude the effects of other cases.

- pkg/chunk/prefetch_test.go
for https://github.com/juicedata/juicefs/pull/4947
> test: Add unit test.

- pkg/winfsp/winfs.go
* and limit the special files access from non-root dir
> windows: fix getpath error for sp files

- sdk/java/libjfs/main.go
- sdk/java/src/main/java/io/juicefs/JuiceFileSystemImpl.java
> Hadoop: fix ranger permmsion issue when juicefs.groups was configured

- .github/scripts/command/mount.sh
- cmd/flags.go
- cmd/mount_unix.go
- docs/en/guide/cache.md
- docs/en/reference/_common_options.mdx
- docs/zh_cn/guide/cache.md
- docs/zh_cn/reference/_common_options.mdx
- pkg/fuse/fuse.go
- pkg/vfs/vfs.go
For negative lookup, we don't know the type.
> mount: rename negative-dir-entry-cache to negative-entry-cache

- docs/en/administration/metadata/fdb_best_practices.md
- docs/en/administration/metadata/tikv_best_practices.md
fix the index only, translating is on the way
> docs: fix missing fdb docs

- cmd/load.go
> cmd/load: fix loading encrypted or compressed backup files

- cmd/sync.go
- go.mod
- go.sum
- pkg/sync/config.go
- pkg/sync/sync.go
- pkg/sync/sync_test.go
> cmd/sync: add start-time and end-time flags for file filtering

- pkg/meta/base.go
- pkg/meta/base_test.go
close #6027
only affect unittest
> meta: fix delete slice

- docs/en/guide/gateway.md
- docs/zh_cn/administration/metadata/fdb_best_practices.md
- docs/zh_cn/guide/gateway.md
1）追加gateway etag的说明和案例。
2）对应升级 Docusaurus v3 以后的 breaking change
> doc: update description about gateway etag and fix breaking change

- go.mod
- go.sum
rel https://github.com/juicedata/juicefs/issues/6089
> fuse: use latest commit of go-fuse

- pkg/object/encrypt.go
- pkg/object/encrypt_test.go
> fix: add validation for ciphertext length in Decrypt function

- pkg/meta/base.go
- pkg/meta/redis.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
> fix: calculate trash files when recalculating volume stats

- pkg/meta/base.go
> Exit StatFS routine when closing session

- docs/en/deployment/hadoop_java_sdk.md
- pkg/fs/fs.go
- pkg/vfs/vfs.go
- sdk/java/libjfs/main.go
- sdk/java/src/main/java/io/juicefs/JuiceFileSystemImpl.java
- sdk/java/src/test/java/io/juicefs/JuiceFileSystemTest.java
PR for https://github.com/juicedata/juicefs/issues/6096
> Support subdir option in hadoop sdk

- .github/scripts/pysdk/pysdk_test.py
- sdk/python/juicefs/juicefs/juicefs.py
> sdk/python: support encoded read/write

- .github/scripts/pysdk/pysdk_test.py
- pkg/fs/fs.go
- sdk/java/libjfs/main.go
- sdk/java/src/test/java/io/juicefs/JuiceFileSystemTest.java
- sdk/python/juicefs/juicefs/juicefs.py
close #6088 
close #6008
close #6003 by support Client.shutdown()
> sdk/python: fix reused client

- .github/workflows/pysdk.yml
- cmd/gateway.go
- cmd/mdtest.go
- cmd/object.go
- cmd/object_test.go
- pkg/fs/fs.go
- pkg/fs/fs_test.go
- pkg/gateway/gateway_test.go
- pkg/vfs/internal.go
- pkg/vfs/vfs.go
- pkg/vfs/vfs_test.go
- pkg/winfsp/winfs.go
- sdk/java/libjfs/main.go
- sdk/python/juicefs/juicefs/juicefs.py
> sdk/python: read .config and .stats

- .github/workflows/integrationtests.yml
- pkg/meta/tkv_tikv.go
> meta/tikv: fix unable to read after write issue

- cmd/mount_unix.go
An IO_FLUSHER will use direct reclaim to discard clean pages or slab pages that do not require the starting of any physical IO. It fixes potential IO hang/deadlock issues.
For more info about IO_FLUSHER, see
https://lore.kernel.org/all/20191112001900.9206-1-mchristi@redhat.com/
> cmd/mount: set the process as an IO_FLUSHER

- pkg/gateway/gateway.go
aws s3api list-object-versions  --endpoint http://127.0.0.1:9008 --bucket testbucket1
> gateway: implement ListObjectVersions to return object and prefix information

- docs/en/deployment/juicefs_on_docker.md
- docs/zh_cn/deployment/juicefs_on_docker.md
Create another method to use juicefs in docker
> docs: add docker-compose healthcheck example

- pkg/sync/sync.go
Reverts juicedata/juicefs#6233
> Revert "cmd/sync: clear the redundant delimiters in the files-from"

- pkg/vfs/internal.go
> log: adjust parent inode position in clone log

- pkg/object/webdav.go
> webdav: simplify ReadStreamRange implementation by using existing method

- cmd/mount_unix.go
When the kernel has a negative dentry cached for a directory, concurrent `mkdir -p` calls from multiple nodes can still result in a `File exists` error.
Reproduce:
1. On node 1, `stat` or `ls` a non-existent directory to populate the negative dentry cache for a path.
2. On node 2, create the directory at that same path.
3. On node 1, running `mkdir -p` for the same directory will now fail with a `File exists` error.
This is a simple reproduction flow. For a user calling Python's `os.makedirs(exist_ok=True)`, this bug can make it seem as if the `exist_ok=True` parameter is not working on JuiceFS.
This bug is fixed on kernel version 6.6 ([fuse: invalidate dentry on EEXIST creates or ENOENT deletes · torvalds/linux@7d875e6](https://github.com/torvalds/linux/commit/7d875e66859a4359acd29ce0d188 …
> cmd/mount: add a warning message when `negative-entry-cache` is enabled on kernel versions below 5.11

- cmd/mount.go
- cmd/mount_unix.go
close https://github.com/juicedata/juicefs/issues/6306
> mount: add hide-internal option

- docs/en/getting-started/installation.md
- docs/zh_cn/getting-started/installation.md
This PR primarily makes the one-click copy function more user-friendly, mainly involving the following changes: 
- Move the comments outside the code block
- Adjust the code in code blocks 
- Improve descriptive information for those parts that are easily confused
> Docs: Improve the installation documentation user experience 

- pkg/object/minio.go
old : `minio://http://127.0.0.1:9000/testbucket1/testbucket1/`
new:` minio://127.0.0.1:9000/testbucket1/`
> object/minio: fix print object storage info
