juicedata/juicefs

- pkg/meta/context.go
- pkg/redis/redis.go
1. Use `strconv.FormatUint` instead of `Sprintf` to avoid escapes to heap
2. Call `Bytes` directly instead of getting a string `Result` and copying to a `[]byte`.
> Avoid escapes to heap in frequently used functions

- cmd/format.go
- cmd/format_test.go
- go.mod
- pkg/chunk/cached_store.go
- pkg/chunk/cached_store_test.go
- pkg/chunk/store_test.go
- pkg/object/interface.go
- pkg/object/prefix.go
- pkg/object/redis.go
This PR clarify the API of object storage used by JuiceFS here, rather than use the wider interface used by Juicesync.
So we can add implementation here much easier.
Close #21
> define the interface required for JuiceFS here.

- cmd/format.go
- cmd/mount.go
- pkg/chunk/disk_cache.go
- pkg/chunk/page.go
- pkg/fuse/fuse.go
- pkg/redis/redis.go
- pkg/redis/redis_test.go
- pkg/vfs/reader.go
- pkg/vfs/vfs.go
- pkg/vfs/writer.go
Some unused variables and functions are found by the linter, so they are deleted in this PR.
> Fix some errors reported by golangci-lint

- pkg/redis/redis.go
Make sure the unused trunk will not be leak in case of failed deletion.
Closes #19
> track unused chunk

- pkg/redis/redis.go
- pkg/redis/redis_test.go
The Redis transaction is based on optimistic lock, it could fail under high contention.
This PR added a local pessimistic lock on first key to reduce contention.
Close #33
> Add Pessimistic lock to reduce conflict on Redis transaction

- Makefile
This PR add an environment variable `STATIC` for `Makefile`.
When specified, the build for C code will use `musl-gcc`, and the output is static linked. This is good for container environment such as CSI driver container with no glibc required( may use musl-libc such as Alpine Linux).
> support static build for musl-gcc

- cmd/mount.go
logging INFO and above into syslog by default, also the DEBUG in daemon mode.
The tracing logs are two many for syslog, even in daemon mode.
Closes #65
> logging INFO into syslog

- .github/workflows/release.yml
- .goreleaser.yml
This PR is to fix arm64 cross build, use a personal access token for brew push as goreleaser will push to another [repository](https://github.com/juicedata/homebrew-tap).
> fix arm64 build

- cmd/format.go
- cmd/main.go
- cmd/mount.go
This issue fixes three problems:
1. Even for output to Syslog, I think we need to record levels like trace, debug, etc., which is usually used for problem debug
2. Remove duplicate log level code in format and mount.
3. By `--quiet` definition, it should be able to log warnings so its log level should be `warning`, not `error`
> Optimized logging level by default only logging to syslog in daemon mode

- Makefile
- go.mod
- go.sum
- pkg/object/ceph.go
JuiceFS can already use S3 API to work with Ceph RGW, that introduce some performance  overhead and maitain burden from RGW.
This PR added support to talk to Ceph Core using librados. 
Since this will add lots of dependency to JuiceFS, so it's not included by default, you can build it:
```bash
$   make juicefs.ceph
```
> Use librados to access Ceph

- README.md
- README_CN.md
GitHub caches badge (on a server called camo.githubusercontent.com ) quite aggressively. This is a workaround from [here](https://github.com/sbts/github-badge-cache-buster) to mitigate this problem.
> Fix wrong Go Report badge caused by GitHub cache

- Makefile
- README.md
- README_CN.md
- cmd/format.go
- cmd/main.go
- cmd/mount.go
- cmd/version.go
- pkg/meta/redis.go
This PR change all command line options to use lower case for consistency.
This is a BREAKING change, we'd like to change it now rather than later.
> change to use lower case for command line options

- pkg/meta/redis.go
- pkg/meta/redis_test.go
Currently, we try to delete chunks as early as possible, for example, delete the chunks if not used after truncate. But there is a race that it could delete new data written after truncate().
So this PR change to delete chunks only once the inode is deleted. It still delete some of slices after compact.
> delete all chunks together

- pkg/meta/redis.go
- pkg/meta/utils_darwin.go
- pkg/meta/utils_linux.go
- pkg/vfs/vfs.go
In darwin, getxattr should return ENOATTR if extended attribute do not exists.
Closes #88
> use ENOATTR in darwin instead of ENODATA

- pkg/meta/redis.go
- pkg/meta/redis_test.go
- pkg/meta/slice.go
```
BenchmarkReadSlices/small-16             3035296               400 ns/op             352 B/op          9 allocs/op
BenchmarkReadSlices/small-16             3063632               382 ns/op             352 B/op          9 allocs/op
BenchmarkReadSlices/small-16             3184216               383 ns/op             352 B/op          9 allocs/op
BenchmarkReadSlices/mid-16                227870              5467 ns/op            5632 B/op        129 allocs/op
BenchmarkReadSlices/mid-16                221240              5342 ns/op            5632 B/op        129 allocs/op
BenchmarkReadSlices/mid-16                220996              5185 ns/op            5632 B/op        129 allocs/op
BenchmarkReadSlices/large-16               14389             84043 ns/op           90112 B/op       2049 …
```
> Make slices parsing faster by pre-allocation

- pkg/meta/redis.go
- pkg/meta/redis_test.go
This PR two bugs that cause chunk leaking:
1) When SCAN is used to find all the chunks of a file, it could return an empty list with cursor, but we did not check the cursor, which cause some of chunks are not deleted.
2) After successful compaction, the unused chunks are not deleted.
Also, SCAN will be too slow to delete chunks, we changed to enumerate all the chunk keys and delete them on by one.
Closes #113
> Fix chunk leaking

- cmd/benchmark.go
- cmd/main.go
- go.mod
This PR is for issue #101 , which add a simple helper `benchmark` subcommand.
When _JuiceFS_ filesystem has been mounted, we can simply run `./juicefs benchmark [<MOUNT-POINT>]` to test the performance read/write/stat big/small file. The destination directory to test can be specified by `--dest` flag or the first positional argument.
```
$ ./juicefs help benchmark
NAME:
juicefs benchmark - run benchmark, including read/write/stat big/small files
USAGE:
juicefs benchmark [command options] [arguments...]
OPTIONS:
--dest value                 path to run benchmark (default: "/jfs/benchmark")
--block-size value           block size in MiB (default: 1)
--bigfile-file-size value    size of big file in MiB (default: 1024)
--smallfile-file-size value  size of small file in MiB (default: 0.1) …
```
> Add benchmark helper subcommand

- README.md
- README_CN.md
- cmd/main.go
- cmd/mount.go
- docs/command_reference.md
- Remove "Command Reference" from TOC
- Add "Command Reference" section to Chinese version README
- Fix spelling in "Command Reference"
- For a more visibility, use [backslash](https://github.github.com/gfm/#hard-line-breaks) to break line explicitly instead of multiple spaces (many editor also trim ending space automatically).
- Remove "Hadoop SDK" from roadmap
Ref to #96
> Update command reference doc

- Makefile
Old git version not support `%as` format
> fix revision in Makefile

- pkg/meta/redis.go
This PR is related to #95 .
In the original implementation, `mget` is called once with all the keys which correspond to files in a directory. When there are many files in a directory, this call might block the Redis server process.
In this PR, I changed it to call `mget` in smaller fixed batch. The consequence is that we reduce the chance of blocking the Redis server, but `ReadDir` is made slower when the number of files in a directory exceeds the batch size (which is set to 4096 now).
For small directories, the latency difference is trivial:
* Before
```python
In [24]: %timeit os.listdir("/Users/satoru//jfs/some-files/")
1.26 ms ± 2.57 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```
* After
```python
In [25]: %timeit os.listdir("/Users/satoru/jfs/some-files/")
1.27 ms ± …
```
> Avoid calling mget with massive number of keys in Readdir

- README.md
- README_CN.md
- docs/how_to_setup_object_storage.md
Ref to #96. More object storage will be added later in separated PR.
> Add doc: How to Setup Object Storage

- Makefile
- sdk/java/libjfs/Makefile
When use `git clone` with `--depth` or `--no-tags` option, we may not get the latest version tag, but the latest commit revision is there, we can pass the `revision` and `revisionDate`.
> fix Makefile to pass revision when git- clone with --depth or --no-tags

- docs/en/redis_best_practices.md
- pkg/meta/redis.go
Once Redis servers and Sentinels are deployed, the `REDIS-URL` can be specified as `[redis[s]://][USER:PASSWORD@]MASTERNAME,SENTINEL_ADDRS:SENTINEL_PORT[/DB]`, for example,
```
$ ./juicefs mount rediss://:sentinelPass@masterName,1.2.3.4,1.2.5.6:5000/2
```
**Note** The default port for Sentinel is 26379, but the above URL use 6379 (default port for Redis server) as the default, so the port for Sentinel is not optional.
**Note** When the password is provided in the URL, it will also be used to connect Redis server. If they have different passwords, the passwords should be specified by enviroment viarables (`SENTINEL_PASSWORD` and `REDIS_PASSWORD`) separately.
Closes #169
> Connect to Redis with Setinel

- README.md
- README_CN.md
- docs/en/how_to_use_on_kubernetes.md
> Update K8s doc link in README_CN.md

- pkg/meta/redis.go
Redis client will not retry the request after read timeout, so we increase
read timeout from 3 seconds to 30 seconds. The default of write timeout is
read timeout, so we also change that to 5 seconds (will be retried).
Closes #182
> increase redis read timeout 3s -> 30s

- cmd/mount.go
- pkg/meta/redis_metrics.go
- pkg/object/metrics.go
- pkg/vfs/accesslog.go
- pkg/vfs/handle.go
- pkg/vfs/vfs.go
Prefix all prometheus metric names with `juicefs_` in order to set a namespace. Otherwise it's hard to know what a metric is referring to on a Prometheus instance with lots of metrics.
From https://prometheus.io/docs/practices/naming/:
> A metric name should have a (single-word) application prefix relevant to the domain the metric belongs to. The prefix is sometimes referred to as namespace by client libraries. For metrics specific to an application, the prefix is usually the application name itself.
> prometheus metrics: add namespace prefix

- docs/en/how_to_setup_object_storage.md
- pkg/object/s3.go
When uri.Path is not empty, parse uri as path-style, otherwise parse uri as virtual hosted-style.
Passed [TestS3](https://github.com/juicedata/juicefs/blob/5a92bdfa6091042cc1fa21076b5069be1ce14af5/pkg/object/object_storage_test.go#L216) with following values:
```
juicefs-image.s3.ap-northeast-1.amazonaws.com
s3.ap-northeast-1.amazonaws.com/juicefs-image
play.minio.io:9000/juicefs
localhost:443/test
```
Closes #134
> support path-style URL for S3 (#134)

- go.mod
- go.sum
scs-go-sdk have a memory leak bug v1.0.0 version,  fix in v1.1.0 version. This pr upgrade scs sdk to v1.1.0. By the way, fix sync subcommand debug flag.
> Upgrade scs sdk

- cmd/mount.go
- pkg/meta/redis_metrics.go
- pkg/object/metrics.go
- pkg/vfs/accesslog.go
- pkg/vfs/vfs.go
Add `vol_name` and `mp` labels for metrics.
As using [`prometheus`](https://github.com/prometheus/client_golang/blob/master/prometheus) package's wrap fuction [`WrapRegistererWith`](https://github.com/prometheus/client_golang/blob/babeb356a51b1277535260e0122ad8c46240ab96/prometheus/wrap.go#L46) to add labels to registry, all `prometheus.MustRegister()` call should be run after the wrap call.
> add vol_name and mp labels for metrics

- cmd/mount.go
- cmd/umount.go
#228  Early `umount` cannot unmount _fuse_ filesystem on Linux, and we need use `fusermount` which is in the fuse package. When unmount JuiceFS, try `fusermount` first, fallback to `umount` if fuse package doesn't installed.
> use fusermount to unmount on linux

- pkg/object/scs.go
咨询了scs技术，一次list object操作返回的key列表顺序可能有问题，Arvintian在测试中也发现一个case导致无法sync。sync 使用marker翻页，接口保证下一页key一定大于marker，所以这里加一个sort，可以fix页内错误，没有错误情况下又不影响。
避免这个错误 [keys out of order error](https://github.com/juicedata/juicefs/blob/main/pkg/sync/sync.go#L129)。
> fix object scs list

- go.mod
- pkg/object/obs.go
We've already define a http client for some object storage, the http client use [proxy setting from environment variables](https://github.com/juicedata/juicefs/blob/main/pkg/object/restful.go#L44), we use this http client to create object storage client if possible (such `s3`, `ks3`, `b2` etc.). 
This PR add support for `obs`.
> obs: support proxy setting from environment variables

- pkg/object/sftp.go
Support IPv6 address for sftp server.
When we _sync_ files to IPv6 sftp server:
`./juicefs sync ./localdir/ user:pass@[IPv6 address]:/remotedir/`
> support IPv6 address for sftp

- cmd/main.go
- cmd/main_test.go
Before this PR, `cli` can only parse named argument BEFORE positional ones, it's difficult to add new named argument.
This PR try to recognize the named arguments and move then to the expected position before they are parsed by `cli`.
For example, we can have this now:
```
./juicefs mount localhost /jfs --cache-dir xxx -v -o debug
```
Closes #219
> re-order the arguments to have named ones after positional

- pkg/meta/redis.go
- pkg/meta/redis_test.go
- pkg/meta/slice.go
For appended log files, there will be many small slices, and we always compact them into bigger one using FIFO, Then the first few slices will be compacted over and over again, even they are bigger than a block (4MB), this increase the get/put traffic.
This PR will skip the first few big slices to reduce traffic to object store during compaction.
Closes #261
> skip first few large slices in compaction

- cmd/info.go
- cmd/main.go
- docs/en/command_reference.md
- pkg/meta/interface.go
- pkg/meta/redis.go
- pkg/vfs/internal.go
This PR is based on #284 
for example,
```bash
$ ./juicefs info /jfs /jfs/Makefile 
/jfs :
inode: 1
files: 2827
dirs:  423
length:        326090181
size:  336531456
/jfs/Makefile :
inode: 25
files: 1
dirs:  0
length:        101
size:  4096
chunks:
0:      7       101     0       101
```
Closes #205
> Show internal information for dir/files

- pkg/fs/fs.go
`resolved` is only set to `true` when `i == len(ss)-1`, but when this
condition holds the loop will terminate without `break`.
> Remove redundant break

- pkg/object/metrics.go
After running with 35 buckets for some time, 25 seem to be the sweet number (despite the theoretical 60s timeout?)
> metrics(object): add more histogram buckets for latency distribution

- Makefile
- cmd/gateway.go
- pkg/object/azure.go
- pkg/object/bos.go
- pkg/object/cos.go
- pkg/object/eos.go
- pkg/object/gs.go
- pkg/object/hdfs.go
- pkg/object/hdfs_kerberos.go
- pkg/object/ibmcos.go
- pkg/object/jss.go
- pkg/object/ks3.go
- pkg/object/minio.go
- pkg/object/nos.go
- pkg/object/object_storage.go
- pkg/object/obs.go
- pkg/object/oos.go
- pkg/object/oss.go
- pkg/object/qingstor.go
- pkg/object/qiniu.go
- pkg/object/s3.go
- pkg/object/scs.go
- pkg/object/scw.go
- pkg/object/sftp.go
- pkg/object/space.go
- pkg/object/swift.go
- pkg/object/upyun.go
- pkg/object/wasabi.go
Added build tags to exclude some of the features, to reduce the size of binary.
Added a rule to build a minimal binary only support file and S3 as object store, reduce the size to 1/3.
```
$ make juicefs.lite
$ ls -l juicefs*
-rwxr-xr-x  1 davies  staff  74564020 Apr 19 15:11 juicefs
-rwxr-xr-x  1 davies  staff  27690572 Apr 19 15:37 juicefs.lite
```
Close #318
> build a minimal binary with S3 only

- cmd/mount.go
- docs/zh_cn/hadoop_java_sdk.md
- pkg/fs/fs.go
- pkg/fs/metrics.go
- pkg/metric/metrics.go
- pkg/usage/usage.go
- sdk/java/libjfs/main.go
- sdk/java/src/main/java/io/juicefs/JuiceFileSystemImpl.java
This PR added the configuration to enable pushing metrics to Promethous Push Gateway [1]
```
juicefs.push-gateway = host:port
juicefs.push-interval = 10
juicefs.push-auth = name:password
```
Since the Push Gateway will not forget any pushed serials, they should be wiped periodically (for example, every hour), otherwise there will be too many serials in Promethous.
[1] https://github.com/prometheus/pushgateway
Closes #312
> push metrics to prometheous gateway from Java SDK

- pkg/meta/redis.go
- pkg/vfs/vfs_unix.go
For setattr, if there is nothing actually changed, we don't to update the attribute in Redis to save a RPC call.
For a directory with 44K files, this PR could decrease the time of `chown -R` from 18 seconds to 14 seconds.
> Speed up SetAttr

- README.md
- README_CN.md
- cmd/benchmark.go
- docs/en/command_reference.md
- pkg/vfs/internal.go
This Added the following metrics at the end of benchmark:
```
FUSE operation: 19333, avg: 0.3 ms
Update meta: 436, avg: 1.4 ms
Put object: 356, avg: 4.8 ms
Get object first byte: 308, avg: 0.2 ms
Delete object: 356, avg: 0.2 ms
Used: 23.4s, CPU: 69.1%, MEM: 147.0 MiB
```
close #315
> show internal metrics at end of benchmark

- cmd/format.go
- docs/en/command_reference.md
- go.sum
- pkg/meta/config.go
- pkg/object/object_storage_test.go
- pkg/object/sharding.go
- sdk/java/libjfs/main.go
To enable this, a volume should be formatted with `--shards  N` and `--bucket TEMPLATE`, N means the number of buckets and TEMPLATE is used to generated different bucket names, for example, `test%d`.
Then all the blocks will be stored into different buckets based on the hash of object keys.
> store blocks into multiple bucket

- pkg/chunk/disk_cache.go
- pkg/chunk/disk_cache_test.go
- Add cache directory path to every log of `cacheStore` to help distinguish different directory when use multiple cache directories
- Add log before execute `cacheStore.cleanup()` to know more context
- Upgrade some logs level (INFO → WARNING)
> Add more logs and upgrade log level in `disk_cache.go`

- cmd/profile.go
add percentage field(total time / interval, may exceed 100 in high concurrency) for juicefs profiling
> add percentage field to `juicefs profile`

- cmd/profile.go
Fix panic when parse invalid log line, e.g. `2021.05.^C` (the last line of access log).
```
panic: runtime error: index out of range [1] with length 1
goroutine 71 [running]:
main.parseLine(0xc001625a40, 0xa, 0xa)
/go/src/github.com/juicedata/juicefs/cmd/profile.go:74 +0x659
main.(*profiler).reader(0xc000a8fef0)
/go/src/github.com/juicedata/juicefs/cmd/profile.go:99 +0xb6
created by main.profile
/go/src/github.com/juicedata/juicefs/cmd/profile.go:290 +0x605
```
> Fix `juicefs profile` panic when parse invalid log line

- cmd/benchmark.go
- cmd/format.go
- cmd/fsck.go
- cmd/gateway.go
- cmd/gc.go
- cmd/mount.go
- cmd/status.go
- docs/en/k8s_grafana_template.json
- go.mod
- go.sum
- pkg/fs/fs.go
- pkg/fs/fs_test.go
- pkg/meta/config.go
- pkg/meta/interface.go
- pkg/meta/redis.go
- pkg/meta/redis_metrics.go
- pkg/meta/redis_test.go
- pkg/meta/slice.go
- pkg/meta/sql.go
- pkg/meta/sql_test.go
- pkg/vfs/internal.go
- pkg/vfs/reader.go
- pkg/vfs/vfs.go
- pkg/vfs/writer.go
- sdk/java/libjfs/main.go
SQL is a popular interface to talk to database, this PR enable JuiceFS to use SQL databases as meta store. Currently, SQLite and MySQL are supported, other database will be added later.
To use MySQL as meta store:
```
./juicefs format mysql://user:pass@host:port/db  name
```
Or SQLite 
```
./juicefs format sqlite3:///path/to/db  name
```
Except file locks, other POSIX features are supported.
Closes #183  #359
> Use SQL database as meta store

- pkg/meta/redis.go
The transaction may not be idempotent, so we can't retry the transaction on network failure, but we can on some known error caused by failover process.
Close #397
> Restart transaction on failover

- pkg/meta/sql.go
When setting `heartbeat`, I see it's formatted using **UTC**. Whereas when comparing it, a **local** timezone is used. Which in my case (CST), causes all sessions being deleted.
> Heartbeat should have consistent date format

- pkg/meta/sql.go
xorm will update only the columns that have non-zero value, but somethings the expect value is zero, so we need to specify the columns for better performance (rather than update all columns).
> specify updated columns

- pkg/meta/benchmarks_test.go
- pkg/meta/slice.go
- pkg/meta/sql.go
Before:
```
BenchmarkReadSliceBuf
BenchmarkReadSliceBuf/small
BenchmarkReadSliceBuf/small-16         	 3337833	       380.6 ns/op
BenchmarkReadSliceBuf/mid
BenchmarkReadSliceBuf/mid-16           	  297603	      4010 ns/op
BenchmarkReadSliceBuf/large
BenchmarkReadSliceBuf/large-16         	   20037	     60182 ns/op
```
After:
```
BenchmarkReadSliceBuf
BenchmarkReadSliceBuf/small
BenchmarkReadSliceBuf/small-16         	 5951392	       201.1 ns/op
BenchmarkReadSliceBuf/mid
BenchmarkReadSliceBuf/mid-16           	  590236	      2038 ns/op
BenchmarkReadSliceBuf/large
BenchmarkReadSliceBuf/large-16         	   40591	     29739 ns/op
```
> Optimize readSliceBuf

- pkg/sync/cluster.go
Currently the concat  launch worker command is: `/tmp/juicefs sync -manager {{managerAddress}} sync ... `, which has a unnecessary `sync` arg.
This PR fix this problem.
> fix juicefs sync launch worker args

- pkg/fs/fs.go
- pkg/meta/lua_scripts.go
- pkg/meta/redis.go
- pkg/meta/redis_test.go
- pkg/vfs/vfs.go
- sdk/java/libjfs/main.go
- sdk/java/src/main/java/io/juicefs/JuiceFileSystemImpl.java
The division return a float rather than a integer, so we need to use math.floor() to convert the result into a integer.
Added a configuration to disable resolve using Lua script.
> fix permession check in lua script

- pkg/meta/sql.go
- pkg/meta/sql_unix.go
Under repeatable read isolation level, the transaction will commit successfully even some queried rows is changed by other transactions, which is different from the optimistic transaction in Redis.
This PR will add a lock for all queried rows during a transaction to fix the conflict.
> lock read rows during transactions

- Makefile
We should hold a branch for each stable version, and use version from code.
> donot try to override version from tag

- pkg/meta/sql.go
Rmdir a directory with 10k entries:
using Count:
100	    477945 ns/op
using Exist:
100	    130837 ns/op
> meta/sql: use Exist instead of checking Count > 0

- pkg/meta/redis.go
- pkg/meta/redis_test.go
- pkg/meta/sql.go
- pkg/meta/sql_test.go
When default permission is enabled on FUSE, the kernel will check for sticky bit, and JuiceFS don't need to do anything rather than storing the sticky bit.
For Java SDK and S3 gateway, JuiceFS need to check permission, so we added the permission check for all meta engines, so they will be active for Java SDK and S3 gateway.
Closes #472
> Support sticky bit in Java SDK

- Makefile
- cmd/fsck.go
- cmd/gc.go
- pkg/meta/interface.go
- pkg/meta/redis.go
- pkg/meta/redis_test.go
- pkg/meta/sql.go
For earlier version, there are leaked inodes in Redis, the PR will cleanup them in `juicefs gc --delete`
> Cleanup leaked inodes in Redis from earlier version

- sdk/java/libjfs/main.go
Config in core-site.xml is :
```
<property>
<name>juicefs.juicefstest.cache-dir</name>
<value>/ssd/juicefs-cache:/juicefs-cache1</value>
</property>
```
When creating cache dirs, it only adds the key after the last dir:
```
ls cache dirs:
ssd/juicefs-cache/juicefstest/raw/
ssd/juicefs-cache1/juicefstest/eb22c013-ea4e-4a42-9c3f-3ade6a3d7d81/raw
```
Closes #514
> Fix the wrong organizational structure of the Cache directories when using Hadoop SDK

- autocomplete/bash_autocomplete
- autocomplete/zsh_autocomplete
- cmd/main.go
close #503 
Run `source bash_autocomplete` or `source zsh_autocomplete` based on the shell to make auto-completion work. We may need a specific doc for this.
> cmd: add auto completion for bash & zsh

- cmd/gateway.go
- cmd/mount.go
- docs/en/command_reference.md
- docs/zh_cn/command_reference.md
- pkg/fs/fs.go
- pkg/fuse/fuse.go
- pkg/meta/config.go
- pkg/meta/interface.go
- pkg/meta/openfile.go
- pkg/meta/redis.go
- pkg/meta/sql.go
- pkg/winfsp/winfs.go
- sdk/java/libjfs/main.go
- sdk/java/src/main/java/io/juicefs/JuiceFileSystemImpl.java
For not-modified files, we should keep the page cache in kernel, also cache the chunks to speed up read.
For any changes to the data, the mtime of file will be updated in microseconds, so we can check the mtime to know whether the file is changed or not. If not, we will keep the cache for chunks and pages in kernel, otherwise invalidate them.
And, we introduce a new option called `OpenCache`, which tell the client to don't check the mtime of a file before that, then JuiceFS will not know any change in the past period. So `OpenCache` should be set based on the change interval of files.
TODO: add command option for OpenCache
Closes #454
> cache attribute and chunks for open files

- pkg/meta/interface.go
- pkg/meta/openfile.go
- pkg/meta/redis.go
- pkg/meta/sql.go
- pkg/vfs/reader.go
1. Invadate the cached attribute for open files after some fields changed.
2. When the cached mtime is updated by GetAttr(), future Open() will assume the mtime is consistent with page cache, but not, so we should mark the cached attribute so that future Open() will not keep the cache.
3. When a file is compacted by other clients, the chunk was deleted, so we should invalidate the chunk cache after a temporary read failure.
> invalidate cache fo open files

- cmd/dump.go
- cmd/load.go
- cmd/main.go
- docs/en/command_reference.md
- docs/zh_cn/command_reference.md
This PR change to FILE argument of dump/load to be optional, then STDOUT/STDIN will be used, then we can use it like this:
```bash
$ ./juicefs dump 127.0.0.1/ | ./juicefs load 127.0.0.1/2
```
> cmd/dump: dump metadata into STDOUT

- cmd/dump.go
- cmd/format.go
- cmd/fsck.go
- cmd/gateway.go
- cmd/gc.go
- cmd/load.go
- cmd/mount.go
- cmd/status.go
- docs/en/command_reference.md
- docs/en/encrypt.md
- docs/en/juicefs_on_macos.md
- docs/en/mount_at_boot.md
- docs/en/quick_start_guide.md
- docs/en/redis_best_practices.md
- docs/zh_cn/command_reference.md
- docs/zh_cn/encrypt.md
- docs/zh_cn/juicefs_on_macos.md
- docs/zh_cn/quick_start_guide.md
- docs/zh_cn/redis_best_practices.md
JuiceFS support multiple database as meta engine, so we should use META-URL instead of REDIS-URL
closes #539
> docs: use META-URL to replace REDIS-URL

- go.mod
- go.sum
- pkg/fuse/fuse.go
Kernel writeback cache (require Linux kernel 3.15+) could be enabled by 
```
$ ./juicefs mount  redis-url /jfs -o writeback_cache
```
closes #577
> support kernel writeback cache

- pkg/meta/redis_test.go
- pkg/meta/sql.go
- pkg/meta/sql_unix.go
SQLite and PG does not support uint64 (always be int64), will fail the query if a value is greater than 1<<63. For lock owner, which could be greater than 1<<63. 
This PR change the column type to int64 for Owner, and cast it to int64 always.
> Fix lock owner in SQLite

- pkg/meta/tkv_tikv.go
https://github.com/tikv/client-go/blob/master/tikv/txn.go#L287-L291
> // SetEnable1PC indicates that the transaction will try to use 1 phase commit(which should be faster).
> // 1PC does not work if the keys to update in the current txn are in multiple regions.
> meta/tikv: enable 1pc when commit

- pkg/object/bwlimit.go
- pkg/object/metrics.go
```
panic: interface conversion: *object.limitedReader is not io.Seeker: missing method Seek
goroutine 242 [running]:
github.com/juicedata/juicefs/pkg/object.(*readCounter).Seek(0xc00083e0a0, 0x0, 0x0, 0x0, 0xc000856020, 0x9)
/workspace/juicefs/pkg/object/metrics.go:80 +0x47
github.com/juicedata/juicefs/pkg/object.generateChecksum.func1(0x7f871d0a1a40, 0xc00083e0a0)
/workspace/juicefs/pkg/object/checksum.go:40 +0x39
github.com/juicedata/juicefs/pkg/object.generateChecksum(0x7f871d0a1a40, 0xc00083e0a0, 0xc000856020, 0x9)
/workspace/juicefs/pkg/object/checksum.go:51 +0x410
github.com/juicedata/juicefs/pkg/object.(*s3client).Put(0xc0007fdc40, 0xc000810100, 0x17, 0x2ed8a00, 0xc00083e0a0, 0x0, 0x0)
/workspace/juicefs/pkg/object/s3.go:116 +0xe8 …
```
> fix bandwidth limit

- pkg/meta/load_dump_test.go
- pkg/meta/redis.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
- pkg/meta/tkv_mem.go
- pkg/meta/tkv_test.go
- pkg/meta/tkv_tikv.go
> meta/tkv: add dump/load functions

- pkg/meta/load_dump_test.go
- pkg/meta/redis.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
it crashed with an empty database
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x20447ec]
goroutine 1 [running]:
main.mount(0xc000786d80, 0x1b, 0x38)
/root/work/juicefs/cmd/mount.go:108 +0x58c
github.com/urfave/cli/v2.(*Command).Run(0xc000492120, 0xc000786500, 0x0, 0x0)
/root/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:163 +0x4dd
github.com/urfave/cli/v2.(*App).RunContext(0xc0003d2d00, 0x2c670a8, 0xc0001ac010, 0xc0007860c0, 0x4, 0x4, 0x0, 0x0)
/root/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:313 +0x810
github.com/urfave/cli/v2.(*App).Run(...)
/root/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
main.main()
/root/work/juicefs/cmd/main.go:99 +0x191c
```
> fix mount with empty database

- docs/en/grafana_template.json
- docs/en/hadoop_java_sdk.md
- docs/en/how_to_use_on_kubernetes.md
- docs/en/p8s_metrics.md
- docs/zh_cn/hadoop_java_sdk.md
- docs/zh_cn/how_to_use_on_kubernetes.md
- docs/zh_cn/p8s_metrics.md
1. Use query to find volume names from prometheus data automatically instead of modifying variable manually in grafana dashboard template.
2. Rename `k8s_grafana_template.json` to `grafana_template.json` as this template has nothing k8s specific.
> Grafana dashboard template auto find volume names from p8s metrics label

- pkg/meta/redis.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
- pkg/utils/alloc.go
- pkg/vfs/compact.go
- pkg/vfs/writer.go
```
fio --group_reporting --time_based --iodepth=32 --norandommap --name=4k-file-single-randwrite --directory=/jfs-ce3/tmp --rw=randwrite --bs=4k --size=10G --runtime=300 --numjobs=1 --output 4k-random-write.txt
```
> Improve stability for heavy random write workload

- pkg/chunk/mem_cache.go
Currently, the mem cache use the same memory allocated for buffers, then it will run out of buffer memory and block the write.
This PR change to allocate new memory for cache.
> alloc memory separately for mem cache

- fstests/Makefile
- pkg/meta/redis.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
Currently, we zero out the chunk when truncate up, but do not zero them when truncate down. Then a write with hole could also truncate the file up, but we did not zero them chunks, then some old data will be available in the hole.
This PR fix it by zero the chunks always in truncate.
> Fix  write  with hole after truncate

- fstests/Makefile
- pkg/fs/fs.go
- pkg/meta/openfile.go
- pkg/meta/redis.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
- pkg/vfs/handle.go
- pkg/vfs/reader.go
- pkg/vfs/vfs.go
- pkg/vfs/writer.go
There is a race accessing cached chunks, so we should add a rwlock to fix that.
> Add rwlock to open file

- cmd/dump.go
- cmd/fsck.go
- cmd/gc.go
- cmd/load.go
- pkg/meta/redis.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
- pkg/utils/utils.go
#603 #670 
**dump**
**load**
Add a dynamic progress bar for dump and load
> feat: progress bar for dump and load

- pkg/chunk/disk_cache.go
When writeback is enabled, we want to speedup the write of small files by sacrifice the durability, but the fsync will slow things down and still not great for durability (disk could be damaged).
This will disable fsync in writeback mode.
> disable fsync in writeback mode

- pkg/meta/redis.go
During compaction, it decrease the reference count using old key rather than the key in a hash set, which cause a slowly memory leak in Redis, depends on the number of compaction.
The leaked keys can be found and removed using `juicefs gc`.
> fix memory leak in Redis

- pkg/vfs/handle.go
When writeback-cache mode is enabled for FUSE, it is possible to READ a file opened with O_WRONLY.
Refs: https://www.kernel.org/doc/Documentation/filesystems/fuse-io.txt
> vfs: try open reader when necessary

- pkg/object/minio.go
`./juicefs format --storage minio --bucket http://minio.juicefs.local:9000/minio/juicefs-dev ... dev`
Currently `minio` storage will display: `<INFO>: Data uses minio.juicefs.local:9000dev/` which is `{{endpoint}}{{prefix}}/` (the `{{prefix}}` is the volume name)
This PR fix it to `minio://minio.juicefs.local:9000/juicefs-dev/dev/` which is `minio://{{endpoint}}/{{bucket}}/{{prefix}}/`
> fix minio storage bucket display string

- go.mod
- go.sum
- pkg/object/object_storage_test.go
- pkg/object/obs.go
There is a bug in Huawei OBS SDK [1] which does not reset the reader before retry PUT and causes DATA LOSS.
[1] https://github.com/huaweicloud/huaweicloud-sdk-go-obs/blob/master/obs/http.go#L426
> disable retry for OBS

- .github/workflows/diagram.yml
Use [repo-visualizer](https://github.com/githubocto/repo-visualizer) to generate a diagram of the project.
Some examples of the generated SVG diagram:
1. https://github.com/githubocto/repo-visualizer-demo
2. https://github.com/suzaku/shonenjump
With this configuration, a new diagram will be committed in `docs/images` whenever something is pushed to `main`.
> Integrate Github codebase visualizer into JuiceFS workflow

- pkg/meta/redis_test.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
When some slices was skipped in compaction, the new slices will be corrupted.
Closes #749
> fix compaction when skip some slices for sql and tikv engine

- pkg/chunk/cached_store.go
When error is `nil`, currently the output is `%s!(<nil>)`.
> Fix format error in log when it's `nil`

- .github/workflows/release.yml
- go.mod
Go 1.17 is out, so we can build the release with Go1.16 and require Go1.15+
Close #767
> require go1.15 and build release with go1.16

- pkg/meta/redis.go
- pkg/meta/redis_test.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
From man 2 chown:
>   When the owner or group of an executable file are changed by an unprivileged user the S_ISUID and
>  S_ISGID mode bits are cleared.  POSIX does not specify   whether  this  also  should happen when root
>  does the chown(); the Linux behavior depends on the kernel version.  In case of a non-group-executable file
>       (i.e., one for which the S_IXGRP bit is not set) the S_ISGID bit indicates mandatory locking, and is not cleared by a chown().
> keep SGID when file is non-group-executable

- pkg/meta/tkv.go
> meta/tikv: retry transaction when encontering TxnLockNotFound error

- cmd/format.go
- pkg/object/ceph.go
Inside CSI controller and node pod, we can't setup the configuration for Ceph from secrets, so we can disable the check for it in node and controller pod.
> disable check of object storage using env

- sdk/java/src/main/java/io/juicefs/JuiceFileSystemImpl.java
- sdk/java/src/test/java/io/juicefs/JuiceFileSystemTest.java
srcs should be deleted after concat according to HDFS implementation
> hadoop: fix concat bug

- pkg/object/ks3.go
The KS3 SDK does not support escaped access keys.
> Unescape Access Key for KS3

- cmd/format.go
`lz4` is the previous default compress algrithm, and we changed that
to `none` in v0.12, then you can't update the AK/SK without specifying
`--compresss` for existing volumes.
This PR allows user to update AK/SK without specify `--compress` for
existing volumes.
> keep existing LZ4 algr when formatted with default algr.

- pkg/meta/redis.go
with meta url being: `redis://mymaster,10.XX.XX.197,10.XX.XX.193,10.XX.XX.67:26379`
from: 
```
SentinelAddrs: ([]string) (len=3 cap=3) {
(string) (len=6) ":26379",
(string) (len=6) ":26379",
(string) (len=18) "10.XX.XX.67:26379"
},
```
to
```
SentinelAddrs: ([]string) (len=3 cap=3) {
(string) (len=20) "10.XX.XX.197:26379",
(string) (len=20) "10.XX.XX.193:26379",
(string) (len=18) "10.XX.XX.67:26379"
},
```
Close https://github.com/juicedata/juicefs/pull/953
> fix redis-sentinel addresses parsing

- .github/workflows/verify.yml
- .travis.yml
- docs/en/client_compile_and_upgrade.md
- docs/en/hadoop_java_sdk.md
- docs/en/how_to_setup_object_storage.md
- docs/zh_cn/client_compile_and_upgrade.md
- docs/zh_cn/how_to_setup_object_storage.md
- fstests/Makefile
- go.mod
- pkg/object/file.go
file.Readdir() calls lstat() on every file, so it's slow on huge directory.
This PR changed to use file.ReadDir(), which does not call lstat(), then we can return some of the files earlier.
> speedup listing on file

- Makefile
- pkg/meta/dump.go
- pkg/meta/redis.go
- pkg/meta/redis_lock.go
- pkg/meta/sql.go
- pkg/meta/sql_lock.go
- pkg/meta/sql_mysql.go
- pkg/meta/sql_pg.go
- pkg/meta/sql_sqlite.go
- pkg/meta/tkv.go
- pkg/meta/tkv_mem.go
- pkg/meta/tkv_tikv.go
- pkg/meta/types.go
- pkg/meta/utils.go
- pkg/object/b2.go
- pkg/object/redis.go
- pkg/object/tikv.go
- pkg/object/ufile.go
The full build is 80MB, current lite version is 43MB, this PR reduce the size to 25MB by removing TiKV, PG, MySQL, SQLite engines.
> reduce the size of juicefs.lite

- pkg/fuse/fuse.go
- pkg/winfsp/winfs.go
`du` aligns the size of file to `frsize` of the file system,  the `frsize` of local file system is 4K, but JuiceFS has it as 64K. we see different result when comparing the size of files in local file system and JuiceFS, see #1014 for details.
It's meaningless in JuiceFS , so we can change it to 4K, so it's compatible with local file system.
close #1014
> change frsize to 4096

- pkg/meta/dump.go
- pkg/meta/load_dump_test.go
- pkg/meta/redis.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
- pkg/utils/utils.go
> Speed up dump for sql engine

- pkg/meta/redis.go
- pkg/meta/redis_test.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
The original implements will always return ok if open a file that does
not exist.
Another unresolved problem is that if an "attr" is given with "Full=true", even
if they do not match, the "GetAttr()" call will still be skipped. But
this does not seem to be a serious problem.
Signed-off-by: 炽天 <hanxin.hx@alibaba-inc.com>
> metadata: should not skip error if open a file not exist

- pkg/object/minio.go
- pkg/object/object_storage_test.go
When a subpath is specified with Minio, juice sync fails with 403.
TODO: we should enable the unit test with Minio
> fix minio with sync

- pkg/fs/fs_test.go
- pkg/fuse/fuse.go
- pkg/meta/base.go
- pkg/vfs/vfs_test.go
- pkg/vfs/vfs_unix.go
- pkg/winfsp/winfs.go
After we change the frsize to 4K, the bsize is still 64K, and we use bsize to calculate the blocks, but df use `frsize` to calculate the used space in Linux.
This PR change both to 4K.
Closes #1069
> fix used space in df

- pkg/meta/tkv.go
Backup will call DumpMeta in the background, so it raises critical problem if m.client is replaced
> tkv: use snap for dumping meta

- pkg/meta/base.go
SubTrash is cached in clients, so it mustn't be remove manually
> meta: forbid removing subTrash directories

- pkg/meta/redis.go
The `gc` command will scan all the entries and inodes to find out dangling (not used by any entry) inodes.  The scanning of entries is not atomic, so we ignore all the inodes (checking the atime) created in last hour. There is still a chance that a inode was renamed and both the old name and new name are missed from the scanning, then the inode will be identify as dangling and deleted.
This PR change it to check the Ctime of inode, ignore the inodes that was created or renamed within a hour.
> Fix potential metadata corrupt in Redis caused by gc

- pkg/meta/metadata-sub.sample
- pkg/meta/metadata.sample
- pkg/meta/redis.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
|             | Redis - Key | SQL/TKV - Key | Redis - Value | SQL/TKV - Value |
| ----------- | ----------- | ------------- | ------------- | --------------- |
| NextInode   | nextinode   | nextInode     | max used      | next available  |
| NextChunk   | nextchunk   | nextChunk     | max used      | next available  |
| NextSession | nextsession | nextSession   | max used      | max used        |
- Redis nextInode & nextChunk have different meanings, which is handled here: https://github.com/juicedata/juicefs/blob/main/pkg/meta/redis.go#L271-L276
- All other counters are identical in the three engines.
> meta: unify counters for all metadata engines

- pkg/meta/sql.go
> meta/mysql: don't error out if there are 'duplicate' keys in Sync2

- pkg/meta/sql.go
SQLite, MySQL and PG may have different error messages when inserting a duplicate key, so it should be better to just check existence first.
> meta/sql: check if trash inode exists

- pkg/meta/base.go
- pkg/meta/redis.go
- pkg/meta/redis_test.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
The man page of chown does not mention the behavior for directory, so we keep the behavior close to ext3/ext4 in Linux.
In macOS (darwin), we pick the behavior in APFS.
close #1132
> Keep SGID for directory

- pkg/meta/tkv.go
fix the bug founded by wechat `crud_boy`
> fix fmtKey to sliceKey

- cmd/config.go
- cmd/config_test.go
- cmd/format.go
- cmd/main.go
- pkg/meta/redis.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
close #1063 
For now the `format` command is not touched, so it can still be used to change the config as well.  However, the new `config` is a recommended way, and `format` will be deprecated (only keep the real **FORMAT** function) after one or two minor versions.
> cmd: add `config` command to change config of a volume

- pkg/fs/fs.go
- pkg/fs/fs_test.go
- pkg/gateway/gateway.go
Slash is a separator in JuiceFS, the trailing slash means the last component is a directory, so we can't allow upload an object with trailing slash.
close #1129
> fix mkdir/rename/delete/rmr with trailing slash

- pkg/gateway/gateway.go
os.ErrNotExist triggers 500 http code (InternalError), syscall.ENOENT triggers 404 code which is expected
> fix gateway GetObjectInfo http code 500 to 404

- cmd/fsck.go
- cmd/gc.go
- cmd/mount.go
- docs/en/reference/command_reference.md
- docs/zh_cn/administration/cache_management.md
- docs/zh_cn/reference/command_reference.md
- sdk/java/src/main/java/io/juicefs/Main.java
The Java SDK still use 100MB memory as block cache.
close #1076
> change default cache-size to 100GB

- docs/en/administration/sync_accounts_between_multiple_hosts.md
- docs/zh_cn/administration/sync_accounts_between_multiple_hosts.md
Prompt the user for a global UID, GID config file that can only be used in a Hadoop environment.
> Docs: update "Sync Accounts between Multiple Hosts" doc

- cmd/sync.go
- cmd/sync_test.go
support 
- `s3-ENDOINT.amazonaws.com/BUCKET/PREFIX`  
- `s3.ENDOINT.amazonaws.com/BUCKET/PREFIX` 
- `localhost:8088/BUCKET/PREFIX`
- `localhost/BUCKET/PREFIX`
- `127.0.0.1:8088/BUCKET/PREFIX`
- `127.0.0.1/BUCKET/PREFIX`
> improve s3 url parsing

- cmd/format.go
- pkg/chunk/singleflight_test.go
When the bucket does not exist, the object store will return the corresponding error code `NoSuchBucket` (e.g. [S3](https://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html#ErrorCodeList), [OSS](https://help.aliyun.com/document_detail/185804.htm?#title-p5t-cwc-kcv), [COS](https://cloud.tencent.com/document/product/436/7730#.E9.94.99.E8.AF.AF.E7.A0.81.E5.88.97.E8.A1.A8)). This PR fix creates a bucket only when it really does not exist.
Incorrect conditional judgments can cause the log to output something that is confusing to the user, e.g. `please create bucket XXX manually, then format again`.
> format: Only try to create bucket when it really doesn't exist

- cmd/main.go
We have to always call the `gspt.SetProcTitle` to adjust the title, or it will be reset to args[0] after the `gspt` package initialized.
See: https://github.com/erikdubbelboer/gspt/blob/ce36a5128377/gspt.go#L55
> cmd: always call setproctitle

- Makefile
This is the script to compile the Linux version on the MacOS platform.
But you need to execute the `brew install FiloSottile/musl-cross/musl-cross` command before use.
> Add cross-platform compile script

- ADOPTERS.md
- ADOPTERS_CN.md
SAIC Motor uses JuiceFS in the private cloud, and share their use case in https://mp.weixin.qq.com/s/Lh5UEVw4-gCe6wAVcmznxg
Add SAIC Motor in adopter list.
> add SAIC Motor in adopter list

- pkg/object/s3.go
Thanks to @[joey71765](https://github.com/joey71765)  for testing support!
> s3 support pvc link

- pkg/vfs/handle.go
- pkg/vfs/vfs.go
When a file handle is released, a write lock was hold forever,
then concurrent truncate (open with new handle) will be deadlock.
This PR remove the write lock when release a file handle, also
remove it before closing the handle. There should be no other
read/write operations.
> Fixed deadlock when truncate a released file handle.

- pkg/meta/base.go
- pkg/meta/sql.go
> meta: limit the number of clients running background cleanup jobs

- docs/en/getting-started/for_local.md
As the practice example uses AWS, it would be better to set --storage option to s3 directly.
> docs: Update for_local.md storage option to s3

- pkg/meta/tkv_prefix.go
- pkg/meta/tkv_tikv.go
close #1454 
`nil` means unbounded upperBound, which makes `iter` returns unrelated keys
> meta/tikv: fix scan of tikv, limiting the upperbound

- Makefile
- cmd/gateway.go
- cmd/main.go
- cmd/mount.go
- cmd/webdav.go
- cmd/webdav_noop.go
- pkg/fs/http.go
support webdav protocol #1441 #1378
> support webdav protocol

- cmd/gateway.go
- cmd/mount.go
- pkg/vfs/vfs.go
- sdk/java/libjfs/main.go
> vfs: add `BackupMeta` in config

- cmd/gateway.go
- cmd/mount.go
- pkg/meta/base.go
- pkg/meta/config.go
- pkg/meta/redis.go
- sdk/java/libjfs/main.go
- sdk/java/src/main/java/io/juicefs/JuiceFileSystemImpl.java
> meta: add an option `no-bgjob` to disable background jobs

- .github/workflows/wintest.yml
The failed action is https://github.com/juicedata/juicefs/runs/5316344226?check_suite_focus=true and
the reason is the update of window's version . More details may refer to https://github.com/actions/virtual-environments/issues/4856 .
> CI: change windows version

- cmd/umount.go
> cmd/umount: use umount instead of diskutil for darwin

- pkg/object/s3.go
- pkg/utils/rusage_test.go
--bucket format `https://${bucketName}.${namespace}.compat.objectstorage.${region}.oraclecloud.com`
eg: https://zhijian-test.axntujn0ebjj.compat.objectstorage.ap-singapore-1.oraclecloud.com
> support Oracle object storage

- docs/en/security/encrypt.md
As `genrsa` has been [deprecated](https://www.openssl.org/docs/manmaster/man1/openssl-genrsa.html) on OpenSSL 3.0
Also, describe the static encryption method will be stored on the Metadata service _(depending which one is used, can be other than Redis)_.
> Add genpkey command

- pkg/gateway/gateway.go
delete objects will cause panic when has errs, use the same logic as gateway-s3.go (L:538)
**panic here：**
**fix this bug, reference gateway-s3.go  (L:538) logic:**
> fix s3 gateway DeleteObjects panic

- Makefile
close #1540 
Test may fail because of deep stack:
```
=== RUN   TestSingleFlight
panic: runtime error: growslice: cap out of range
goroutine 83304 [running]:
github.com/juicedata/juicefs/pkg/chunk.(*Page).Acquire(0xc014cf9580)
/home/travis/gopath/src/github.com/juicedata/juicefs/pkg/chunk/page.go:77 +0x125
github.com/juicedata/juicefs/pkg/chunk.(*Controller).Execute(0xc000557a60, 0x1bc5736, 0x2, 0x1bce9b8, 0xc014cf82c0, 0x0, 0x0)
/home/travis/gopath/src/github.com/juicedata/juicefs/pkg/chunk/singleflight.go:42 +0xe5
github.com/juicedata/juicefs/pkg/chunk.TestSingleFlight.func1(0xc000557a60, 0xc000046cb0, 0x14484)
/home/travis/gopath/src/github.com/juicedata/juicefs/pkg/chunk/singleflight_test.go:32 +0x7e
created by github.com/juicedata/juicefs/pkg/chunk.TestSingleFlight …
```
> make: disable JFS_PAGE_STACK for tests

- hack/builder/Dockerfile
> upgrade golang-cross version to v1.17.8

- .github/workflows/elastictest.yml
- .github/workflows/ltpfs.yml
- .github/workflows/ltpsyscallshead.yml
- .github/workflows/ltpsyscallsmiddle.yml
- .github/workflows/ltpsyscallstail.yml
- .github/workflows/mysqltest_bigtable.yml
- .github/workflows/mysqltest_smalltable.yml
- .github/workflows/mysqltest_smalltablelocal.yml
- .github/workflows/mysqltest_smalltablelocalchangedir.yml
- .github/workflows/pjdfstest.yml
- .github/workflows/redis_compile.yml
- .github/workflows/release.yml
- .github/workflows/sysbench_smallfile_randrw.yml
- .github/workflows/sysbench_smallfile_seqrw.yml
- .github/workflows/tpcds.yml
- .github/workflows/verify.yml
- .github/workflows/wintest.yml
- .travis.yml
- docs/en/deployment/hadoop_java_sdk.md
- docs/en/getting-started/installation.md
- docs/en/reference/how_to_setup_object_storage.md
- docs/zh_cn/getting-started/installation.md
- docs/zh_cn/reference/how_to_setup_object_storage.md
- go.mod
Go 1.18 is released and 1.16 is also deprecated, we should upgrade it to 1.17.
> switch to Go 1.17

- .goreleaser.yml
- Makefile
1. `.CommitDate` of new version of [goreleaser](https://github.com/goreleaser/goreleaser) has timestamp part, use environment instead of `.CommitDate`
2. Add macOS arm64 arch build `juicefs` binary
> Fix goreleaser

- pkg/object/sharding.go
> object/sharding: fix ListAll returning invalid objects

- pkg/meta/redis.go
- pkg/meta/utils.go
#1593 
```
try = 0: sleep = 0
if kill -9 (connection refused): write wait = 0
if down host (i/o timeout): write wait = opt.WriteTimeout = 5s
min, max = opt.MinRetryBackoff, opt.MaxRetryBackoff = 20ms, 10s
try = 1; sleep ~= min << 1 / 2 + min = 40ms
try = 2; sleep ~= min << 2 / 2 + min = 60ms
...
try = 9; sleep ~= min << 9 / 2 + min = 5s
try = 10; sleep ~= min << 10 / 2 + min = 10s
Once = (10 + 5 + 2.5 + 1.25 + ...) + 11 * (write wait)
= 20s or 75s
Total = Once * 2
= 40s or 150s
```
> meta/redis: use smaller retry backoff in sentinel mode

- pkg/object/object_storage.go
- pkg/object/sharding.go
- pkg/sync/sync.go
- pkg/utils/errors.go
> object: fallback to List only if ListAll is not supported

- .github/workflows/release.yml
Add the `-amd64` suffix to the JAR package name of the Hadoop Java SDK to indicate the CPU architecture
> Workflow: canonicalize Hadoop Java SDK name

- cmd/sync.go
- docs/en/reference/command_reference.md
- docs/zh_cn/reference/command_reference.md
- pkg/sync/config.go
- pkg/sync/sync.go
- pkg/sync/sync_test.go
> support sync limits

- pkg/vfs/backup.go
1. if `backup-meta` <= one hour, skip backup when number of inodes exceeds 1m.
2. if `backup-meta` > one hour, it means user has changed this option explicitly. In this case no more check is applied.
As a reference, a simple test with Redis as meta shows that it takes ~5 mins to backup 1m files, consuming ~2G memory.
> vfs/backup: reduce the limit for skipping backup

- pkg/object/file.go
- pkg/object/object_storage.go
> sync: reduce memory allocation when write into files

- pkg/sync/sync.go
After upgrading `urfave` from v2.3.0 to v2.4.0, the default value of StringSliceFlag is an empty slice, not nil any more (maybe a bug of `urfave` cuz the comment is not changed)
> sync: fix empty value of StringSliceFlag

- pkg/meta/utils.go
fix #1709 
The auto-created subdir has mode 777, and uid/gid = 0.
> meta: create subdir automatically

- cmd/flags.go
- cmd/mount.go
- docs/en/reference/command_reference.md
- docs/zh_cn/reference/command_reference.md
- pkg/chunk/cached_store.go
- pkg/chunk/cached_store_test.go
- pkg/meta/base.go
- sdk/java/libjfs/main.go
- sdk/java/src/main/java/io/juicefs/JuiceFileSystemImpl.java
> Set max retries of meta & chunk according to the config `io-retries`

- pkg/object/obs.go
We have experienced data loss from OBS silently, so we should double check the returned ETag from OBS.
> Verify Etag from OBS

- cmd/format.go
- pkg/object/encrypt.go
- pkg/object/encrypt_test.go
> fix parse rsa from pem

- go.mod
- go.sum
Progress bar module code change content https://github.com/juicedata/mpb/commit/092927ed012210658e86778c0ea9e03f3b4cf0c6
> fix the problem that the progress bar loses the log

- cmd/info.go
- cmd/rmr.go
- cmd/warmup.go
- pkg/vfs/vfs.go
- pkg/vfs/vfs_test.go
fix #1739
Reference: https://code.google.com/archive/p/macfuse/wikis/OPTIONS.wiki
> vfs: write control file asynchronously

- pkg/meta/dump.go
- pkg/meta/load_dump_test.go
- pkg/meta/redis.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
This pr is mainly to solve the problem that juicefs cannot create files whose filenames are not UTF8 encoded when using the sql type of metadata engine
To solve this problem, the metadata database field type needs to be updated, so there is a certain compatibility problem with the old version. The following is a smooth upgrade scheme for upgrading the old version to this version:
1. If there are old clients in mount state, they can be upgraded without stopping them
2. Enter the metadata database and manually execute sql
```sql
alter table jfs_edge
modify name varbinary(2048) not null;
alter table jfs_symlink
modify target blob not null;
```
3. At this time, the old client in the mount state can already write files with non-utf8 file names, but it should be noted that after executing sql, …
> sql: changing name column type to binary type

- pkg/meta/config.go
- pkg/meta/redis.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
> meta: specify the format field preventing update

- pkg/sync/sync.go
> sync: Fix copied and copiedBytes

- docs/en/benchmark/benchmark.md
Hi, is this word "a" redundant in doc benchmark？
> remove needless word "a"

- pkg/meta/sql.go
> split insert batch

- pkg/meta/sql.go
- pkg/meta/sql_lock.go
There is a bug in xorm when scanning a binary column, it could return partial or wrong result.
This PR fix that by reset the binary column before scan next row.
> meta/sql: fix wrong result from scanning SQL database

- ADOPTERS.md
- ADOPTERS_CN.md
Trip.com uses the JuiceFS in file sharing, data backup and clickhouse data tiering, add it in the adopter list.
> add Trip.com in adopter list

- pkg/meta/redis.go
If there is a big directory or big file, the pipeline could be too big for Redis to process, we should split them into smaller batches.
> meta/redis: fix loading large directory into Redis

- pkg/meta/redis.go
- pkg/meta/redis_test.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
- pkg/meta/utils.go
> meta: check legacy sessions as well

- cmd/flags.go
- cmd/format.go
- cmd/mount_unix.go
- cmd/warmup_test.go
> cmd: use homedir as default working directory for non-root users

- ADOPTERS.md
- ADOPTERS_CN.md
Vivo uses the JuiceFS in AI and other workloads for storage, management intensive data. Add vivo in the adopter list.
> add vivo in adopter list

- pkg/meta/interface.go
> meta: escape meta password from env

- docs/en/reference/fuse_mount_options.md
- docs/en/reference/p8s_metrics.md
- docs/en/reference/posix_compatibility.md
@davies  Could you give a quick review on this proofread? Only minor changes have been made. Thanks! :)
A question here: https://github.com/juicedata/juicefs/blob/main/docs/en/reference/fuse_mount_options.md#debug 
Does the option `-d` refers to enabling debug log? Maybe it is better to make it clearer in the document?
> proofread: fuse_mount_options.md minor change

- pkg/sync/sync.go
- pkg/sync/sync_test.go
When both include and exclude can be matched, the matching part in the original path has a higher priority closer to the beginning of the path
```bash
$ tree jfs_source
jfs_source
└── pkg
├── chunk
│   ├── mem_cache.go
│   └── singleflight_test.go
└── winfsp
├── trace.go
└── winfs.go
3 directories, 4 files
$ juicefs sync jfs_source/ jfs_sync_dir/ --dirs --include 'chu*/' --exclude 'pkg'
2022/04/24 17:53:04.606866 juicefs[18994] <INFO>: Syncing from file:///tmp/jfs_source/ to file:///tmp/jfs_sync_dir/ [sync.go:610]
Scanned objects count: 1 / 1 [==============================================================]  done
Copied objects count: 0
Copied objects bytes: 0.00 b (0 Bytes)   0.00 b/s
Checked objects bytes: 0.00 b (0 Bytes)   0.00 b/s
Deleted objects count: 0
Skipped objects count: 1 …
```
> fix partial match

- .github/workflows/version_compatible.yml
- pkg/meta/sql.go
> meta/sql: add primary key for all tables

- .gitignore
- cmd/flags.go
- cmd/mount.go
allow mount to select storage typ other than default from format.
> cli flag allow customized storage type

- ADOPTERS.md
- ADOPTERS_CN.md
Horizon Robotics uses the JuiceFS to store and manage datasets in its AI platform and train models for self-driving cars.
Add it to the adopter list.
> add Horizon Robotics to the adopter list

- .github/workflows/sync.yml
juicefs sync and rsync will handle .accesslog in the same way.
> don't need to exclude .accesslog file because its size is 0.

- cmd/sync.go
- pkg/object/sftp.go
When the path of sftp does not ends with `/`, it added `/` between the path and found keys, which is wrong.
Also, this PR added support for ssh-agent, so we don't need to specify the path to private key.
> sync/sftp: fix prefix of sftp, support ssh-agent

- pkg/meta/tkv.go
- pkg/meta/tkv_badger.go
- pkg/meta/tkv_etcd.go
- pkg/meta/tkv_mem.go
- pkg/meta/tkv_prefix.go
- pkg/meta/tkv_test.go
- pkg/meta/tkv_tikv.go
Currently, we use transaction to scan all the metadata, which is heavy (bookkeeping) and easy to fail (timeout or others), this  PR change it to iterator on read-only snapshot (based on timestamp or revision).
> meta/tkv: dump metadata using snapshot

- pkg/meta/dump.go
- pkg/meta/load_dump_test.go
- pkg/meta/metadata-sub.sample
- pkg/meta/metadata.sample
> meta: keep valid utf8 in dumped JSON

- pkg/object/oss.go
After adding UserAgent header，ali can analyzes the request's delay for customers using juicefs， and can make some optimizations
close #1992
> add user agent for oss #1992

- pkg/vfs/internal.go
- pkg/vfs/vfs.go
- pkg/vfs/vfs_test.go
File `.control` is used for internal communication, should be hide from end users.
> vfs: hide .control from readdir

- docs/en/getting-started/for_distributed.md
- docs/en/getting-started/for_local.md
- docs/zh_cn/getting-started/for_distributed.md
- docs/zh_cn/getting-started/for_local.md
Using the relative path `mnt` to represent the mount point may make it unclear to the user what the specific mount directory is. Using an absolute path will make it clearer.
> Docs: use absolute path to represent the mount point in quick start guide

- pkg/object/prefix.go
Storage of type whithprfix should behave in the same way as the storage it wraps.
> object: fix with prefix

- pkg/object/minio.go
`err` is always nil here
close #2008
> object/minio: remove unused error

- pkg/meta/sql.go
we use lock in SQL database to avoid conflict, the order of locks should be the same, otherwise there will be deadlock.
There is order: parent -> edge -> node -> chunk/flock/plock/edge
For rename, there is two parents, so we lock them in the beginning.
close #2060
> meta/sql: fix the deadlock in rename

- docs/en/tutorials/juicefs_on_colab.md
Fix the header marker format which would result in `docusaurus build` failed when deploy to [web](https://juicefs.com/docs/)
> fix head marker format

- pkg/meta/sql.go
xorm may try to create duplicated index during `Sync2`, we should ignore that. 
closes #2080
> meta/sql: ignore error about duplicated index

- pkg/meta/base.go
- pkg/meta/redis.go
- pkg/meta/sql.go
- pkg/meta/sql_lock.go
- pkg/meta/tkv.go
- pkg/meta/tkv_lock.go
This PR bring the pessimistic lock used in Redis engine to all of the meta engines.
> meta: add pessimistic lock to reduce conflicted transaction in database

- cmd/main.go
- cmd/mdtest.go
This is a internal test tool similar to mdtest, but run in userland, expected to be faster.
> add a tool to run tests again meta engine

- sdk/java/libjfs/main.go
- sdk/java/src/main/java/io/juicefs/JuiceFileSystemImpl.java
> sdk/java: don't reuse fd in Java SDK

- go.mod
- go.sum
- pkg/meta/sql.go
This PR upgrade xorm to 1.3.0 and patch it to always use repeatable-read isolation level for transaction.
close #2110
> meta/sql: use repeatable-read for transaction

- pkg/meta/sql.go
There is a bug in xorm, the buffered iterater may return partial results.
closes #2110
> meta/sql: fix dump with more than 10000 files

- .github/workflows/tpch_clickhouse.yml
- .github/workflows/tpch_clickhouse_limitcache.yml
du: cannot access '/var/jfsCache/33b603ab-cdaf-44b4-b05a-48ee7e332813/raw/chunks/0/5/5628_0_1048576': No such file or directory
du: cannot access '/var/jfsCache/33b603ab-cdaf-44b4-b05a-48ee7e332813/raw/chunks/0/5/5275_0_1048576': No such file or directory
du: cannot access '/var/jfsCache/33b603ab-cdaf-44b4-b05a-48ee7e332813/raw/chunks/0/5/5415_0_4096': No such file or directory
More details may refer to https://github.com/juicedata/juicefs/runs/6599792359?check_suite_focus=true.
> fix clickhouse du jfscache err

- pkg/meta/dump.go
- pkg/meta/tkv.go
- pkg/meta/tkv_mem.go
The btree used by memkv is still to slow, this PR change to use go map instead.
> meta/tkv: Speedup dump for kv storage

- pkg/meta/tkv.go
Currently, we need to load all the entries into memory, then write them into kv storage one by one. This PR change it to load entries as a stream and write them into kv storage as batches.
For a volume with 10 millions of files, this PR reduce  the memory from 20G to 1G,  reduce  the time to load into badge from 12 minutes to 2 minutes.
> meta/tkv: reduce memory for loading into kv storage

- .github/workflows/rmdirectory.yml
- .github/workflows/rmfiles.yml
/home/runner/work/_temp/d5604aef-e1c5-4e69-8bff-ac019aa78f50.sh: line 1: cd: /tmp/juicefs-sync-test/: No such file or directory
Error: Process completed with exit code 1.
https://github.com/juicedata/juicefs/runs/6747044587?check_suite_focus=true
> CI:fix rm action err

- pkg/meta/dump.go
- pkg/meta/load_dump_test.go
- pkg/meta/redis.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
Currently, we dump all the key-values from Redis into JuiceFS's memory, then build the file system tree and dump them as JSON stream, it require lots of memory to hold all the metadata, for example, 10 millions of files require 9GB memory.
Since Redis holds all the data in memory, we can access them very fast in random order, similar to the memory snapshot it builds. So this PR remove the in-process snapshot and fetch data from Redis in batch and in parallel.
For a test with 11 millions of small files, this PR can reduce the time to dump from 13 minutes to 3.5 minutes, it also reduce the memory from 9GB to 300 MB.
> meta/redis: Speedup dump for Redis and reduce memory usage

- cmd/main.go
Hi community, I find panic will be triggered by missing argument, like below
I think that eliminating this panic will make Juicefs CLI  more friendly.
> eliminate panic which is triggered by missing argument

- pkg/meta/utils.go
This reverts commit 03175d2b7f7b41ff1eb679d716deafeb0b6412c0.
> Revert "meta: reduce concurrency of RMR (#2102)"

- .github/workflows/list.yml
/home/runner/work/_temp/[8](https://github.com/juicedata/juicefs/runs/6742429178?check_suite_focus=true#step:7:9)2064f78-3cbf-4872-a16c-a2c65d02be75.sh: line 1: cd: /tmp/juicefs-sync-test/createfile/: No such file or directory
Error: Process completed with exit code 1.
https://github.com/juicedata/juicefs/runs/6742429178?check_suite_focus=true
> CI:fix list action err

- pkg/fs/fs.go
- pkg/meta/base.go
- pkg/meta/base_test.go
- pkg/meta/benchmarks_test.go
- pkg/meta/interface.go
- pkg/meta/redis.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
- pkg/meta/utils.go
- pkg/vfs/internal.go
When removing directories with many files in parallel, they need lots of memory for these entries. 
This PR change to remove them as smaller batches (10000), so it will hold at most 500K entries in memory (100-200MB). 
For smaller directories, it will take one more readdir() to ensure that the directory is empty (better for concurrent adding files).
> cmd/rmr: remove entries in batch

- cmd/mount.go
> meta/tkv: use absolute path for badgerDB as metadata engine

- pkg/meta/sql.go
Vitess is a MySQL proxy, which does not support read-only transactions, we will fallback to default transactions.
close #2237
> support database without read-only transaction

- cmd/mount.go
> bugfix: --backup-meta could be 0 to disable backup

- .goreleaser.yml
We may create a temporary pre-release tag before an official release to test the whole release flow, this PR remove the auto homebrew tap update in goreleaser process. We'll update the homebrew tap in another process after the release.
> skip auto update brew tap in goreleaser

- pkg/meta/interface.go
> cmd/info: Fix repeat path info when inode is 1

- .github/workflows/elastictest.yml
Elasticsearch action failed .
More details may refer to https://github.com/juicedata/juicefs/actions/runs/2521673386 .
> CI:add log to elasticsearch test

- .github/workflows/redis_compile.yml
*** [err]: Don't rehash if redis has child proecess in tests/unit/other.tcl
Expected '[Dictionary HT]
Hash table 0 stats (main hash table):
table size: 4096
number of elements: 4099
different slots: 2619
max chain length: 7
avg chain length (counted): 1.57
avg chain length (computed): 1.57
Chain length distribution:
0: 1477 (36.06%)
1: 1551 (37.87%)
2: 743 (18.14%)
3: 253 (6.18%)
4: 59 (1.44%)
5: 12 (0.29%)
7: 1 (0.02%)
[Expires HT]
No stats available for empty dictionaries
' to match '*table size: 16384*' (context: type eval line 16 cmd {assert_match "*table size: 16384*" [r debug HTSTATS 9]} proc ::test)
Cleanup: may take some time... OK
make[1]: *** [Makefile:349: test] Error 1
make[1]: Leaving directory '/tmp/jfs/redis/src'
make: *** [Makefile:6: test] Error 2
Error: Process completed …
> CI: add redis failure log

- cmd/profile.go
For a new line without any other item, `fmt.Scanln` returns error: `unexpected newline`
> cmd/profile: ignore error of Scanln

- docs/en/administration/upgrade.md
- docs/en/deployment/hadoop_java_sdk.md
- docs/en/getting-started/README.md
- docs/en/getting-started/for_distributed.md
- docs/en/getting-started/installation.md
- docs/en/introduction/README.md
- docs/en/reference/command_reference.md
- docs/zh_cn/administration/upgrade.md
- docs/zh_cn/deployment/hadoop_java_sdk.md
- docs/zh_cn/getting-started/README.md
- docs/zh_cn/getting-started/for_distributed.md
- docs/zh_cn/getting-started/installation.md
- docs/zh_cn/reference/command_reference.md
- The upgrade-related content is stripped from the "Installation" document and becomes a new document independently, and more client upgrade instructions are added.
- Added "Verify the file system" section to Quick Start Guide
> Docs: add new "Upgrade" and "Verify the file system" document

- sdk/java/libjfs/guid.go
- sdk/java/libjfs/main.go
- sdk/java/src/main/java/io/juicefs/JuiceFileSystemImpl.java
SDK has two params ``juicefs.users`` and ``juicefs.groups`` to overwrite local guidmapping.
So when name2id mapping is overwrited. name2id should not lookup the local to avoid multiple uid to the same name confusion.
> hadoop: do not use local uid/gid if global user/group specified

- go.mod
- go.sum
This reverts commit 089ee12419b331fe4f63ec6316e7f0b375cd7e9a.
> Revert "upgrade the go version to 1.18 (#2454)"

- go.mod
- go.sum
- pkg/object/hdfs.go
According to [hdfs](https://github.com/colinmarc/hdfs). In v2.3.0，hdfs will return ErrReplicating when namenode is not complete.
```
Previously, we would simply ignore the result field on CompleteResponse, which
lead to a silently hanging lease on the file. A hanging lease isn't that bad -
it expires on its own - but it was causing the sneaky
AlreadyBeingCreatedExceptions we were seeing in append tests.
```
since we do not append to a existing file in HDFS. It's ok to ignore this error
> upgrade go-hdfs

- hack/builder/Dockerfile
This is the `Dockerfile` for [juicedata/golang-cross:latest](https://hub.docker.com/r/juicedata/golang-cross) image
> upgrade docker cross build image's golang version to 1.18

- sdk/java/src/main/java/io/juicefs/JuiceFileSystemImpl.java
- sdk/java/src/test/java/io/juicefs/JuiceFileSystemTest.java
> hadoop: allow concat to empty file

- cmd/gateway.go
- pkg/gateway/gateway.go
Currently, gateway does not respect the umask flag specified in the start command, instead, it hard codes 755 for all the directories it creates. I have added an option, umask-dir, which will dictate the umask for all the mkdir calls. I keep them as separate flags in case some users would like their umasks different for folders and directories.
The following screenshots show different behaviors when gateway is started with umask-dir 022 vs 000.
> pkg/gateway: Support specifying umask for directories

- pkg/compress/compress.go
- pkg/compress/compress_test.go
The LZ4 compressed result is not empty, we should check that before calling lz4.DecompressSafe, otherwise it will crash.
#2495
> fix LZ4 decompressing an empty input

- pkg/object/file_unix.go
Before this PR, the owner and group will be ignored if  the user/group is not found.
This PR will change it to use uid/gid instead.
> cmd/sync: sync uid/gid for not existed user/group

- cmd/main.go
```
$ /sbin/mount.juicefs mount
2022/08/12 16:13:18.700930 juicefs[5941] <WARNING>: [/sbin/mount.juicefs mount] [main.go:95]
panic: runtime error: index out of range [0] with length 0
goroutine 1 [running]:
github.com/juicedata/juicefs/cmd.reorderOptions(0xc000926340, 0x0, 0x0, 0x0, 0x0, 0x0, 0x19)
/data/timfeirg/ce/cmd/main.go:174 +0xfb9
github.com/juicedata/juicefs/cmd.Main(0xc0008dbde0, 0x2, 0x2, 0x0, 0x0)
/data/timfeirg/ce/cmd/main.go:84 +0x2054
main.main()
/data/timfeirg/ce/main.go:29 +0x49
```
> /sbin/mount.juicefs: do not crash when called with no opts

- cmd/gc.go
> cmd/gc: distinguish compacted objects from valid ones

- cmd/format.go
- pkg/meta/config.go
- pkg/object/encrypt.go
- pkg/object/encrypt_test.go
- pkg/object/object_storage_test.go
> pkg/object: support chacha20 cipher

- go.mod
- go.sum
JuiceFS is not affected by [CVE-2022-21698](https://github.com/prometheus/client_golang/security/advisories/GHSA-cg3q-j54f-5p7p), so we don't need to backport this into 1.0.
> upgrade etcd and prometheus/client_golang for security

- .gitignore
- cmd/bench_test.go
- cmd/fsck_test.go
- cmd/gc_test.go
- cmd/info_test.go
- cmd/integration_test.go
- cmd/main.go
- cmd/mount.go
- cmd/mount_test.go
- cmd/mount_unix.go
- cmd/rmr_test.go
- cmd/status_test.go
- cmd/warmup_test.go
PR code will produce the following result:
permission denied behavior:
closes https://github.com/juicedata/juicefs/issues/2432
> add / update fstab entry with --update-fstab

- cmd/main.go
`mount.juicefs redis://xxxx /mnt/jfs` can not work. fix it.
> fix mount.juicefs

- docs/en/guide/how_to_set_up_metadata_engine.md
- docs/zh_cn/guide/how_to_set_up_metadata_engine.md
- pkg/meta/sql.go
- pkg/meta/sql_test.go
- pkg/object/object_storage_test.go
- pkg/object/sql.go
> postgres : only one schema in search_path is allowed

- pkg/vfs/handle.go
- pkg/vfs/vfs.go
- pkg/vfs/vfs_unix.go
This reverts commit 68a7168deb949d21e7a33243a3701d1ce4bd2cb1.
Failed LTP tests caused by the previous commit:
```
fcntl14    30  TFAIL  :  fcntl14.c:635: Test case 30, GETLK: type = 0, 2 was expected
fcntl14    31  TFAIL  :  fcntl14.c:669: Test case 30, GETLK: pid = 57008, should have remained 0
fcntl14    32  TFAIL  :  fcntl14.c:708: Attempt to set child NONBLOCKING lock failed
fcntl14    33  TFAIL  :  fcntl14.c:710: Test case 30, errno = 11
fcntl14    30  TFAIL  :  fcntl14.c:890: tchild returned status 0x100
fcntl14    31  TFAIL  :  fcntl14.c:895: testcase:30 FAILED
fcntl14    32  TFAIL  :  fcntl14.c:895: testcase:31 FAILED
fcntl14    33  TFAIL  :  fcntl14.c:895: testcase:32 FAILED
fcntl14    34  TFAIL  :  fcntl14.c:895: testcase:33 FAILED
fcntl14    35  TFAIL  :  fcntl14.c:895: …
```
> Revert "vfs: record plock owner and use it instead of the one from FUSE (#2649)"

- cmd/flags.go
- cmd/mount.go
- pkg/chunk/cached_store.go
- pkg/chunk/disk_cache.go
- sdk/java/libjfs/main.go
- sdk/java/src/main/java/io/juicefs/JuiceFileSystemImpl.java
> cmd/mount: add `cache-scan-interval` option

- cmd/dump.go
- pkg/meta/interface.go
- pkg/meta/load_dump_test.go
- pkg/meta/redis.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
- pkg/vfs/backup.go
> cmd/dump: add `keep-secret-key` option

- pkg/chunk/cached_store.go
- pkg/chunk/disk_cache.go
> add upload delay metrics

- go.mod
- sdk/java/libjfs/bridge.go
Related to #2729 
The `golang/protobuf` is still required indirectly for `github.com/prometheus/client_golang` module.
> dependency: replace deprecated golang/protobuf

- pkg/vfs/vfs.go
- pkg/vfs/writer.go
Since a interrupted `close` will not be retried, and Linux kernel guarantee that the fd will be close even it's interrupted,  we should also do that, and try to not interrupt a `FLUSH` operation as much as possible. 
close #2744
> close fd before interrupted

- pkg/fuse/fuse.go
- pkg/vfs/internal.go
- pkg/vfs/vfs.go
close #2769 
close #2767 
`DeleteNotify` is not used for simplicity because the child inode can't be obtained directly.
See: https://github.com/juicedata/go-fuse/blob/master/fuse/server.go#L767
> vfs: invalid entry cache after `rmr`

- cmd/sync.go
Fix s3 path s3://test.127.0.0.1/123\123/ 
> sync: make the special char '\' behavior consistent with aws s3

- .github/actions/load/action.yml
- .github/workflows/load.yml
The test of loading metadata in badgerdb has failed for a long time . Details may refer to https://github.com/juicedata/juicefs/actions/runs/3095075995 .
> CI:rm load bagerdb test

- cmd/fsck.go
- pkg/meta/base.go
- pkg/meta/base_test.go
- pkg/meta/interface.go
- pkg/meta/redis.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
> cmd/fsck: support the nlink of the check and repair directory

- cmd/doctor.go
- cmd/doctor_test.go
- cmd/main.go
- pkg/utils/utils_darwin.go
- pkg/utils/utils_linux.go
- pkg/utils/utils_unix.go
- pkg/utils/utils_windows.go
The following file will be created:
It collects and displays info from multiple dimensions such as the running environment and system logs to report bugs, etc.
- **System info collection:** support collection of os, architecture, hardware, juicefs version, etc.
- **Syslog collection:** support automatic search for log location and filter logs according to the maximum number of records 
-  **Pprof metric collection:** Goroutine stack information, CPU performance statistics, memory allocation statistics, etc.
- **Mount point config collection:** support specifying mount point to obtain the config (filter sensitive info)
- **Mount command collection:** Collect juicefs mount commands and corresponding parameters
```
$ juicefs doctor /mnt/jfs
$ juicefs doctor --out-dir=/var/log /mnt/jfs
$ …
```
> cmd/doctor: doctor command supports collecting system, syslog and other info

- pkg/meta/tkv_badger.go
close #2808 
Badger hangs here:
```
1 @ 0x42796e 0xc277eb 0x11555fc 0x11555fd 0x1130749 0x224df63 0x620f0a 0x61e8fe 0x225ca6d 0x225a4ca 0x2283b8e 0x44cf87 0x47eb61
er/v3@v3.2103.2/txn.go:401
er/v3@v3.2103.2/txn.go:439
v2.4.0/command.go:163
v2.4.0/app.go:313
v2.4.0/app.go:224
```
> meta/badger: drop all keys directly to reset the database

- pkg/object/ks3.go
A private KS3 region may have different rule on endpoints, we can use `us-east-1` as the region for compatibility, which can also specified by AWS_REGION.
> support private region for KS3

- pkg/meta/tkv_fdb.go
close #2801
The read transaction for scanning is retried, which leads to the huge number of scanned keys. In fdb, there is a 5s limit for the read transaction.
refs: https://forums.foundationdb.org/t/large-range-scans-avoid-5s-limit/292
> meta/fdb: fix scan for many keys

- .github/workflows/gateway.yml
- .github/workflows/load.yml
- .github/workflows/pjdfstest.yml
- .github/workflows/rmfiles.yml
- .github/workflows/vdbench.yml
- .github/workflows/version_compatible_hypo.yml
tiup mirror is not stable,  it will failed to fetch some files, we add cache as a work round
https://github.com/juicedata/juicefs/actions/runs/3214726165/jobs/5255311152
Playground Bootstrapping...
Error: Playground bootstrapping failed: fetch /2551.pd.json from mirror(https://tiup-mirrors.pingcap.com/) failed: url https://tiup-mirrors.pingcap.com/2551.pd.json: not found
> CI: add cache for tiup.

- pkg/chunk/disk_cache.go
This is a very special case, which will totally disable building index for the cached keys. Users have to be make sure by themselves that there is at lease one client building this index, so that it can upload staging blocks (if `writeback` is enabled) and do the cleanup of cache directory.
> chunk/cache: disable refreshCacheKeys if interval < 0

- cmd/flags.go
- cmd/main.go
- cmd/mount.go
- docs/en/reference/command_reference.md
- docs/en/tutorials/aliyun.md
- docs/en/tutorials/aws.md
- docs/en/tutorials/digitalocean.md
- docs/en/tutorials/qcloud.md
- docs/zh_cn/reference/command_reference.md
- docs/zh_cn/tutorials/aliyun.md
- docs/zh_cn/tutorials/aws.md
- docs/zh_cn/tutorials/digitalocean.md
- docs/zh_cn/tutorials/qcloud.md
- go.mod
- go.sum
- pkg/vfs/vfs.go
> cmd/flags:remove gops agent

- pkg/object/tos.go
Using tos storage without beijing region, failed.
because :
close #2910
> obj/tos: fix TOS region parse bug

- pkg/meta/base.go
- pkg/meta/base_test.go
Mode of symlink is ignored in POSIX, but mac and bsd may check the read permission in readlink(). We follow the behavior in POSIX.
link: https://superuser.com/questions/303040/how-do-file-permissions-apply-to-symlinks
close #2915
> mode of symlink should be 0777

- cmd/main.go
- go.mod
- go.sum
- pkg/meta/sql.go
libraries  https://github.com/uber-go/automaxprocs
reference  https://github.com/pingcap/tidb/blob/be75669f68a2eda401b5ea239a9842fb0369f907/tools/check/ut.go#L37
> set the correct GOMAXPROCS value when it runs inside container

- pkg/object/object_storage_test.go
- pkg/object/obs.go
- pkg/object/oss.go
- pkg/object/redis.go
- pkg/object/swift.go
- pkg/object/tos.go
- pkg/object/upyun.go
- pkg/object/webdav.go
The `tls-insecure-skip-verify` no work on `gs` and `ibmcos`  also.
Since they are directly replacing http client, it is risky, so we should try to fix it when we have user feedback.
Redis
```
=== RUN   TestRedis
object_storage_test.go:95: PUT failed: context deadline exceeded
object_storage_test.go:82: delete failed: context deadline exceeded
--- FAIL: TestRedis (25.00s)
```
If redis is modified, the test will fail. Do not change it for now.
> object:fix tls-insecure-skip-verify does not effect on some object stores

- pkg/meta/base_test.go
- pkg/meta/sql.go
- pkg/meta/sql_lock.go
Do not use the number of affected rows returned by update to determine whether the update is successful
> meta/sql: do not use the number of affected rows returned by update

- pkg/meta/interface.go
> meta: remove meta password

- docs/en/introduction/comparison/juicefs_vs_cephfs.md
- docs/zh_cn/introduction/comparison/juicefs_vs_cephfs.md
community users sometimes tend to mistake "Volume" for Kubernetes PersistentVolume.
> explanation: a Volume is a JuiceFS Filesystem

- cmd/info.go
- pkg/meta/base_test.go
- pkg/meta/interface.go
- pkg/meta/redis_lock.go
- pkg/meta/sql_lock.go
- pkg/meta/tkv_lock.go
- pkg/meta/utils.go
- pkg/vfs/internal.go
- pkg/vfs/vfs_test.go
Close https://github.com/juicedata/juicefs/issues/2625
```bash
> ./juicefs info /mnt/jfs/example
/mnt/jfs/example :
inode: 55
files: 1
dirs: 0
length: 1.56 KiB (1596 Bytes)
size: 4.00 KiB (4096 Bytes)
path: /mnt/jfs/example
objects:
+------------+----------------------------+------+--------+--------+
| chunkIndex |         objectName         | size | offset | length |
+------------+----------------------------+------+--------+--------+
|          0 | myjfs/chunks/0/0/34_0_1596 | 1596 |      0 |   1596 |
+------------+----------------------------+------+--------+--------+
flocks:
+-----+---------------------+------+
| Sid |        Owner        | Type |
+-----+---------------------+------+
| 49  | 4848886172199279596 |    W |
+-----+---------------------+------+
```
> info: show locks of a certain file

- cmd/mount.go
- cmd/mount_test.go
> fix config equal when checking re-mount

- pkg/vfs/vfs.go
- pkg/vfs/vfs_test.go
If fd isn't opened for read or write, EBADF should be returned according to read(2) and write(2).
Signed-off-by: Eryu Guan <guaneryu@gmail.com>
> vfs: return EBADF if handle is not opened for read or write

- pkg/object/restful.go
The default buffer size of HTTP connection is 4KB, which is too small that lots of CPU spent in syscalls.
> object: increase buffer size from 4KB to 32KB

- cmd/status.go
In current implementation, `delfile` means files that were deleted delayed and could be cleaned immediately, while the `delslice` means slices that were swept into trash and should be cleaned according to `trash-days`.
In this PR, we renamed them more appropriately.
> status: rename DeletedSlice to TrashSlice and DeletedFile to PendingDeletedFile

- pkg/meta/base.go
- pkg/utils/general.go
Some periodically tasks sleep for a jittered duration and setIfSmall by a strict duration, it may cause some tasks delayed for an extra period.
> setIfSmall with smaller period than sleep

- sdk/java/src/main/java/io/juicefs/JuiceFileSystem.java
Close empties filesystem object when closing base filesystem to release thread resource and avoid thread leak.
> Close emptier filesystem to avoid thread leak

- pkg/meta/base.go
- pkg/meta/redis.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
Usually in the trash directory we can expect massive deletes, which may from background auto-cleanups, or from user called `juicefs rmr`/`rm -rf`. When it happens, and when the deletion is not fast enough, it should be better to keep files in trash rather than move them to `delFiles`.
> meta: force delete file data when cleaning up trash

- .github/workflows/codeql-analysis.yml
- .github/workflows/release.yml
- .github/workflows/sdktest.yml
- .github/workflows/tpcds.yml
AdoptOpenJDK has moved to the Eclipse Foundation and now distributes binaries under the new name "Eclipse Temurin"
> Migrate setup-java action to use Temurin

- docs/en/deployment/hadoop_java_sdk.md
- docs/en/getting-started/installation.md
- docs/en/guide/how_to_set_up_object_storage.md
- docs/zh_cn/getting-started/installation.md
- docs/zh_cn/guide/how_to_set_up_object_storage.md
- go.mod
- go.sum
We actually require go 1.18+ when using tikv client-go v2.0.2.
```
/var/lib/go/pkg/mod/github.com/tikv/client-go/v2@v2.0.2/internal/locate/sorted_btree.go:45:17: syntax error: unexpected [, expecting semicolon or newline or }
note: module requires Go 1.18
```
> deps: upgrade go version to 1.18

- pkg/object/object_storage_test.go
- pkg/object/s3.go
ref https://github.com/juicedata/juicefs/issues/3129
> object/OVH: support OVH region

- pkg/meta/tkv_badger.go
- pkg/meta/tkv_test.go
This method is used in `doCleanupDelayedSlices` to find delSliceKeys, with the filter `len(k) == 1+8+8`. So it is possible to get these keys that are actually undesired:
```
C...               counter
AiiiiiiiiD...      dentry
AiiiiiiiiX...      extented attribute
Diiiiiiiillllllll  delete inodes
```
Moreover, the length of value has to be a multiple of 12 to be processed, while the lengths for counter, dentry, delete inodes are fixed as 8, 9 and 8. Thus, the expected cleanup happens only when there is an xattr with key of length 7 and value of length that is a multiple of 12.
> meta/badger: fix the issue that scanKeysRange ignores begin/end

- pkg/chunk/cached_store.go
close #3143 
For simplicity mutex/atomic is not used to control the status of block uploading or not. It's still possible that a block is uploaded for more than one time, but the possibility and limit should be much smaller.
> chunk: fix the issue that staging file may be uploaded for many times

- cmd/mdtest.go
- cmd/objbench.go
- cmd/object.go
- cmd/object_test.go
- cmd/sync.go
- docs/en/guide/sync.md
- docs/zh_cn/guide/sync.md
- pkg/chunk/cached_store.go
- pkg/fs/fs.go
- pkg/object/file.go
- pkg/object/file_unix.go
- pkg/object/sftp.go
- pkg/sync/sync.go
- pkg/utils/utils.go
This PR allow us sync with JuiceFS without mount point:
```
juicefs sync   a/path/   jfs://meta-url/path/
```
Since meta-url is used as `host`, so it should be escaped twice, for example, sqlite3://a.db should be
```
juicefs sync   a/path/   jfs://sqlite3%253A%252F%252Fa.db/path/
```
To simplify this, we could use environment variable to pass meta-url, for example
```
myfs=sqlite3://a.db juicefs sync  a/path/   jfs://myfs/path/
```
> sync with juicefs without mount point

- pkg/vfs/handle.go
- pkg/vfs/internal.go
- pkg/vfs/vfs.go
When a response has more than 2MB, the first 1MB will be dropped before reading.
> fix reading large response from .control

- cmd/mount.go
- cmd/mount_test.go
- cmd/object.go
- pkg/fuse/fuse_test.go
- pkg/meta/base.go
- pkg/meta/base_test.go
- pkg/meta/interface.go
- pkg/vfs/vfs.go
- pkg/vfs/vfs_test.go
- sdk/java/libjfs/main.go
close #3175 
This PR also fix the issue that secret keys in baseMeta.fmt are removed for a short time [here](https://github.com/juicedata/juicefs/blob/v1.0.3/pkg/vfs/vfs.go#L942).
`meta.Load` can't be used for `.config` file to load the current format, because this method will update the one cached in baseMeta, which fails the detection of format change in `baseMeta.refresh`.
> vfs: change conf.Format from a pointer to a struct

- pkg/meta/utils.go
Now users can clean up the trash manually with command like `juicefs rmr /mnt/jfs/.trash/`.
> meta: skip trash directories when handling rmr

- .github/workflows/unittests.yml
- pkg/meta/base_test.go
- pkg/meta/info.go
- pkg/meta/redis.go
When the meta engine is keydb and storage provider is flash, do not adjust the maxMemoryPolicy.
```
redis-cli -h xxxxxxx  -p 6379
47.99.52.222:6379> info
redis_version:6.3.2
redis_git_sha1:d1dff8c2
redis_git_dirty:0
redis_build_id:ff5573d014b83759
redis_mode:standalone
os:Linux 4.18.0-348.7.1.el8_5.x86_64 x86_64
arch_bits:64
multiplexing_api:epoll
atomicvar_api:atomic-builtin
gcc_version:8.5.0
process_id:10515
process_supervised:no
run_id:cb07e0f23b039299373ff0264436b1847f473eaa
tcp_port:6379
server_time_usec:1675063191723253
uptime_in_seconds:203
uptime_in_days:0
hz:10
configured_hz:10
lru_clock:14118807
executable:/root/keydb-server
config_file:/root/keydb.conf
connected_clients:1
cluster_connections:0
maxclients:10000
client_recent_max_input_buffer:16
client_recent_max_output_buffer:0 …
```
> meta/redis: ignore check maxMemoryPolicy when meta engine is keydb

- .github/workflows/chaos.yml
The chaos-mesh/chaos-mesh-actions does not support setting config when installing Chaos Mesh, so we decide to install Chaos Mesh manually.
> install Chaos Mesh manually in the chaos test

- go.mod
- go.sum
- pkg/meta/dump.go
go-json is a faster replacement for "encoding/json", which can reduce the time of loading 1 million files from 9 seconds to 5 seconds. 
[1] github.com/goccy/go-json
> speedup dump and load with faster JSON library

- docs/en/reference/fuse_mount_options.md
- docs/zh_cn/reference/fuse_mount_options.md
this pr puts code references directly in docs, creating a precedent
> improve docs on allow_other

- cmd/dump_test.go
- cmd/integration_test.go
- cmd/mount_test.go
- go.mod
- go.sum
- pkg/meta/base_test.go
- pkg/meta/redis.go
- pkg/meta/redis_lock.go
- pkg/meta/utils.go
- pkg/object/object_storage_test.go
- pkg/object/redis.go
close https://github.com/juicedata/juicefs/issues/3223
> upgrade go-redis to support redis 7

- pkg/object/s3.go
问题：
aws-sdk-go 客户端上传文件到 s3 时，如果文件大于 2m 会自动加上请求头 Expect: '100-Continue'，但http规范 Expect 的值是 '100-continue' （大小写不一样）
如果请求发生重试，aws-sdk-go 会讲 Expect header 请求头用作签名，由于上面大小写问题，如果对象存储在验签时将 '100-continue' 作为 expect 的值，那么会导致签名校验失败
考虑上面原因 以及  juicefs 实际上传 s3 的都是分块文件比较下，所以这里将 expect 请求头禁用
> optionally turn off 'S3Disable100Continue' via url query parameter

- pkg/object/cos.go
- pkg/object/ibmcos.go
- pkg/object/ks3.go
- pkg/object/object_storage_test.go
- pkg/object/obs.go
- pkg/object/s3.go
| Object Storage | Protocol | Encode type config | Notes                                               |
| -------------- | -------- | ------------------ | --------------------------------------------------- |
| Azure          | XML      | NO                 | PUT failed:`The request URL is invalid`             |
| NOS            | XML      | NO                 |                                                     |
| COS            | XML      | YES                |                                                     |
| OBS            | XML      | YES                |                                                     |
| OSS            | XML      | YES                | listobject api  adds `EncodingType=url`  by default |
| S3             | XML      | YES                | …
> object: set encoding type when list object

- cmd/flags.go
- pkg/meta/base.go
- pkg/meta/openfile.go
In #3241 we introduce `open-cache-limit` flags but not use it, this PR will fix this mistake.
Moreover, this PR reduce the default limitation to zero, which means all unused files will eventually be cleaned, while used files are not affected.
> fix open cache: use configurable limitation

- go.mod
- go.sum
- pkg/sync/cluster.go
- pkg/sync/config.go
> sync env in juicefs cluster mode

- pkg/object/b2.go
ref #3272
```
=== RUN   TestB2
object_storage_test.go:87: PUT testEncodeFile failed: bad_request: File names must not contain unicode characters with codes less than 32
object_storage_test.go:340: b2://zhijian-dev/unit-test/ does not support multipart upload: not supported
object_storage_test.go:357: delete slash/ failed range_not_satisfiable: byte range bytes=0-1 for a file of length 0
object_storage_test.go:346: delete empty file failed: range_not_satisfiable: byte range bytes=0-1 for a file of length 0
--- PASS: TestB2 (124.78s)
```
> object/b2: fix b2 get empty file info

- docs/en/guide/how_to_set_up_object_storage.md
- docs/zh_cn/guide/how_to_set_up_object_storage.md
- pkg/object/gs.go
The bucket defaut region is US. 
ref: [LINK](https://pkg.go.dev/cloud.google.com/go/storage@v1.21.0#section-readme:~:text=//%20Location%20is%20the%20location%20of%20the%20bucket.%20It%20defaults%20to%20%22US%22.%0A%09Location%20string)
set a region manually
https://github.com/juicedata/juicefs/blob/5a35d18017e70afba7d476eaef46dcb59c08f152/pkg/object/gs.go#L177-L182
> object/gs: remove unnecessary region check

- pkg/object/ibmcos.go
- pkg/object/ks3.go
- pkg/object/qingstor.go
- pkg/object/s3.go
ref #3272
```
=== RUN   TestOOS
object_storage_test.go:73: Can't create bucket oos://zhijian-dev2/: please create bucket zhijian-dev2 manually
--- FAIL: TestOOS (0.29s)
```
Root cause：
> object/s3: set delimiter when it is not empty string

- pkg/meta/tkv.go
- pkg/meta/tkv_badger.go
- pkg/meta/tkv_etcd.go
- pkg/meta/tkv_fdb.go
- pkg/meta/tkv_mem.go
- pkg/meta/tkv_tikv.go
The GC cleans up old entries before 3 hours by default, and can be configured with the query string "gc-interval".
It should be disabled by setting "gc-interval=0" if there's already TiDB daemon or any other service that can trigger the GC deployed.
Refs: https://github.com/tikv/client-go/blob/master/examples/gcworker/gcworker.go
TODO: not fully tested.
> meta/tikv: add background GC worker for TiKV

- Makefile
Recent action shows that the time used for these tests are:
- test for all pkgs: 8 mins
- test for all cmds: 5 mins
- test for fdb: 40s
> CI: adjust the timeout for unittests

- pkg/meta/tkv_prefix.go
The current `gets` method of tkv_prefix changes the input key list, which may cause bugs if the caller reuses the key list.
> fix gets of tkv_prefix: not change input key list

- cmd/info.go
- pkg/meta/utils.go
- pkg/vfs/internal.go
Optimize `info -r` based on #3257
> info recursively support fast mode

- cmd/object.go
#3308 for backport 1.0
This pr is used to fix main branch testjfs error.
> object/jfs: jfs object list should return utils.ENOTSUP

- cmd/flags.go
- cmd/mount.go
- pkg/meta/config.go
- pkg/meta/tkv.go
- sdk/java/libjfs/main.go
- sdk/java/src/main/java/io/juicefs/JuiceFileSystemImpl.java
This makes #3285 configurable.
> meta/tkv: add an option to skip updating of nlink to reduce conflict

- pkg/meta/redis.go
- pkg/meta/utils.go
- fix a bug in `doSyncDirStat` of redis engine
- use `inodes` in dir stat of leaf dirs instead read them
> optimize fast summary

- pkg/meta/utils.go
Both of strict summary and fast summary should run `readdir` parallelly.
In engines that support high concurrency, such as TiKV, the parallel summary feature has become 20 times faster than before.
> support parallel directory summary

- cmd/info.go
- pkg/vfs/internal.go
- pkg/vfs/vfs_test.go
```bash
~/s/juicefs (info-process-bar)> ./juicefs info -r ~/mnt/jfs/
/home/hexi/mnt/jfs/: 490959                       163175.9/s   
/home/hexi/mnt/jfs/: 5.9 GiB (6347726848 Bytes)   2.0 GiB/s    
/home/hexi/mnt/jfs/:
inode: 1
files: 490959
dirs: 47203
length: 4.35 GiB (4671020626 Bytes)
size: 5.91 GiB (6347726848 Bytes)
path: /
```
> add progress bar for recursive info

- pkg/gateway/gateway.go
when s3fs identify whether the object is a folder, s3fs need to check a header "Content-Type: application/octet-stream" returned by HEAD Object rest api of juicefs s3 gateway
> fix s3fs folder

- pkg/object/mem.go
- pkg/object/object_storage_test.go
mem storage does not currently support delimiter, so some test codes cannot rely entirely on mem storage to mock
This PR adds delimiter support to mem storage
> Add delimiter for mem storage

- pkg/meta/dump.go
- pkg/meta/load_dump_test.go
- pkg/meta/metadata.sample
- pkg/meta/sql.go
At present, when meta dumps, there is no flags field, and this PR is used to dump the flags field.
> load and dump flags field

- pkg/fuse/fuse.go
In some environment, like cgroup2, or container without host cgroup fs, the warning of granting failure is annoying. As this case is easily reproducible and cannot be resolved by users, we should modify the log level to `debug`.
> adjust the log level of granting FUSE

- pkg/fs/fs.go
- pkg/meta/base.go
- pkg/meta/base_test.go
- pkg/meta/interface.go
- pkg/meta/utils.go
- pkg/vfs/internal.go
Improve the parallelism for summary when the structure of directories is not perfect.
> improve parallelism for summary

- cmd/mount_unix.go
1. juicefs csi driver has already add host /etc/updatedb.conf to mount pod, so we should also disable updatedb in k8s node,so i dropped os.Getpid() != 1
https://github.com/juicedata/juicefs-csi-driver/commit/77dad895a5100b4835982f86dd69d9d4fe026a8f
2. add flock to prevent multiple juicefs clients writing  updatedb.conf at the same time
> enhance disable updatedb to prevent concurrent modification

- pkg/chunk/cached_store.go
- pkg/chunk/disk_cache.go
- pkg/chunk/disk_cache_test.go
- pkg/chunk/mem_cache.go
- pkg/chunk/metrics.go
- pkg/chunk/utils_linux.go
1. enable self-contained metrics tracking for cacheManager, without relying on cachedStore for tracking
2. separating metrics from the cacheManager allows other object to use them.
3. remove the metrics "stageBlockDelay" from the cacheManager and place it in the cachedStore.
> Refactor metrics and  make the cacheManager more generic

- .github/workflows/bash/rm_list.sh
https://github.com/juicedata/juicefs/actions/runs/4652380547/jobs/8237811380#:~:text=sed%3A%20%2De%20expression%20%231%2C%20char,93%3A%20unknown%20option%20to%20%60s%27
> CI / ltptest：replace sed default delimiter

- pkg/vfs/handle.go
- pkg/vfs/vfs.go
> fix deadlock under concurrent truncate and releases

- README.md
The current provider is unstable:
Also, star-history has an elegant style:
> chore: replace star history chart with a stable source

- pkg/meta/base.go
- pkg/meta/base_test.go
- pkg/meta/interface.go
- pkg/sync/cluster.go
- pkg/utils/utils.go
> meta: add IPAddrs to the session info

- cmd/flags.go
- cmd/mount.go
- pkg/chunk/cached_store.go
- pkg/chunk/disk_cache.go
- pkg/chunk/mem_cache.go
- sdk/java/libjfs/main.go
- sdk/java/src/main/java/io/juicefs/JuiceFileSystemImpl.java
> cmd/mount: add an option `cache-eviction` to specify the policy

- pkg/gateway/gateway.go
When MultiBucket is false and bucketName is not equal to volumeName, return BucketNotFound instead of BucketNameInvalid
ref https://github.com/juicedata/jfs/issues/48
> gateway: fix gateway GetBucketInfo

- pkg/meta/base.go
- pkg/meta/redis.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
- pkg/vfs/internal.go
a label(method anme) is added to the `opDist` metrics collector of metadata operations at `pkg/meta/base.go:217`
so that we can clearly view the time duration and qps of different methods through monitoring, which is useful for troubleshooting problems and analyzing performance bottlenecks.
> add method tag for metadata access monitoring

- pkg/object/hdfs_kerberos.go
https://github.com/juicedata/juicefs/issues/3283
> Support keytab

- cmd/quota.go
Before:
```
+-------+---------+---------+------+--------+-------+---------+
|  Path |   Size  |   Used  | Use% | Inodes | IUsed |  IUse%  |
+-------+---------+---------+------+--------+-------+---------+
| /lani | 1.0 GiB | 2.8 GiB | 279% |    100 |   100 | 260024% |
+-------+---------+---------+------+--------+-------+---------+
```
Now:
```
+-------+---------+---------+------+--------+---------+---------+
|  Path |   Size  |   Used  | Use% | Inodes |  IUsed  |  IUse%  |
+-------+---------+---------+------+--------+---------+---------+
| /lani | 1.0 GiB | 2.8 GiB | 279% |    100 | 260,024 | 260024% |
+-------+---------+---------+------+--------+---------+---------+
```
> quota: fix wrong iused in output table

- pkg/object/gs.go
The `regional` is an illegal value, which seems to be a bug
> object/gs: remove storage class settings

- cmd/mdtest.go
- pkg/meta/base_test.go
- pkg/meta/benchmarks_test.go
- pkg/meta/interface.go
- pkg/meta/redis.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
- pkg/vfs/vfs_unix.go
- pkg/vfs/writer.go
Currently, it updates mtime as it updates the chunks in meta engine after data persisted. Actually, the mtime should be the time when data was written from kernel or application, not the time when data is persisted. 
Especially, a setattr could be called to update mtime before data is persisted, then the `mtime` could be lost (overwritten by data persistency).
close #3204
> fix update mtime before close

- cmd/sync.go
- pkg/sync/config.go
- pkg/sync/sync.go
> cmd/sync: support `existing` and `ignore-existing` flag

- cmd/flags.go
- cmd/mount.go
- docs/en/development/internals.md
- docs/en/reference/command_reference.md
- docs/zh_cn/development/internals.md
- docs/zh_cn/reference/command_reference.md
- pkg/meta/base.go
- pkg/meta/config.go
- pkg/meta/redis.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
- pkg/meta/utils.go
- pkg/meta/utils_test.go
- pkg/vfs/vfs_test.go
Currently juicefs doesn't update atime on access, so introduce --atime-mode option to select how to update atime. And support three modes:
- noatime: don't update atime
- relatime: update atime relative to motify or change time
- strictatime: always update atime
Fixes: #3240
Signed-off-by: Eryu Guan <eguan@linux.alibaba.com>
> vfs: introduce --atime-mode option to control atime update behavior

- cmd/mount_unix.go
- pkg/fuse/context.go
- pkg/fuse/fuse.go
- pkg/vfs/vfs.go
> support root squash

- cmd/config.go
- cmd/flags.go
- cmd/format.go
- cmd/gateway.go
- cmd/mount.go
- cmd/object.go
- pkg/chunk/cached_store.go
- pkg/chunk/chunk.go
- pkg/meta/config.go
- sdk/java/libjfs/main.go
> chunk/store: add default upload/download limit for each volume

- sdk/java/libjfs/main.go
- sdk/java/src/main/java/io/juicefs/JuiceFileSystemImpl.java
> sdk: support storage class flag for sdk

- pkg/vfs/vfs.go
Currently, the `vfs.Truncate` ignores error thrown by `meta.Truncate`
> fix vfs.Truncate: throw error from meta.Truncate

- cmd/umount.go
- pkg/chunk/disk_cache.go
WalkDir uses readdirplus() to fetch all the attributes of files in batch, which is faster than calling stat for each files.
> mount: speedup cache scan using WalkDir

- cmd/clone.go
supprot `juicefs clone /tmp/jfs/a /tmp/jfs/a1`
close #3663
> cmd/clone: fix prefix check

- pkg/meta/base_test.go
- test.sh
close #3264
We disabled the checking of sustained inodes in close session tests, because it was flaky before.
> fix sustained inodes test

- sdk/java/libjfs/guid.go
- sdk/java/libjfs/main.go
> sdk/java: limit generated uid/gid to int32 for sql engines

- pkg/meta/sql.go
When MySQL is used as meta engine, the lock on edge is a gap lock, which can overlap with other directories, can cause deadlock.
Since we always lock the parent directory, so the lock for edge is useless, remove them to avoid deadlock.
Some lock on child node is also removed, since the update of some column is atomic or already protected by the lock of parent dir.
There is still a chance to deadlock in rename, because we have to lock the target sub-directory (for overwrite), which could be locked first by other rename. We left this for database to detect it and retry the transactions.
close #3665
> meta/sql: remove lock on edge to avoid deadlock

- pkg/meta/tkv_fdb_test.go
in #3678, most of engine test use `testConfig()` instead of `DefaultConf` expect for `TestFdbClient`
> fix TestFdbClient: replace DefaultConf with testConfig

- docs/en/guide/how_to_set_up_object_storage.md
- docs/zh_cn/guide/how_to_set_up_object_storage.md
- pkg/object/hdfs.go
- pkg/object/object_storage_test.go
```  <property>
<name>dfs.namenode.rpc-address.ns.namenode157</name>
<value>hadoop02:8020</value>
</property>
<property>
<name>dfs.ha.namenodes.ns</name>
<value>namenode108,namenode157</value>
</property>
```
> Support hdfs://namenode:port for hdfs object storage

- cmd/sync.go
- pkg/object/hdfs.go
The path of HDFS uri is already used, we should not add a prefix over it.
The bug is introduced by #3528
> cmd/sync: fix duplicated path in HDFS

- pkg/meta/redis.go
- pkg/meta/sql.go
close #3725
we introduce a bug in #3715, which causes all dir stats will be updated by single record.
> meta/sql: fix update dir stats by fault

- cmd/flags.go
- cmd/main.go
Sometimes (in tests) we want to set log level to `error` or even higher.
> cmd: add `log-level` option to customize the log level

- cmd/info.go
- pkg/vfs/internal.go
- pkg/vfs/vfs_test.go
Currently, our `info` v2 protocol relies on the scan period: if the mount process sends all progress data and results in single period (300ms), the command process could not parse the response, which causes #3726.
In #3381, we introduce the `meta.CDATA` header to ensure the `summary` protocol stable, and this PR does the same thing.
> internal/info: use CDATA header to send back data

- pkg/meta/sql.go
in #3654 we introduce three new fields for the `node` table, so the numbers of placeholders may exceed the limitation of SQL engine like https://github.com/juicedata/juicefs/actions/runs/5049460379/jobs/9058941017
> load/sql: update max fields count to reduce max batch size

- pkg/fs/fs.go
When the path starts with `/`, it will check permission for root.
We assume root is accessible for everyone.
> sdk: skip permission check for root

- pkg/object/object_storage.go
- pkg/utils/cond.go
- pkg/utils/cond_test.go
There is a chance that Wait() may miss the signal from Signal(), then deadlock, we should always use WaitWithTimeout().
```
G1                        G2
read is false
Unlock
Lock
ready = true
select ch {
default:
}
<- ch (deadlock)
```
> sync: wait() may miss signal then cause deadlock

- sdk/java/src/main/java/io/juicefs/JuiceFileSystemImpl.java
`soVer = 8` is used for v1.0.4.
> hadoop: change back the so version

- README.md
Redis was almost exposed as the only service in some paragraphs, rewrite to be more "compatible" with other metadata engines.
Also removed from Roadmap parapgraph already implemented features.
> doc: rewrite ReadMe file to expose other engines than Redis

- pkg/meta/base.go
> fsck: ignore dir stats when it's disabled

- pkg/meta/sql.go
Add index to column refs in sliceRef table because the doCleanupSlices function query statement executes too slowly when there are too many rows in the table.
> Update sql.go, Add index to column refs in sliceRef

- pkg/vfs/internal.go
Fix the error of the name change for the 'juicefs_object_request_data_bytes' metric.
ref #3501
> metrics: fix the bug of `juicefs_object_request_data_bytes` name 

- .github/scripts/command/info.sh
- .github/workflows/command.yml
- cmd/info.go
- cmd/warmup.go
> cmd/info: fix the problem of reading progress when the data is very large

- pkg/object/ceph.go
close #3836 
```
// use ctx.WriteFull(key, data)
for i := 85; i < 95; i++ {
body := make([]byte, i<<20)
rand.Read(body)
err = s.Put("test", bytes.NewReader(body))
if err != nil {
t.Errorf("PUT %dM failed: %s", i, err.Error())
} else {
t.Logf("PUT %dM success", i)
}
}
```
> object/ceph: fix ceph range get and get no-exist

- cmd/restore.go
- pkg/fs/fs.go
- pkg/meta/base.go
- pkg/meta/base_test.go
- pkg/meta/interface.go
- pkg/meta/redis.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
There is a race that a client may create a file into a directory which is already moved into trash by another client, and the creation succeed but user can't access the file from given path. The file will be eventually removed from trash.
close #2774 #3737
> disallow create files in trash directory

- pkg/object/hdfs_kerberos.go
load decodedKeytab directly in memory to avoid possible multi clients conflicts
> refactor hdfs kerberos keytab load

- pkg/meta/redis.go
Apache KVRocks supports the needed Redis commands (see https://kvrocks.apache.org/docs/supported-commands) to be a backend for JuiceFS, however because it uses RocksDB, there is no max_memory policy, but JuiceFS will try and set this, resulting in an non-critical error at startup.
> dont try set maxmemory_policy if setting does not exist

- sdk/java/src/main/java/io/juicefs/JuiceFileSystemImpl.java
on Windows platform, Paths.get(jarPath) will get InvalidPathException like "java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Program Files/xxx"，change to use Paths.get(location.toURI())
> fix java.nio.file.InvalidPathException when loadLibrary on Windows platform

- .github/workflows/load.yml
because we use secret when save benchmark, the pr from other repos will fail on empty secrets.
> CI: run load test only for juicedata/juicefs repo

- cmd/sync.go
- pkg/sync/cluster.go
- pkg/sync/cluster_test.go
- pkg/sync/config.go
- pkg/sync/sync.go
The `sync` subcommand allows customization of the IP address and port that the management node listens on.
> cmd/sync: allows customization of the IP address and port that the management node listens on

- go.mod
- go.sum
godeltaprof v0.1.0 building fails on golang 1.21:
```bash
(main)> make
go version
go version go1.21.0 linux/amd64
go build -ldflags="-s -w -X github.com/juicedata/juicefs/pkg/version.revision=d3bbc0ca -X github.com/juicedata/juicefs/pkg/version.revisionDate=2023-08-11"  -o juicefs .
../../go/pkg/mod/github.com/pyroscope-io/godeltaprof@v0.1.0/internal/pprof/delta_mutex.go:25:20: undefined: runtime_cyclesPerSecond
../../go/pkg/mod/github.com/pyroscope-io/godeltaprof@v0.1.0/internal/pprof/proto.go:400:8: undefined: runtime_expandFinalInlineFrame
make: *** [Makefile:24: juicefs] Error 1
```
They fix it in v0.1.2
> upgrade godeltaprof to v0.1.2

- Makefile
- sdk/java/libjfs/Makefile
Author time might be an old timestamp, commit time is always monotonically increasing and useful to identify a revision.
> Makefile: use commit time for revision date

- .github/workflows/verify.yml
- cmd/bench.go
- cmd/format.go
- cmd/mdtest.go
- cmd/objbench.go
- pkg/chunk/disk_cache_test.go
- pkg/object/object_storage_test.go
- pkg/object/restful.go
- pkg/sync/download_test.go
Lint error for Go 1.20:
```
Error: SA1019: rand.Seed has been deprecated since Go 1.20 and an alternative has been available since Go 1.0: Programs that call Seed and then expect a specific sequence of results from the global random source (using functions such as Int) can be broken when a dependency changes how much it consumes from the global random source. To avoid such breakages, programs that need a specific result sequence should use NewRand(NewSource(seed)) to obtain a random generator that other packages cannot access.  (staticcheck)
Error: SA1019: rand.Read has been deprecated since Go 1.20 because it shouldn't be used: For almost all use cases, crypto/rand.Read is more appropriate.  (staticcheck)
```
> use crypto/rand.Read, and remove math/rand.Seed

- pkg/object/file.go
- pkg/object/gluster.go
Change back to use Readdir() instead of ReadDir(), because List() needs FileInfo, Readdir() issue lstat() during the loop (cache hit), but ReadDir() will not, so we will issue lstat() after that, (cache miss).  When list a huge directory, Readdir() can be much faster than ReadDir() + many lstats().
> object/file: use Readdir to lookup FileInfo faster

- pkg/object/gluster.go
Try using `JFS_GLUSTER_LOG_PATH=/dev/stdout` or `JFS_GLUSTER_LOG_PATH=/dev/stderr` to redirect the log within k8s.
> object/gluster: allow customizing log path

- sdk/java/src/main/java/io/juicefs/bench/TestDFSIO.java
When testing I/O throughput by local. I found the result pring should be MB/sec.
> sdk/java: Fix print result inaccurate when TestDFSIO by local

- .github/scripts/db.py
when PR from external repos, the secret MYSQL_PASSWORD will not set, in this case , we do not save the data to db.
> CI: don't save benchmark when mysql password is empty.

- pkg/gateway/gateway.go
Since the gateway is not set to enable compression, returning true or false will ultimately not compress. This is the expected behavior, but returning false direct here would be clearer.
> cmd/gateway: disable compression

- .github/scripts/command/sync_minio.sh
- pkg/fs/fs.go
ref https://github.com/juicedata/juicefs/pull/3896
> cmd/gateway: judge loop symbolic links rather than hard-code deep limit

- cmd/flags.go
- cmd/main.go
- docs/en/reference/command_reference.md
- docs/zh_cn/reference/command_reference.md
- pkg/utils/logger.go
- pkg/utils/logger_test.go
So that we could filter logs from the same juicefs instance. And use "--log-id random" to generate random uuid as log id.
> utils/logger: support append user specified ID in log

- integration/s3gateway_test.sh
- pkg/gateway/gateway.go
Create the parent directory of the target on demand when copying the object
> cmd/gateway: create dst dir path when copy-object

- pkg/meta/base.go
- pkg/meta/interface.go
Mount time might be useful when debugging issues.
> meta: add mount time in session info

- cmd/restore.go
- pkg/meta/base.go
close #4044
- restore with session
- flush quotas before closing session
> fix restore: count dir stats and quota

- cmd/mdtest.go
- cmd/mount.go
- cmd/mount_test.go
- cmd/sync.go
- go.mod
- go.sum
- pkg/metric/metrics.go
- pkg/sync/config.go
- pkg/sync/sync.go
- sdk/java/libjfs/main.go
depend on https://github.com/juicedata/mpb/pull/2
close #4109
p8s http://127.0.0.1:9567/metrics
```
juicefs_sync_checked{cmd="sync",pid="18939"} 1008
juicefs_sync_checked_bytes{cmd="sync",pid="18939"} 3.262846983e+09
juicefs_sync_copied{cmd="sync",pid="18939"} 0
juicefs_sync_copied_bytes{cmd="sync",pid="18939"} 0
juicefs_sync_cpu_usage{cmd="sync",pid="18939"} 10.618006000000001
juicefs_sync_failed{cmd="sync",pid="18939"} 0
juicefs_sync_go_build_info{checksum="",cmd="sync",path="github.com/juicedata/juicefs",pid="18939",version="(devel)"} 1
juicefs_sync_go_gc_duration_seconds{cmd="sync",pid="18939",quantile="0"} 7.6753e-05
juicefs_sync_go_gc_duration_seconds{cmd="sync",pid="18939",quantile="0.25"} 7.9967e-05
juicefs_sync_go_gc_duration_seconds{cmd="sync",pid="18939",quantile="0.5"} …
```
> cmd/sync: add p8s metrics for sync command

- pkg/meta/sql.go
The current issue is that when there's an error in deleting dirstats, the rmdir operation still proceeds (the transaction is successfully committed). However, the next time a mkdir operation with the same name is attempted, it will check dirstats. If it already exists, an error is reported, making it impossible to make a directory with the same name. 
There are two options to fix this issue: 
1) Return the rmdir error. This will trigger a retry to execute rmdir later.
2) Ignore existing dirstats during mkdir.
For option2, I think it requires the logic to check if the dirStats table is the only one not removed by the previous transaction, if so, overwrite the old one during mkdir, if not, report EEXIST error. This requires far more changes than option1, so option1 is preferred here.
> Return remove dir error of table dirStats to trigger retry.

- pkg/sync/sync.go
close #4108
limit the maximum memory size for multiple upload is 32MB times the number of threads
> cmd/sync: limit the maximum memory size for multiple upload

- cmd/debug.go
- cmd/gateway.go
- cmd/mount.go
- cmd/mount_unix.go
- cmd/mount_windows.go
- cmd/webdav.go
> cmd/gateway&webdav: gateways and webdav support daemon running

- cmd/sync.go
- pkg/object/nfs.go
- pkg/sync/sync.go
> sync: fix nfs path and list

- cmd/objbench.go
1. The user system for Windows is different from linux
> 2023/11/08 23:23:57.612797 juicefs[3440] &lt;FATAL&gt;: lookup nobody user failed: No mapping between account names and security IDs was done. [objbench.go:172]
2. Cannot perform rename and delete operations on files that are not closed under window
> golang.org/x/sys/windows.ERROR_SHARING_VIOLATION (32)
3. Chmod does not work in Windows,  may be use https://pkg.go.dev/golang.org/x/sys/windows or https://github.com/hectane/go-acl
```
PS C:\Users\15810\GolandProjects\juicefs> .\juicefs.exe objbench C:\Users\15810\Desktop\tmp\d1\
Start Functional Testing ...
+----------+---------------------+--------------------------------------------------+
| CATEGORY |         TEST        |                      RESULT                      | …
```
> cmd/objbench: fix the objbench command run on Windows

- cmd/config_test.go
- pkg/object/filesystem_test.go
To avoid test failure from the second run, as the test bucket path is not empty, i.e.
<FATAL>: Storage file:///tmp/testBucket/test/ is not empty; please clean it up or pick another volume name
> CI: remove tmp test bucket path before test

- cmd/object.go
- pkg/fs/fs.go
- pkg/object/file.go
- pkg/object/file_unix.go
- pkg/object/file_windows.go
- pkg/sync/sync.go
> fix sync: copying times, owner and mode not follow link

- pkg/meta/base_test.go
- pkg/meta/redis_lock.go
- pkg/meta/sql_lock.go
- pkg/meta/tkv_lock.go
flock should convert current exclusive lock into a shared lock.
> convert current write lock into read lock

- .github/scripts/chaos/workflow.yaml
Delaying each io operation for 1s is almost unacceptable for minio, which cause [chaos-test](https://github.com/juicedata/juicefs/actions/workflows/chaos.yml ) fails frequently.
> chaos-test: reduce io-delay of minio to 50ms

- cmd/object.go
- cmd/object_test.go
- pkg/object/file.go
- pkg/object/filesystem_test.go
- pkg/object/hdfs.go
- pkg/object/nfs.go
- pkg/object/sftp.go
This PR also fixed a but that may leak temporary file when Create() returns an error but the file is created.
close #4212
> sync: fix temporary name when create a file

- pkg/object/ceph.go
This PR will call stat from in parallel to speedup List.
> object/ceph: Speedup list for ceph

- cmd/mount_unix.go
> cmd/mount: add `JFS_MOUNT_TIMEOUT` env for adjust check mountpoint  timeout

- pkg/object/checksum.go
- pkg/object/checksum_test.go
- pkg/object/cos.go
- pkg/object/oss.go
- pkg/object/s3.go
> object: fix verify checksum 

- docs/zh_cn/reference/how_to_set_up_metadata_engine.md
It is mentioned in Slack that if the mysql dsn does not set timeout, in the scenario where the juicefs to mysql network is blocked, it will be blocked for longer than expected, such as 2h.
slack link: https://juicefs.slack.com/archives/C01HXAD7LDQ/p1699360126783569
We recommend adding a guide for timeout parameters in the documentation to ensure clarity regarding this situation.
> Docs: add timeout parameter for MySQL dsn

- .github/scripts/setup-hdfs.sh
- pkg/winfsp/winfs.go
1. fix windows fs truncate return syscall.EBADF
2. fix setup-hdfs.sh: upgrate hdfs verion from 2.10.1 to 2.10.2, because hadoop-2.10.1.tar.gz is not available in https://dlcdn.apache.org/hadoop/common
BTW, It’s difficult to get a PR passed through all checks. I pushed my branch without any changes for 6 times to get my PR passed through all checks.
> fix windows fs truncate return syscall.EBADF

- pkg/meta/redis.go
Transactional behavior is needed, so use TxPipelined()
> meta/redis: use TxPipelined() instead of Pipelined()

- pkg/chunk/cached_store_test.go
When testing in constrained env with few space in /tmp, TestFillCache() may fail due to not caching all chunks, as free space ratio is less than 10% and some chunks are evicted.
So lower FreeSpace ratio in the test to avoid its impact as much as possible.
> chunk: lower FreeSpace config in TestFillCache

- pkg/meta/redis.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
> meta: trigger compaction more aggresively when there are too many slices

- cmd/flags.go
- cmd/gateway.go
- cmd/mdtest.go
- cmd/mount.go
- cmd/mount_test.go
- docs/en/deployment/hadoop_java_sdk.md
- docs/en/reference/command_reference.md
- docs/zh_cn/deployment/hadoop_java_sdk.md
- docs/zh_cn/reference/command_reference.md
- sdk/java/libjfs/main.go
- sdk/java/src/main/java/io/juicefs/JuiceFileSystemImpl.java
close #4245
Does some defensive programming (check the format of parameter) needed ?
> add `push-labels` option for java sdk and add `--custom-lables` option for mount

- .gitignore
- cmd/compact_test.go
- cmd/compact_unix.go
- cmd/compact_windows.go
- cmd/main.go
- go.mod
- go.sum
- pkg/meta/base.go
- pkg/meta/context.go
- pkg/meta/interface.go
- pkg/vfs/internal.go
Support triggering compaction of all files under a given directory #4303
> cmd/compact: add new compact cmd, used for specific path

- pkg/sync/sync.go
- pkg/utils/alloc.go
Scanned objects: 178828/189169 [==========================================================>---]  0.5/s ETA: 6h9m12s
Skipped objects: 137390                            0.4/s                                       ⠸
Pending objects: 10240                             0.0/s                                       ⠸
Copied objects: 41435                             0.1/s                                       ⠸
Copied bytes: 80.9 TiB (88996429305820 Bytes)   221.6 MiB/s                                 ⠸
Failed objects: 3                                 0.0/s                                       ⠸
panic: runtime error: index out of range [31] with length 30
goroutine 65784726 [running]:
[github.com/juicedata/juicefs/pkg/utils.Alloc(0xc06722b4c8?)](http://github.com/juicedata/juicefs/pkg/utils.Alloc …
> cmd/sync: increase memory pool for sync oversize files(part > 1G)

- .github/workflows/mutate-test.yml
- cmd/objbench.go
- pkg/object/object_storage_test.go
> test: improve special character test case

- .github/scripts/chaos/juicefs-csi-driver.Dockerfile
- .github/workflows/verify.yml
- docs/en/deployment/hadoop_java_sdk.md
- docs/en/getting-started/installation.md
- docs/en/reference/how_to_set_up_object_storage.md
- docs/zh_cn/getting-started/installation.md
- docs/zh_cn/reference/how_to_set_up_object_storage.md
- go.mod
> require Go 1.20+ to build

- .github/workflows/verify.yml
- cmd/main.go
- go.mod
- go.sum
* `github.com/pyroscope-io/client` was moved to `github.com/grafana/pyroscope-go`, see redirect of https://github.com/pyroscope-io/client
* Go 1.22 support was added in `godeltaprof` 0.1.6 via https://github.com/grafana/pyroscope-go/pull/55
* Fixes #4339
> Bump pyroscope client and godeltaprof to support Go 1.22

- pkg/meta/base_test.go
- pkg/meta/redis.go
- pkg/meta/slice.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
close #4347 
Handle cases like:
```
|___1___|
|___|
|___|             ==>
|___|
|____0____|              |____0____|___1___|
// the slice with ID = 1 will be skipped
```
> meta: fix protection check for compaction

- cmd/compact_test.go
> fix: compact test in order

- pkg/meta/redis.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
fix: reset slices in meta.Read when chunk not exists
> fix: reset slices in meta.Read when chunk not exists

- cmd/warmup.go
- pkg/chunk/cached_store.go
- pkg/chunk/cached_store_test.go
- pkg/chunk/chunk.go
- pkg/vfs/fill.go
- pkg/vfs/fill_test.go
- pkg/vfs/internal.go
- pkg/vfs/vfs_test.go
> Feat: cmd-warmup add option "check" and "evict"

- pkg/meta/utils.go
1. change: add cancel when failed
2. hint: does not use wg.Wait because the function call stack is too deep and mayebe block somewhere. It involves context handling in many other functions, we will strengthen the context handling of other interfaces in the future.
> enhance: cancel context when emptyDir failed

- pkg/fs/fs.go
- pkg/meta/base_test.go
- pkg/meta/interface.go
- pkg/meta/random_test.go
- pkg/meta/redis.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
- pkg/vfs/vfs.go
- pkg/vfs/writer.go
> vfs: fix file length after fallocate & copyfilerange

- pkg/chunk/disk_cache.go
disk cache cleanup expire cache items should skip staging cache items which size is <0, otherwise it will add wrong cache.used
> fix: cleanup cache expire skip staging

- cmd/config.go
- cmd/format.go
- cmd/mount_test.go
- pkg/fuse/fuse.go
- pkg/meta/config.go
- pkg/meta/metadata-sub.sample
- pkg/meta/metadata.sample
- pkg/version/version.go
#4409 
- add enable-acl flag
- add version checking
> feat/acl: add enable-acl flag and version checking

- pkg/acl/acl.go
- pkg/acl/cache.go
- pkg/acl/cache_test.go
#4409
add acl rule and acl cache which will cache all acl rules
> feat/acl: add acl rule and cache

- pkg/sync/sync.go
- pkg/sync/sync_test.go
> sync: fix filter with two star

- cmd/mount_unix.go
- cmd/passfd.go
> mount: fix upgrade with xattr

- cmd/mount.go
- pkg/vfs/backup.go
> metrics: export meta backup metrics

- pkg/meta/dump.go
- pkg/meta/redis.go
> dump: reduce memory when dump large directories from redis

- go.mod
- go.sum
- pkg/acl/cache.go
- pkg/acl/cache_test.go
- pkg/fuse/fuse.go
- pkg/fuse/fuse_darwin.go
- pkg/fuse/fuse_linux.go
- pkg/meta/base.go
- pkg/meta/base_test.go
- pkg/meta/interface.go
- pkg/meta/redis.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
- pkg/meta/utils.go
- pkg/vfs/vfs.go
1. add interface GetFacl and SetFacl
2. implement ACL support for three engines: TKV, Redis, and SQL.
- sync mode and acl
- add new acl
- inherit from default acl
3. vfs interface support
> feat/acl: add acl support

- pkg/acl/cache.go
- pkg/fuse/fuse.go
- pkg/meta/base.go
- pkg/meta/dump.go
- pkg/meta/metadata-sub.sample
- pkg/meta/metadata.sample
- pkg/meta/redis.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
> feat/acl: support dump and load meta

- pkg/acl/acl.go
- pkg/fuse/fuse.go
- pkg/meta/base.go
- pkg/meta/base_test.go
- pkg/meta/redis.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
> feat: support juicefs acl check

- pkg/meta/redis.go
> fix: redis convert acl to []byte

- pkg/meta/sql.go
close #4494 
The current behavior with possible deadlock is not a bug (see: https://bugs.mysql.com/bug.php?id=96748). However, try insertion first seems do omit the deadlock warning.
> meta/sql: use upsert in Write() to avoid possible deadlock

- pkg/fuse/fuse_test.go
- pkg/vfs/handle.go
- pkg/vfs/internal.go
- pkg/vfs/vfs.go
- pkg/vfs/vfs_test.go
> mount: recovery read only file handler

- cmd/main.go
- pkg/object/object_storage.go
1MiB io-size increases throughput by ~20%
> cmd/sync: use larger io-size when writing to backends

- go.mod
- go.sum
- pkg/chunk/cached_store.go
- pkg/chunk/disk_cache.go
- pkg/chunk/disk_cache_test.go
- pkg/chunk/mem_cache.go
- pkg/chunk/utils_unix.go
- pkg/chunk/utils_unix_test.go
- pkg/chunk/utils_windows.go
> feat: disk cache switch to consistent hash and add bad disk detection

- pkg/meta/base.go
- pkg/meta/redis.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
> fix/acl: clear sgid in some cases

- pkg/vfs/accesslog.go
- pkg/vfs/accesslog_test.go
- pkg/vfs/vfs.go
- pkg/vfs/vfs_unix.go
Add `method` label to metric `fuse_ops_durations_histogram_seconds`, keeping in step with `meta_ops_durations_histogram_seconds`.
Sometimes, we see count of `fuse_ops` has increased but not `meta_ops`. Given the current monitoring, we cannot determine what caused such phenomenon.
> Fuse ops metric supports showing method label

- pkg/vfs/internal.go
A patch for #4554 .
Without it there will be multiple lines for fuse ops metrics:
```
juicefs_fuse_ops_durations_histogram_seconds_total 101
juicefs_fuse_ops_durations_histogram_seconds_sum 1.305467913
juicefs_fuse_ops_durations_histogram_seconds_total 205
juicefs_fuse_ops_durations_histogram_seconds_sum 1.6931756689999993
juicefs_fuse_ops_durations_histogram_seconds_total 211
juicefs_fuse_ops_durations_histogram_seconds_sum 0.05859979800000001
juicefs_fuse_ops_durations_histogram_seconds_total 315
juicefs_fuse_ops_durations_histogram_seconds_sum 0.09348225000000002
```
> vfs: merge fuse ops metrics in .stats

- pkg/meta/tkv.go
If the trash node does not exist, give it a default value.
> assign default values to the trash node

- .github/scripts/prepare_db.sh
- pkg/meta/base.go
- pkg/meta/base_test.go
- pkg/meta/redis.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
fix #4536 
Known limits for value:
- MySQL: 64 KiB
- FoundationDB: 100 KB
- etcd: 1MiB
> meta: force compaction when there's too many slices in one chunk

- cmd/mount.go
- docs/en/grafana_template.json
- docs/en/grafana_template_k8s.json
- pkg/chunk/cached_store.go
- pkg/meta/base.go
- pkg/vfs/vfs.go
1. Export version into metrics label - useful when we are upgrading a cluster of hundreds of nodes, it provides an overview of upgrade process.
3. Export the uploading objects number - so we will know whether we are running out of `max-uploads`.
> Two minor metrics updates

- pkg/meta/base.go
- pkg/meta/base_test.go
- pkg/meta/quota.go
`df` may display negative value:
```
$ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/vda2       178G   44G  127G  26% /
JuiceFS:test    1.0P -100K  1.0P   0% /mnt/jfs
```
> meta: fix negative values in quota before used in statfs

- cmd/flags.go
- cmd/flags_test.go
Allow user to specify duration like `--cache-expire=1d`
> Support parsing "1d" duration

- pkg/sync/sync.go
> sync: skip listing on dst in force mode

- pkg/object/s3.go
Add option to disable md5 and crc verification when s3 compatible storage does not support them, which improves throughput by 20% and cut cpu usage by 70%
> Add option to disable md5 and crc verification when s3 compatible storage does not support them

- pkg/object/ceph.go
Limitations:
1. Values in both `ceph.conf` and cluster internal configurations (`ceph config`) will be overwritten. To adjust these options we have to set the corresponding envs
2. Only ONE active client can have the admin socket enabled. A `pid` field may be added into the path later if the connection can be closed gracefully.
> object/ceph: set default path for admin socket and log file

- cmd/format.go
- pkg/chunk/cached_store.go
- pkg/chunk/disk_cache.go
- pkg/meta/base.go
- pkg/object/azure.go
- pkg/object/bos.go
- pkg/object/cos.go
- pkg/object/dragonfly.go
- pkg/object/gs.go
- pkg/object/ibmcos.go
- pkg/object/ks3.go
- pkg/object/object_storage.go
- pkg/object/object_storage_test.go
- pkg/object/obs.go
- pkg/object/oss.go
- pkg/object/prefix.go
- pkg/object/qingstor.go
- pkg/object/s3.go
- pkg/object/sharding.go
- pkg/object/storage_class.go
- pkg/object/tos.go
- pkg/vfs/reader.go
Some object storage supports configuring lifecycles to automatically move objects into different storage classes. This label allows us to observe the throughput and latency of different storage classes.
> Expose the storage-class to the metrics of throughput and latency

- pkg/chunk/cached_store.go
- pkg/vfs/reader.go
When s3 storage is unhealthy, we see lots of failed read requests for the same key - half of them are triggered by prefetch. Actually only a successful partial read needs a prefetch.
> Only prefetch on successful partial read

- cmd/flags.go
> cmd: add unit for all time options

- pkg/meta/base_test.go
- pkg/meta/random_test.go
- pkg/meta/redis.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
> fix: permission mode of new node with minimum default acl

- cmd/mount_unix.go
Sometimes on startup, we see errors `fuse transport endpoint is not connected` when determining if we can gracefully shutdown the old mountpoint. This causes the current mount process exits with 1, which may results in an infinite restart.
> Donot fatal at startup, when failed to read .config file

- pkg/utils/utils_unix.go
- pkg/utils/utils_windows.go
- pkg/vfs/accesslog.go
- pkg/vfs/accesslog_test.go
- pkg/vfs/internal.go
- pkg/vfs/vfs.go
- pkg/vfs/vfs_test.go
- pkg/vfs/vfs_unix.go
Senario:
1. Better understanding users' pattern
2. Set up alarm rules on abnormal error rate
> Add errno label to fuse ops metric

- go.mod
- go.sum
- pkg/gateway/gateway.go
> delete bucket metadata when deleting a bucket.

- pkg/chunk/cached_store.go
- pkg/vfs/writer.go
When user opens lots of files for write, we will see spikes in write buffer usage, which may cause write stall if we don't have large enough write buffer limit.
By preparing slice id eagerly, we now have a more predictable write buffer usage.
> Prepare slice id eagerly to have a stable and predictable write buffer usage

- pkg/metric/metrics.go
- pkg/vfs/backup.go
It turns out the backup process always runs in fast mode. Which causes OOM
> Fix: backup always runs in fast mode, consuming more than 5G memory on a large volume

- cmd/sync.go
> cmd/sync: support using NFS path that is not directly exported

- pkg/vfs/writer.go
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1ed3c80]
goroutine 3559509 [running]:
github.com/juicedata/juicefs/pkg/chunk.(*wSlice).ID(0x10100c00f1f1c20?)
/home/miaochangxin/workspace/juicefs/pkg/chunk/cached_store.go:472
github.com/juicedata/juicefs/pkg/vfs.(*sliceWriter).prepareID(0xc00f330680, {0x3fbda18, 0xc0110dcf00}, 0x0)
/home/miaochangxin/workspace/juicefs/pkg/vfs/writer.go:91 +0x282
created by github.com/juicedata/juicefs/pkg/vfs.(*sliceWriter).write in goroutine 1
/home/miaochangxin/workspace/juicefs/pkg/vfs/writer.go:139 +0x149
```
> Fix panic when reading and writing s.writer concurrently

- pkg/vfs/writer.go
> prepare slice id to flush data earlier

- pkg/meta/redis.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
- pkg/vfs/vfs.go
- pkg/vfs/vfs_test.go
Reverts juicedata/juicefs#4713
After test in linux, copy_file_range under these conditions will return 0, and dst file's length will set to 0.
- len = 0 
- offset exceed src file length
> Revert "fix: file length after CopyFileRange and add checks for meta CopyFileRange"

- pkg/object/object_storage_test.go
- pkg/object/sql.go
> postgres: fix postgres address parse

- sdk/java/src/main/java/io/juicefs/JuiceFileSystemImpl.java
- sdk/java/src/test/java/io/juicefs/JuiceFileSystemTest.java
Support ``;`` separated values for juicefs.users, juicefs.group https://github.com/juicedata/juicefs/issues/4723
> Support ; separated values for juicefs.users, juicefs.group

- pkg/chunk/cached_store.go
When gc and uploading happens simultaneously on the same stage file, the uploaded object will be leaked - never got a second chance to be deleted.
We observed several cases of leaded objects when `write-back` is enabled and `trash-days` set to 0.
> Delete leaked objects if it's already deleted by other goroutines

- cmd/flags.go
- cmd/mount.go
- pkg/chunk/cached_store.go
- pkg/chunk/disk_cache.go
- pkg/chunk/metrics.go
Currently, the writeback mode works by writing the block to the staging files first, and then uploading them to the object storage. So the throughput of the writeback mode is limited by the speed of disk. And the max write concurrency is `buffer-size / block-size` which could be overwhelming for some disks.
By limiting concurrent writes to staged files and spill others to object backend, we can have concurrent uploads to two backends, and theoretically the write throughput equals to **sum of the two** (see following experiment).
> By setting `--max-stage-write=10`, we got a write throughput of **5GB/s**, almost double the speed of original write. And it lasts for a long time, as long as we have enough space for stage files
> Enable concurrent write to both stage files and object storage to get 5GB/s write throughput

- cmd/dump.go
> cmd/dump: use a temp file during dumping

- pkg/vfs/vfs.go
> vfs: update data of internal files only when it's empty

- pkg/meta/slice.go
```
$ dd if=/dev/zero of=/jfs/tmp bs=1M count=10
$ truncate -s 4 /jfs/tmp
$ juicefs compact /jfs/tmp
$ juicefs info /jfs/tmp
objects:
+------------+----------------------------------+---------+--------+---------+
| chunkIndex |            objectName            |   size  | offset |  length |
+------------+----------------------------------+---------+--------+---------+
|          0 | test/chunks/0/24/24578_0_4194304 | 4194304 |      0 | 4194304 |
|          0 | test/chunks/0/24/24578_1_4194304 | 4194304 |      0 | 4194304 |
|          0 | test/chunks/0/24/24578_2_2097152 | 2097152 |      0 | 2097152 |
+------------+----------------------------------+---------+--------+---------+
$ juicefs info /jfs/tmp
objects:
+------------+----------------------------+------+--------+--------+
| …
```
> meta: remove tail zero slice in compactChunk

- pkg/meta/redis.go
The CAS happens only before the EXEC command: https://redis.io/docs/latest/develop/interact/transactions/
> meta/redis: fix some transactions that are not wrapped by multi/exec

- pkg/vfs/reader.go
Align with other memory usages, read buffer should track actual allocated memory rather than just using a portion of it.
> Fix read buffer usage

- pkg/chunk/disk_cache.go
- pkg/chunk/disk_cache_state.go
> disk-cache: disable state check when writeback enabled

- pkg/gateway/gateway.go
Increased max size of part to 5Gb in CompleteMultipartUpload
I've caught bug when tested server side copy with rclone. Rclone has default copy cutoff [4.656Gi](https://rclone.org/s3/#s3-copy-cutoff). During CompleteMultipartUpload gateway ignores size of parts and doesn't consider globalMaxPartSize (5GiB) and copies 1Gb max of each part.
> fix: JfsObjects.CompleteMultipartUpload

- pkg/vfs/vfs.go
- pkg/vfs/vfs_unix.go
> vfs: fix the issue that plock may be unlocked by mistake

- pkg/sync/cluster.go
In sync cluster mode, manager's IP address is never set. So it sends the address of `[::]` to workers, which makes the cluster mode unusable.
> Manager's IP address is never set in sync cluster mode

- cmd/stats.go
When objects sink to cold storage, we will have multiple `storage_class` labels in `object_request_data_bytes` metric, which causes the stats cmd shows less object bandwidth than actual.
The stats cmd should be robust to this situation - it's counter-intuitive for a newcomer to realize that adding a new label to those metrics will cause the stats cmd to function incorrectly.
> stats cmd should be robust enough to handle metrics with multiple labels

- pkg/meta/config.go
There was a typo in a warning string (an extra d in "heartbeat shouldd not be greater than 10 minutes")
> fix a trivial typo in a warning message

- pkg/vfs/reader.go
> Short-circuit fileReader.visit function if visitor returns false

- cmd/mount.go
No metadata backup in read-only mode is more confusing, it helps to have a hint.
> backup: print a warning message that backups are not turned on

- cmd/gateway.go
- go.mod
- go.sum
- pkg/gateway/gateway.go
1. Resolve a compatibility issue where the 1.2 version of gateway could not create a configuration file directory in the case of meta-readonly.
2. Fixed the bug that deleting an object through a web page does not report an error when using meta read-only.
close https://github.com/juicedata/juicefs/issues/4975
close #4989
close #4988
> gateway: skip init meta bucket when meta is read only

- pkg/gateway/gateway.go
fix https://github.com/juicedata/juicefs/pull/4969
> fix: list object should return etag information when needed

- cmd/webdav.go
- pkg/fs/http.go
- pkg/fs/http_test.go
ref #5023
```
$ juicefs  webdav redis://127.0.0.1/1  127.0.0.1:9092 --enable-proppatch
make[1]: Entering directory '/root/repo/litmus-0.13/lib/neon'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/root/repo/litmus-0.13/lib/neon'
gcc  -o basic src/basic.o -L. -ltest -Llib/neon -lneon  -lexpat
gcc  -o copymove src/copymove.o -L. -ltest -Llib/neon -lneon  -lexpat
gcc  -o props src/props.o -L. -ltest -Llib/neon -lneon  -lexpat
gcc  -o locks src/locks.o -L. -ltest -Llib/neon -lneon  -lexpat
gcc  -o http src/http.o -L. -ltest -Llib/neon -lneon  -lexpat
-> running `basic':
0. init.................. pass
1. begin................. pass
2. options............... pass
3. put_get............... pass
4. put_get_utf8_segment.. pass
5. put_no_parent......... pass
6. …
```
> cmd/webdav: support PROPPATCH method

- cmd/mount_unix.go
- cmd/passfd.go
if JFS_SUPER_COMM exist in env, get fuse fd from it.
> get fuse fd from csi

- pkg/meta/base_test.go
- pkg/meta/redis.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
> fix(quota): update quota twice when unlink/rename opened file

- pkg/fuse/fuse.go
> fix: fuse unmount when exit

- pkg/chunk/disk_cache.go
- pkg/chunk/disk_cache_test.go
fix with hash prefix path `chunks/5D/6/6174/6174813_0_8388608`
> fix invalid file matching regular expressions

- pkg/meta/base.go
- pkg/meta/quota.go
- pkg/meta/redis.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
We observed several volumes having much larger usage than the actual data size. It's confirmed when two of them are emptied but still have a large usage, and `juicefs summary` shows there are no files.
Here fix one possible reason: the usage is not flushed on close - thus we have different volume stats than dir stats.
> fix: flush volume stats on session close

- pkg/chunk/cached_store.go
- pkg/chunk/disk_cache.go
- pkg/chunk/disk_cache_state.go
- pkg/chunk/mem_cache.go
Add a new interface to clear the read cache. 
Since there are already interfaces like remove and removeStage, a flag-based merge is not used to avoid too many API changes. Moreover, the read and write cache logic is actually quite independent, so it is better to keep them separate.
> warmup: evict sub command may remove stage incorrectly

- pkg/vfs/vfs.go
Two reasons:
1. To align with the write op.
2. Admin can know read concurrency of the same file.
> Access log for read op also outputs file handle

- docs/en/introduction/comparison/juicefs_vs_glusterfs.md
- docs/zh_cn/introduction/comparison/juicefs_vs_glusterfs.md
Fixed an issue in the documentation stating that JuiceFS does not support the POSIX ACLs feature.
> Docs: fix JuiceFS vs. GlusterFS doc

- cmd/sync.go
- pkg/sync/config.go
- pkg/sync/sync.go
> cmd/sync: add 'max-failure' to exit when the transfer encounters more than a certain number of errors

- docs/en/administration/upgrade.md
> doc: add english documents about smooth upgrade

- docs/en/getting-started/standalone.md
- docs/zh_cn/getting-started/standalone.md
单机模式文档中存储默认路径"$HOME/.juicefs/local"，"/var/jfs" 或 "C:/jfs/local"，实测下来，在linux下没找到路径"$HOME/.juicefs/local"，存在歧义，提交文档优化，补充操作系统类别以便区分说明。
> doc:default bucket path doc optimize

- pkg/meta/tkv.go
`ss := ss[:0]` creates a new variable, so the outer `for i, s := range ss` never gets the new value.
> Fix: gc tool never deletes delayed slices

- pkg/chunk/disk_cache.go
`st.Mode()` represents a directory, whereat `cache.mode` is a file mode - they are **always** not equal.
This issue causes one extra syscall/IO on every cache write. Especially causes conflicts on staging writes with high concurrency.
> Fix: os.Chmod is called on every cache/stage write

- pkg/meta/redis.go
Because connecting to Azure Cache requires a [TLS server name](https://github.com/redis/go-redis/issues/1698), I'm not sure why this [PR](https://github.com/juicedata/juicefs/pull/3194/files) leaves the TLS server name empty. To avoid making disruptive updates, I added a separate query for users to specify the TLS server name.
> fix(redis): supports pass the tls server name for redis tls connection

- cmd/fsck.go
- cmd/gc.go
- pkg/meta/base_test.go
- pkg/meta/interface.go
- pkg/meta/redis.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
> cmd/gc: fix the issue that pending delete objects are misclassified as leaked

- pkg/chunk/cached_store.go
As discussed in #5192 , two benefits:
1. Remove unexpected read retries to obey user specified `io-retries` option.
2. Remove 1s delay between retries, just in case we get a stale file layout.
> Remove unexpected read retries

- pkg/chunk/disk_cache.go
After updating to the latest master branch, a lot of warning logs show up (see attached screenshot). 
This happens because `dir` is appended with "/" in the CacheManager (I don't know why), and when calling `filepath.Dir` on a string ending with "/", the function returns the same dir (with "/" trimed). So same dir is passed to `os.Mkdir` twice, and the second call will raise a warning log. This may cause confusion to users.
> Fix warning log when creating a new cache dir

- .github/scripts/sync/sync_cluster.sh
- cmd/object.go
- cmd/sync.go
> sync: when using the jfs protocol header, close the session before the program exits

- cmd/flags.go
- cmd/mount.go
- pkg/vfs/reader.go
> cmd/mount: add `max-readahead` option to set the max buffer of each readahead

- pkg/chunk/disk_cache.go
Retain a margin when evicting disk cache according to the free-space-ratio to ensure we have enough free space after cleanup, just the same as the mechanism when evicting by cache-size.
> disk-cache: keep a margin when evicting disk cache according to the free-space-ratio

- cmd/flags.go
- pkg/vfs/reader.go
Allow user to disable read-ahead when he is doing random read - to reduce read amplification and improve read latency.
> Allow user to disable readahead by setting `max-readahead` smaller than blocksize

- pkg/chunk/cached_store.go
- pkg/chunk/cached_store_test.go
- pkg/chunk/singleflight.go
- pkg/chunk/singleflight_test.go
- pkg/object/restful.go
Prefetch/partial/full read are three ways to read from oss. In current implementation, they may overlap with each other. On sequential read when readahead is triggered, the overlap is trivial. But on other cases, the overlap may cost extra network bandwidth.
This PR groups them in a singleflight to avoid the read amplification.
> Dedup prefetch/partial read with full block read to reduce read amplification

- pkg/object/ufile.go
close https://github.com/juicedata/juicefs/issues/5234
> object/ufile: implement limits interface  for us3 to support the multipart upload

- pkg/object/s3.go
close https://github.com/juicedata/juicefs/issues/5222
> object/s3: parse credentials using the default HTTP client

- pkg/meta/base.go
- pkg/vfs/vfs_test.go
* For the redis implementation, they are the same.
* For the kv implementation, `h.batch.indexes` are local offset to the `h.batch.entries`. But `h.readOff` is the global offset (minus the `h.initEntries`). They are not comparable.
> Fix dirHandler: readOff and index offset are not comparable

- cmd/mount_unix.go
#5238 propagates signals to child process, but provides no way to clear signal handler and exit goroutine.
The child process is started in a loop, unable to clear signal handler causes false positive warning logs.
> Clear signal handler when child process exits

- cmd/mount_unix.go
The supervisor process will always restart mount process even if it exits after receiving SIGTERM, is it expected?
We observe lots of restart in the logs - it will exit finally, but the restart causes lots of alerts.
> Fix endless restart loop on exit when user holds a file handler

- docs/en/grafana_template.json
- docs/en/grafana_template_k8s.json
Related Issue: https://github.com/juicedata/juicefs/issues/5247
1. Add "Uptime" panel to Grafana dashboard
2. Fix "Client Sessions" panel to show separate graphs by juicefs version
3. Fix "Go threads" panel to filter by vol_name variable
4. Update rate panels to use variable interval instead of fixed range
5. Update Staging panels to align with other panels
6. Sync Grafana template with Kubernetes template
> Update Grafana dashboards for consistency and improved visualization

- cmd/format.go
- docs/en/reference/how_to_set_up_object_storage.md
- docs/zh_cn/reference/how_to_set_up_object_storage.md
- pkg/meta/config.go
Hello there! :)
There is no issue for this PR yet (I think I will create it)
This PR adds support for TLS client certificates at transport level. It's intended for those S3 endpoints that are behind mTLS protection. This has been already tested in our endpoints and it's working well
I have added those params as flags under `format` command as this is more expectable by the user. 
I saw you stored some of them as query params, for example `tls-insecure-skip-verify` but equally they are stored in metadata settings
WDYT?
CC: @davies @SandyXSD @zhijian-pro I mention you all as you are the top contributors, so I dunno who to invoke
> feat: Add ability to configure client TLS

- pkg/chunk/metrics.go
The variable for the `staging_write_bytes` metric is intended to be `prometheus.Counter`, but the code uses Gauge.
https://github.com/juicedata/juicefs/blob/9ddc6d422d1511b0d861849535afcb286bd1af05/pkg/chunk/metrics.go#L32
https://github.com/juicedata/juicefs/blob/9ddc6d422d1511b0d861849535afcb286bd1af05/pkg/chunk/metrics.go#L91-L94
close https://github.com/juicedata/juicefs/issues/5268
> fix: initialize staging_write_bytes metric as Counter instead of Gauge

- cmd/fsck.go
- cmd/gc.go
- cmd/gc_test.go
GC tool hard-coded `chunk.Config` fields with:
```go
chunkConf := chunk.Config{
BlockSize:  format.BlockSize * 1024,
Compress:   format.Compression,
GetTimeout: time.Second * 60,
PutTimeout: time.Second * 60,
MaxUpload:  20,
BufferSize: 300 << 20,
CacheDir:   "memory",
}
```
This is error-prone - it may miss some fields from `format` added in the future. One such case is `HashPrefix`, where user sets it in the format but the gc tool doesnot pass it to `chunkConf`, which causes the `compact` sub-command never works.
> Fix gc tool never compacts keys with hash-prefix

- cmd/gc.go
Follow-up to PR #4979 , the `gc` tool never updates volume stats, even when files are deleted (e.g. run with `--delete`). So after several runs, volume will have a larger usage than expected.
> Fix gc tool never updates volume stats

- cmd/mount_unix.go
Too many error logs:
```
juicefs[1] <ERROR>: send signal terminated to 48: os: process already finished [mount_unix.go:794]
```
> Avoid too many error logs - "os: process already finished"

- pkg/meta/base.go
- pkg/meta/quota.go
It is possible that same fs stats will be increased/decreased twice, when `CloseSession` and `flushStats` run concurrently.
> Avoid concurrency between CloseSession and flushStats

- cmd/flags.go
- cmd/mount.go
- pkg/chunk/cached_store.go
Benefit scenario: read the most recently written files. One good use case is save/load checkpoint.
> Support cache blocks after uploading

- pkg/vfs/backup.go
To ensure there are some available backups.
> Only cleanup obsolete backups after a successful backup

- cmd/flags.go
- cmd/format.go
- cmd/mount.go
Test object storage at startup to fail fast instead of throwing `EIO` in the middle of user's workload.
> Perform object storage test at startup

- cmd/warmup.go
fix when warm up paths more then batchMax, fill same file repeat.
> fix warm up reset batch bug

- pkg/meta/sql.go
- pkg/meta/tkv.go
We observed many txn conflicts between `write` and `compact` when using TiKV, especially when users have many small IOs. TiKV's txn conflicts are very expensive, we can avoid them on the client side by using inode-granularity locks.
One downside of this change is that compaction between chunks within an inode cannot be performed concurrently, but considering chunks are 64M, so the probability of small IOs spanning multiple chunks is relatively low.
```
method: doCompactChunk, error: write conflict { start_ts:453879141784617034 conflict_ts:453879141784617033 primary:"xia\375A\013\000\003\000\000\000\000\000C\000\000\000\000" reason:Optimistic
```
> Avoid txn conflicts between write and compact on the same inode

- go.mod
- go.sum
- pkg/meta/base.go
- pkg/meta/interface.go
- pkg/vfs/vfs.go
depend on https://github.com/juicedata/go-fuse/pull/35
> vfs:support O_TMPFILE flag

- pkg/chunk/mem_cache.go
To release high memory usage caused by burst read/write.
> Memory cache also obeys `--cache-expire` flag

- pkg/utils/logger.go
- pkg/utils/logger_test.go
Besides file name and line number, also output method name for easier locating log messages in the code. Other languages' logging libraries also have similar outputs. e.g.
```log
juicefs[1] <INFO>: watching /jfs/data-rbwbwc, pid 49 [watchdog@mount_unix.go:160]
```
> Output method name in log

- cmd/mount_unix.go
Mount process and supervisor process occasionally hang and require manual killing. It turns out the supervisor process hangs while accessing mount process's pprof interface. A timeout is needed to prevent it from waiting indefinitely.
> Donot hang when showing stack traces

- pkg/meta/utils_darwin.go
- pkg/meta/utils_linux.go
- pkg/meta/utils_windows.go
- pkg/vfs/vfs.go
close https://github.com/juicedata/juicefs/issues/5328
> vfs/setxattr: ignore all unsupported xattr flags on the MacOS platform

- pkg/meta/base.go
- pkg/meta/redis.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
> Allocate `nextTrash` inode in `mknod` to avoid generating too many txn conflicts

- go.mod
- go.sum
- pkg/object/gluster.go
close #5211 #4043 
This problem with libgfapi is caused by this PR https://github.com/gluster/glusterfs/pull/3755.
glfd->entries should be initiated at first like in [pub_glfs_opendir](https://github.com/anoopcs9/glusterfs/blob/0b3e23d67f7a307b0b5b5bad6ad152f2a50188ee/api/src/glfs-fops.c#L3320).
In [pub_glfs_open](https://github.com/anoopcs9/glusterfs/blob/0b3e23d67f7a307b0b5b5bad6ad152f2a50188ee/api/src/glfs-fops.c#L420), it's not initiated and returned without error, which leads to segmentation when calling readdir.
> fix(obj-gluster): use OpenDir for directories, avoid segmentation fault

- pkg/meta/base.go
In most cases, `cleanupDeletedFiles` runs without doing anything. We can reduce scan calls to meta engine by decreasing the check frequency to an hourly basis.
> Reduce scan interval in cleanupDeletedFiles

- pkg/meta/redis_bak.go
- pkg/meta/sql_bak.go
1. A new slice is needed as concurrent operations might still use the same slice. 
3. Batch size for xattr is already limited at the outer layer.
> meta/backup: fix slice conflict

- .github/workflows/mutate-test-sdk.yml
- .github/workflows/sdktest.yml
- sdk/java/libjfs/main.go
- sdk/java/src/main/java/io/juicefs/JuiceFileSystem.java
- sdk/java/src/main/java/io/juicefs/JuiceFileSystemImpl.java
- sdk/java/src/main/java/io/juicefs/utils/BgTaskUtil.java
- sdk/java/src/main/java/io/juicefs/utils/NodesFetcher.java
- sdk/java/src/test/java/io/juicefs/JuiceFileSystemBgTaskTest.java
- sdk/java/src/test/java/io/juicefs/JuiceFileSystemTest.java
- sdk/java/src/test/java/io/juicefs/utils/BgTaskUtilTest.java
- sdk/java/src/test/resources/log4j.properties
BgTaskUtil：
对于同一个 volname 的后台任务只会启动一个实例运行。BgTaskUtil 的 runningInstance 存储了每个 volname 和 handles 之间的映射，当同一个 volname 的所有实例全部关闭，即 BgTaskUtil 内 volname 没有任何 handle 时，清理该 volname 对应的所有后台任务。确保当所有 JuiceFileSystem instance 关闭时，没有线程泄漏。
juicefs.users 和 juicefs.groups 配置的全局 guid 映射会缓存在 main.go 的 ``userGroupCache  // name -> (user -> groups)``  里，每个实例 user  的 groups 会优先查询此 map，如果没有找到，才会使用 java 传入的 group。Java 端后台任务会定期更新 
userGroupCache，默认 1 分钟一次
> Hadoop: fix background task thread leak

- pkg/meta/base.go
So user don't need to set up another tool, eg. `node-exporter`, to monitor their usage.
> Expose a capacity metric for users to configure usage alerts

- cmd/gc.go
close #5445
Remove concurrency of OnMsg since MaxDeletes concurrency has been set.
Additionally, the asynchronous processing in OnMsg (meta.DeleteSlice) may lead to object storage leaks if the GC process is interrupted.
> cmd/gc: fix delete slice

- pkg/meta/sql.go
close #5442
Transaction should have an X lock and wait for it, but MariaDB’s behavior is somewhat inconsistent and it reported an error.
Case: removeDir may conflict on child node (dirStat)
> meta/sql: retry txn for mariadb when conflict

- pkg/meta/sql.go
close #5479
Forcing the database to use composite index (parent, name) when querying the edge table in readdir stream and sorting based on the composite index.
It is the default behavior in MySQL to sorted by composite index, but not in PostgreSQL.
> meta/sql: fix readdir query

- pkg/chunk/disk_cache.go
When link fails, user won't be able to read the written block until background upload finishes. During this delay, an `EIO` error may occur.
> Fix link error during stage writing should be considered as failure

- pkg/meta/redis.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
`m.deleteSlice` may take much longer than limited to delete a large batch, which causes unnecessary txn conflicts. We can avoid that by checking earlier.
> Fix `cleanupDelayedSlices` to respect time limits as expected

- cmd/flags.go
- cmd/mount_unix.go
- pkg/fuse/fuse.go
- pkg/vfs/vfs.go
Some programs rely on frequent `readdir` calls to obtain updates from other processes. One example is [TensorBoard](https://www.tensorflow.org/tensorboard), which is widely used in machine learning area. This imposes a significant load on the backend metadata engine. In our environment, we observed over 200k QPS, but most directories are cold. Therefore, it is necessary to introduce a caching feature to reduce the metadata load.
> Allow kernel to cache readdir entries to reduce overhead of meta engines

- pkg/chunk/disk_cache.go
`diskcache.full()` is copied from `memcache` implementation.
> Fix a copy-paste error when refactoring `cache-items` flag

- pkg/vfs/vfs.go
> vfs: fix readdirplus retry when eaccess

- pkg/meta/redis.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
> dump: use total inodes to set the total number of the progress bar

- pkg/sync/download.go
- pkg/sync/download_test.go
- pkg/sync/sync.go
close #5492
All unit tests related to this update are adjusted and passed.
The case mentioned in the issue can also run now.
> cmd/sync: allocate memory from sync.Pool instead of Chunk.NewOffPage to avoid stall problem

- pkg/meta/base.go
use MaxDeletes as remove concurrency, the default value is hardcoded as 50.
> cmd/gc: use MaxDeletes as remove concurrency

- pkg/gateway/gateway.go
single bucket mode, almost every request calls stat `/` - it's unnecessary.
> No need to stat "/" in single bucket mode

- pkg/gateway/gateway.go
When everything works fine, it's unnecessary.
```log
2025.01.10 14:27:38.429215 [uid:0,gid:0,pid:0] Create (/.sys/tmp/077b2a5b-b48b-4e4e-a464-a9ed1f6cdbea,666): OK <0.001698>
2025.01.10 14:27:38.431234 [uid:0,gid:0,pid:0] Write (/.sys/tmp/7c76ca25-7d65-48a4-a57f-3d5c7fc1b46b,1048576): (1048576,OK) <0.000617>
2025.01.10 14:27:38.433948 [uid:0,gid:0,pid:0] Write (/.sys/tmp/7c76ca25-7d65-48a4-a57f-3d5c7fc1b46b,1048576): (1048576,OK) <0.000604>
2025.01.10 14:27:38.436660 [uid:0,gid:0,pid:0] Write (/.sys/tmp/7c76ca25-7d65-48a4-a57f-3d5c7fc1b46b,1048576): (1048576,OK) <0.000591>
2025.01.10 14:27:38.443178 [uid:0,gid:0,pid:0] Write (/.sys/tmp/214616a8-d8d9-4fb9-be24-8a71a6ade98c,1048576): (1048576,OK) <0.000113>
2025.01.10 14:27:38.448607 [uid:0,gid:0,pid:0] Write …
```
> Gateway - avoid one extra unnecessary delete request

- pkg/fuse/fuse.go
The written bytes of copy_file_range in FUSE must be 32 bits, but the requested size is 64 bites, which could be overflow.
> fuse: fix copied bytes overflow

- cmd/flags.go
- pkg/chunk/cached_store.go
A bug introduced in #5230
Otherwise, data corruption may happen.
> cache: fix buffer conflict in writeback mode

- pkg/sync/sync.go
> cmd/sync: eliminate wasteful list for some stores in sync

- .github/scripts/command/info.sh
- .github/scripts/hypo/fs_sdk_test.py
- .github/scripts/pysdk/pysdk_test.py
- .github/workflows/command.yml
- .github/workflows/fsrand.yml
- .github/workflows/pysdk.yml
- pkg/fs/fs.go
- pkg/meta/base.go
- sdk/java/libjfs/main.go
- sdk/python/juicefs/juicefs/juicefs.py
#5503
Also: update the SDK function parameter list to ensure accurate data types.
> sdk/python: use same bits of integer in all languages

- pkg/gateway/gateway.go
In the current gateway implementation, the `tmp/upload` directory is a flat structure, which can easily lead to concurrency conflicts under high concurrency. These conflicts severely impact performance and prevent the gateway from scaling. 
We can reduce conflicts in those large directories by adding a layer of hierarchy.
> gateway: add one more hierarchy to upload tmp/multiupload dir to reduce txn conflicts

- cmd/stats.go
Add timestamp info for each row
> cmd/stats: add timestamp info and duration option

- cmd/gateway.go
- docs/en/guide/gateway.md
- pkg/gateway/gateway.go
Enable object metadata for s3 gateway
#5367
> Gateway: add object metadata

- pkg/meta/sql.go
fix https://github.com/juicedata/juicefs/issues/5587
Where there is active transaction, the read will report database is locked error (can be easily reproduce by mdtest). Add cache/_journal/_timeout option to get it work.
> meta/sqlite3: fix database is locked error

- cmd/mount_test.go
- cmd/mount_unix.go
- pkg/fuse/context.go
- pkg/vfs/vfs.go
refer to https://github.com/juicedata/juicefs/issues/5394
> cmd/mount: Support all-squash mount option

- .goreleaser.yml
- hack/builder/Dockerfile
* Add arm64 musl-libc cross C compiler toolchain to the build container image
* Using the musl-libc cross C compiler for building in `.goreleaser.yml`
> build juicefs arm64 binary staticly linked

- pkg/meta/base.go
When process terminates and it's deleting slices, a panic happens:
> Fix send on closed channel panic

- pkg/chunk/cached_store.go
Once a struct is embedded in another struct, it can no longer be cast to the original one, therefore `partial cached block` are  not deleted.
https://go.dev/play/p/nTPo6xRoyJO
> Fix type assert to `*os.File` never works for `cacheFile`

- pkg/utils/logger.go
`Format` is called with the logger mutex locked.
```
func (entry *Entry) write() {
entry.Logger.mu.Lock()
defer entry.Logger.mu.Unlock()
serialized, err := entry.Logger.Formatter.Format(entry)
if err != nil {
fmt.Fprintf(os.Stderr, "Failed to obtain reader, %v\n", err)
return
}
if _, err := entry.Logger.Out.Write(serialized); err != nil {
fmt.Fprintf(os.Stderr, "Failed to write to log, %v\n", err)
}
}
```
> logger: don't call Getpid() inside the Format function

- go.mod
- go.sum
A new forked repo has been created to fix the panic issue.
https://github.com/juicedata/go-colorable/commit/a425c97a107553f8cc0833c2edf8e92004520c55
This pr replaces module dependency.
> Windows: fix panic when running as serivces; fix #5628

- .gitignore
- cmd/mount_windows.go
- pkg/winfsp/winfs.go
The Winfsp expects a fuse error code returned, however, the juicefs return a syscall error code, leading almost all error codes being converted to the default error code "permission denied".
https://github.com/winfsp/winfsp/blob/4fdec4d37fb4e56b6d810714f5a201e275211aaf/src/dll/fuse/fuse.c#L1127
This Pr extends the original errorconv function, the changes are based on the error.i file from WinFSP. 
https://github.com/winfsp/winfsp/blob/4fdec4d37fb4e56b6d810714f5a201e275211aaf/src/dll/fuse/errno.i#L1
meanwhile, this Pr adds an "access-log" mount option allowing the access log to be written into a file.
> Windows: fixed incorrect permission error returned; fix #5599

- pkg/chunk/disk_cache.go
- pkg/chunk/mem_cache.go
Process of cache write:
1. Write `cache.pages`
2. Write `cache.keys`
3. Delete `cache.pages`
When concurrently caching the same key, since we only check existence of `cache.pages`, not `cache.keys`, the same key can be written multiple times, resulting in wasted IO.
This additional overhead is easily reproducible. It can be frequently observed after adding more logs:
> Fix concurrent cache write

- cmd/mount_unix.go
close https://github.com/juicedata/juicefs/issues/5619
> mount: wait until new service process is ready

- cmd/config.go
> cmd/config: only convert the path when the new storage type is still a file

- pkg/meta/base.go
Currently, we do not have statistics on the trash directory, so it is unnecessary to update the statistics info for trash directory during unlink, and metadata operations can be eliminated to `Lookup` and `Unlink`.
Before:
> Remove one unnecessary `GetAttr` when deleting from trash

- pkg/meta/base.go
These warning logs appear frequently during massive deletions. CleanupTrash should exit timely like other deletion routines.
> Delete trash exits timely

- pkg/meta/base.go
- pkg/meta/base_test.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
Follow-up on #5549 - after uploading to a temporary file, gateway uses `rename` to move it to the target path. In current implementation, `rename` only locks `parentSrc` (in normal cases). #5549 adds an additional hierarchy to reduce conflicts on `parentSrc`, but conflicts still occur a lot on `parentDst` when user writes to the same directory concurrently.
So we should lock both `parentSrc` and `parentDst` in tkv/sql engines, in consistent with the redis engine.
> meta/rename: lock both src and dst parent for rename op to avoid txn conflicts and performance

- cmd/mount_unix.go
> log: fix nonsense characters in log (#5676)

- pkg/fuse/context.go
- pkg/meta/context.go
- pkg/meta/sql_bak.go
- pkg/meta/tkv_bak.go
- sdk/java/libjfs/main.go
In stdlib, `context.WithValue` returns a derived context that points to the parent `Context`, and the parent `Context` is not modified.
In JuiceFS, `context.WithValue` mutates itself by stacking the `Context` field. This is error-prone as no one can clean the stack chain.
Especially in the `gateway` scenario where `meta.Context` is a global variable - its value chain can grow infinitely as `gateway` runs long enough. This causes a memory leak and makes searching for a non-existent key very expensive.
It's better to follow best practices in the Go community.
> Better to keep `context.WithValue` constant

- pkg/meta/base.go
- pkg/meta/interface.go
I think the Attr's marshal and unmarshal in Attr is better than baseMeta.  Maybe some other basic structure need review later.
> refactor: extract Attr's marshal and unmarshal from baseMeta to Attr

- pkg/fuse/fuse.go
Timeout shows in `.config` file, but not passed to the fuse lib.
> Fix fuse timeout is not set

- pkg/chunk/disk_cache.go
- pkg/chunk/disk_cache_test.go
Scanning from disk overwrites `size` and `atime` of existing cache items in memory:
1. `size` is overwritten by the physical size of the file, which includes the logical size plus the CRC footer. However, when adding cache in other places, we use the logical size. I suppose it's better to be consistent on which size to use.
2. The granularity of file system's `atime` is relatively coarse (relatime), and some even have atime disabled (noatime). However, `atime` recorded in memory has finer granularity and is more accurate in most cases. Overwriting `atime` in memory blindly would cause the expire eviction strategy not working as expected.
> cache: inherit atime and track logic size when re-scan

- cmd/mount_windows.go
- pkg/winfsp/winfs.go
> Windows: hide the  dot files by default. fix #2013

- pkg/meta/base.go
- pkg/meta/redis.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
Improve the file deletion performance by processing multiple files in parallel
close #5671
> gc: improve the performance of Juicefs gc command

- pkg/winfsp/winfs.go
fix #https://github.com/juicedata/juicefs/issues/5682
following is the create disposition defined for a create IRP (from system wdm.h file )
```
//
// Define the create disposition values
//
#define FILE_SUPERSEDE                  0x00000000
#define FILE_OPEN                       0x00000001
#define FILE_CREATE                     0x00000002
#define FILE_OPEN_IF                    0x00000003
#define FILE_OVERWRITE                  0x00000004
#define FILE_OVERWRITE_IF               0x00000005
#define FILE_MAXIMUM_DISPOSITION        0x00000005
```
When calling ```CreateFileW(filename, GENERIC_READ | GENERIC_WRITE, FILE_SHARE_READ | FILE_SHARE_WRITE, 0, CREATE_NEW, FILE_ATTRIBUTE_NORMAL, 0);``` twice, WinFsp receives the Create IRP with FILE_CREATE disposition value twice, so it calls …
> Windows: fix issue when creating an existing file

- pkg/winfsp/winfs.go
close https://github.com/juicedata/juicefs/issues/5723
The reason why the wrong permission was set is that we have a default create_umask=022 option. With this option, all permissions for newly created files would be set to 0755 according to the [ winfsp source code.](https://github.com/winfsp/winfsp/blob/4fdec4d37fb4e56b6d810714f5a201e275211aaf/src/dll/fuse/fuse_intf.c#L479)
> Windows: remove set_umask default value;

- pkg/meta/interface.go
- pkg/vfs/vfs.go
- pkg/vfs/vfs_windows.go
- pkg/winfsp/winfs.go
close https://github.com/juicedata/juicefs/issues/5693
* When setting attributes for a file or folder, winfsp call juicefs.chflags() and pass the attribute flags to juicefs.
* According to this [article,](https://support.microsoft.com/en-us/topic/you-cannot-view-or-change-the-read-only-or-the-system-attributes-of-folders-in-windows-server-2003-in-windows-xp-in-windows-vista-or-in-windows-7-55bd5ec5-d19e-6173-0df1-8f5b49247165) on windows sytem, the readonly attribute for a folder basically doesn't have any effect. 
run ```winfsp-test --fuse-external create*```
* before this PR, it failed for the create_fileattr_test and create_readonly_test.
* after this PR, the failed tests passed. [tested on redis and sqlite, **didn't** test on tikv]
* Maybe we can ignore the FlagWindowsArchive? This is …
> Windows: add win attrs support;

- go.mod
- go.sum
When I tried to compile on some heterogeneous computing devices, I encountered some errors, so I updated this dependency to fix the problem.
```
[root@master-1 juicefs-main]# uname -r
4.19.190-7.9.an8.loongarch64
[root@master-1 juicefs-main]# go build -o juicefs .
/root/go/pkg/mod/github.com/remyoudompheng/bigfft@v0.0.0-20200410134404-eec4a21b6bb0/arith_decl.go:10:6: missing function body
/root/go/pkg/mod/github.com/remyoudompheng/bigfft@v0.0.0-20200410134404-eec4a21b6bb0/arith_decl.go:11:6: missing function body
/root/go/pkg/mod/github.com/remyoudompheng/bigfft@v0.0.0-20200410134404-eec4a21b6bb0/arith_decl.go:12:6: missing function body
/root/go/pkg/mod/github.com/remyoudompheng/bigfft@v0.0.0-20200410134404-eec4a21b6bb0/arith_decl.go:13:6: missing function body …
```
> Update bigfft package to latest version

- pkg/vfs/vfs_windows.go
- pkg/winfsp/winfs.go
The previous PR https://github.com/juicedata/juicefs/pull/5714 added an flag "O_EXCL" manually while creating a new file, resulting in the incorrect behavior handler.writer  = nil when creating a file handler.
According to the source code of [winfsp](https://github.com/winfsp/winfsp/blob/4fdec4d37fb4e56b6d810714f5a201e275211aaf/src/dll/fuse/fuse_intf.c#L951) 
```
if ('C' == f->env->environment) /* Cygwin */
fi.flags = 0x0200 | 0x0800 | 2 /*O_CREAT|O_EXCL|O_RDWR*/;
else
fi.flags = 0x0100 | 0x0400 | 2 /*O_CREAT|O_EXCL|O_RDWR*/;
```
Winfsp will pass the O_EXCL flag to juicefs, so all we need to do is only convert those flags to syscall flags.
https://github.com/winfsp/cgofuse/blob/b8358bce7bce407a8f5a9445723df52ebca32337/fuse/fsop_nocgo_windows.go#L101C1-L111C2
```
// Flags used in …
```
> Windows: fixed incorrect flags when creat/open a file

- pkg/sync/sync.go
> sync: fix the counter issue when deleting directories

- pkg/meta/interface.go
If the username contains the "@" character, JuiceFS cannot correctly identify the username. I want to add support for usernames that contain the "@" character.
As shown in the following figure, the username is "user@name", but JuiceFS recognizes the username as "user", which results in the inability to log in to the database.
After the modification, the user name without the @ character and the user name with the @ character can be recognized.
username contains '@' characters
username does not contains '@' characters
> Fix the issue that the username cannot contain the "@" character

- pkg/meta/base.go
- pkg/meta/base_test.go
- pkg/meta/redis.go
- pkg/meta/redis_lock.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
- pkg/meta/tkv_lock.go
- pkg/meta/utils.go
- pkg/meta/utils_test.go
- pkg/utils/logger.go
- pkg/utils/logger_test.go
`txRestart` happens a lot in a busy cluster. Some are expected (incrCounter of usedSpace), some are not (doWrite) - they all mix together in the same metric, we cannot set up an alert for the latter.
This PR adds few labels to `txRestart` metric. It helps to understand the reason of transaction conflicts and gives a hint how to avoid/fix them, e.g. conflicts:
- `doCleanupDelayedSlices` - `cleanupDelayedSlices` doesnot respect time limits as expected, it can be fixed by modifying code, see #5463.
- `doMknod` - user is creating in the same directory simultaneously, this conflict hurts performance, and can be avoided sometimes, see #5549, #5330.
- `doWrite`/`doTruncate` - user is modifying the same file from different nodes accidentally. He must be notified to avoid data corruption and even …
> Show method label on transaction conflict metric

- pkg/chunk/cached_store.go
- pkg/chunk/cached_store_test.go
- pkg/chunk/chunk.go
- pkg/vfs/compact.go
- pkg/vfs/compact_test.go
- pkg/vfs/writer.go
> cache/writeback: upload directly to object storage when compact

- cmd/flags.go
- cmd/mount_unix.go
- pkg/fs/fs.go
- pkg/fuse/fuse.go
- pkg/vfs/vfs.go
When `lookup` a non-existent file, current code only returns the error. However, kernel allows an empty dentry with a timeout to be returned, which acts as a negative lookup cache.
One use case of this negative cache in our environment is to accelerate `ffmpeg` - it looks up many non-existent files in the working directory. With hundreds of instances, those negative lookups cause lots of overhead to meta engine, and slows down all `ffmpeg` instances.
Also, `libfuse` has a similar option `negative_timeout` - https://man7.org/linux/man-pages/man8/mount.fuse3.8.html
> Allow kernel to cache negative dir entry lookups

- .github/workflows/wintest.yml
- pkg/winfsp/winfs.go
* This pr introduces three tests for juicefs, winfsp test, winfstest, fsx. I modified the source code of these tests to make sure the current version of juicefs can pass all of them (to build a baseline). The following are the 3 repos that I forked.
* https://github.com/juicedata/winfsp
* https://github.com/juicedata/winfstest
* https://github.com/chenjie4255/fstools 
The reason that I did not fork the fstools is because I didn't make any changes to the source code, but only created a release to save the build result (exe file)
* https://github.com/juicedata/juicefs/actions/runs/13850669232/job/38757277730
> CI: Add Windows tests

- cmd/mount.go
- pkg/vfs/reader.go
> mount: support setting readahead to 0

- pkg/winfsp/winfs.go
The previous [fix](https://github.com/juicedata/juicefs/pull/5376) for juicefs subcommand was tested with as-root option. when this option is removed, calling ```juicefs info``` or other sub commands results in the "Access denied" error.
According to this [disscustion](https://github.com/winfsp/winfsp/issues/40) , even we have the mode "0666" for the ".control" file, because we didn't set the correct uid & gid, the permission mapping doesn't work.
> windows: fixed access denied for '.control' file

- go.mod
- go.sum
- pkg/vfs/vfs_windows.go
- pkg/winfsp/winfs.go
ref: https://github.com/winfsp/cgofuse/releases/tag/v1.6.0
> windows/cgofuse: upgrade cgofuse sdk from v1.5.0(2021-03-09) to v1.6.0(2025-01-13)

- .github/workflows/wintest.yml
- pkg/fs/fs.go
- pkg/winfsp/winfs.go
close https://github.com/juicedata/juicefs/issues/5822
* Calling the original function: ```func (f *File) Utime(ctx meta.Context, atime, mtime int64) (err syscall.Errno) ``` results in the loss of accuracy for the nanosecond (nsec) part.
* This PR introduces a new utime2 method, allowing the direct setting of both the second (sec) and nanosecond (nsec) parts.
> windows: fix time accruacy bug

- cmd/mount_unix.go
- cmd/passfd.go
When main thread exits, deferred statements in child threads won't execute.
> Fix fuse_fd_comm was never cleaned up

- pkg/vfs/backup.go
fix #5875 
When a parent directory does not exist, the os package will return syscall.ENOTDIR on windows platform.  see this [link](https://go-review.googlesource.com/c/go/+/381957)
Now can see a successful backup log.
```
C:\Users\....\Workspace\juicefs>juicefs.exe mount redis://192.168.31.134:6379/2 x: --backup-meta 5m
2025/03/27 16:39:07.964517 juicefs[21180] <INFO>: Meta address: redis://192.168.31.134:6379/2 [NewClient@interface.go:578]
2025/03/27 16:39:07.968331 juicefs[21180] <INFO>: Ping redis latency: 561.1µs [checkServerConfig@redis.go:3653]
2025/03/27 16:39:07.976978 juicefs[21180] <INFO>: Data use minio://192.168.31.134:9000/jfscevol2/myjfs2/ [mount@mount.go:664]
2025/03/27 16:39:07.976978 juicefs[21180] <INFO>: JuiceFS version 1.3.0-dev+unknown [mount@mount.go:707]
2025/03/27 …
```
> windows: fixed meta backup

- cmd/debug.go
- cmd/debug_windows.go
- cmd/mount.go
- cmd/mount_windows.go
- pkg/winfsp/winfs.go
fix #5869
* Winfsp provides a "stderr" param, allowing us to redirect the output of a managed application to a file. We can use it when running in the background to save the log output.
* for the replacement of the 'tail' command on Windows, this pr uses 'Get-Content' command, which has a similar effect as the 'tail' command on UNIX.
> windows:  add pprof & log file collection for debug command

- pkg/chunk/cached_store.go
Warmup now have too many concurrency than expected by default (50x50, introduced in #5713), which makes peak memory usage prone to trigger OOM. This patch alleviates part of the memory usage.
> Release memory timely to avoid OOM

- pkg/meta/base.go
close #5880
The attributes of the “init entries” are not full, causing winfs to re-execute getattr for each file.
> meta: fix missing attributes in ReadDirPlus

- pkg/utils/alloc.go
- pkg/utils/alloc_test.go
BenchmarkPowerOf2
BenchmarkPowerOf2/bits.Len
BenchmarkPowerOf2/bits.Len-8         	   38287	     29290 ns/op
BenchmarkPowerOf2/Loop
BenchmarkPowerOf2/Loop-8             	    1995	    578712 ns/op
> Optimize `PowerOf2` to use a msb lookup table

- cmd/clone.go
fix #5896
* WinFsp doesn’t support getting the UID/GID during I/O calls (read/write). See: https://github.com/winfsp/winfsp/issues/99#issuecomment-321215011
* When the mount process receives the write callback to the .control file, it tries to get the UID through fuse.getcontext(). Because of the previous "bug," it results in the write operation being performed as root (uid=0).
* The clone message handler processes it as the root user, which causes the file to become inaccessible on Windows.
* This pr simply force the "preserve" mode on windows.
* Maybe in the future we can extend the clone message and pass the current UID/GID with it.
> windows: fix clone perm issue.

- sdk/python/Dockerfile.builder.arm
Compiling the Python SDK relies on golang, and the dockerfile for arm is old.
I rewrote the file with a golang image and successfully compiled it on macOS.
> Rewriting arm-oriented Dockerfile with golang images

- pkg/meta/sql.go
- pkg/meta/tkv.go
A minor patch:
1. avoid write operation when nothing changes
2. avoid txn conflict when multiple clients set the same KV concurrently
> meta/setXattr: avoid write operation when nothing changes

- cmd/mount.go
- cmd/mount_windows.go
- pkg/meta/base_test.go
- pkg/meta/redis.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
- pkg/winfsp/trace.go
- pkg/winfsp/winfs.go
fix #5871 
This PR adjusts the following behaviors:
* Fixed a crash issue on Windows when renaming a.txt to A.TXT. The crash was caused by the original line 1736. see comment.
* After fixing the crash, it also fixed the issue where renaming had no effect (because the code returned early when ino == dino).
* Fixed a problem where the file name became all uppercase after renaming in File Explorer. (Solved by implementing the getpath interface.)
* Adjusted the original --access-log feature: instead of logging from the FS layer, it now logs from the WinFS layer.
* Added a case-sensitive parameter. (It is disabled by default, and can be enabled when needed.)
* When case-sensitive is enabled, renaming a file to a similar name with different casing (e.g., a.txt → A.TXT) will cause the file to …
> windows: fix rename bugs

- pkg/sync/sync.go
Since version 1.2, we have observed that even when specifying multiple workers using the `--worker` option, the throughput of sync tool does not scale any more. Debugging revealed that because each worker's buffer is very large, a single worker might fetch (almost) all tasks into its own buffer, causing other workers to remain idle:
After removing the buffer, workers can fetch as demand now:
> cmd/sync: fix large buffer prevents sync throughput from scaling with the number of workers

- pkg/winfsp/winfs.go
fix #5932 
When testing the dd behavior, I found the following "bug":
[Mingw-msys] When the dir capacity reached to 80%(8MB/10MB), calling ```dd if=/dev/zero of=test bs=1M count=10``` would not report an error. However, the file was created but the content is still empty.
It seems that the implement for the dd command on Windows platform might not properly call flush() before closing the file handle, this could be confirmed by the kernel IRP packages(see the screenshot below). The same issue occurs when using the cp command.
I also tested the Windows "copy" command and it can report "no enought space on the disk" correctly.
> windows: fix incorrect error code;

- pkg/sync/cluster.go
Currently, when we need to custom the manager-addr port, we must pass the manager's IP address; otherwise, an invalid address is passed to the worker
now, support custom manager port without ip like `--manager-addr=:1234`
> sync: custom cluster manager-addr port without ip

- cmd/status.go
- cmd/status_test.go
- pkg/fs/fs.go
- pkg/meta/status.go
- sdk/java/libjfs/main.go
- sdk/python/juicefs/juicefs/juicefs.py
rel https://github.com/juicedata/juicefs/issues/5815
New modification points:
1. move the specific implementation of status to meta.
2. add exception handling to the PySDK code.
3. simplify the calling code for JSON serialization and deserialization.
> pysdk: add command status

- cmd/mount_windows.go
- pkg/winfsp/winfs.go
From the tests that I ran, I found that when disabling the get-get callback, the small file reading performance in the bench test could earn an improvement of about 30% on my machine. 
Since we are running a case-insensitive file system on Windows, I think it is better to disable this feature by default to get a better default performance.
> windows: added "enable-get-path" mount option

- cmd/flags.go
- cmd/format.go
- cmd/mount.go
- cmd/mount_unix.go
- pkg/object/object_storage_test.go
ref #5014 https://github.com/rfjakob/gocryptfs/issues/590
test:
apptainer run --fusemount "host:juicefs mount sqlite3:///[path]/test.db --cache-dir=/tmp/cache /mnt" docker://ubuntu
will convert to "juicefs mount sqlite3:///[path]/test.db /dev/fd/number -f"
> cmd: modify params to support apptainer fusemount

- pkg/chunk/disk_cache.go
- pkg/chunk/disk_cache_test.go
The size limit of diskcache is controlled by the direct parameter cacheSize as well as the disk's freeRatio. Therefore, in cacheStore.add function, eviction tirgger could also take freeRatio's size limit into consideration.
> feat(chunk): trigger eviction by freeratio in cache add path

- pkg/vfs/fill.go
`cmd/warmup` doesnot support hole in file - there should be no GET requests for slice ID 0.
```
warmup cache error : inode 3282947 slice 0 : get chunks/0/0/0_0_1024: NoSuchKey: The specified key does not exist.
```
> cmd/warmup: fix handling files with holes

- pkg/meta/base.go
- pkg/meta/quota.go
- pkg/meta/redis.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
Fix missing update for total inodes in `--sync-dir-stat`.
File usage in .trash is also missed as reported in #6035.
> cmd/fsck: `sync-dir-stat` should also update total inodes

- pkg/meta/base.go
- pkg/meta/tkv.go
- pkg/vfs/backup.go
- pkg/vfs/fill.go
- pkg/vfs/internal.go
Two minor fixes:
- When user cancels the `cmd/compact`, the compact task in the background just won't stop because of a deep queue(10000). It should exit timely as other cmd tasks.
- It's better to have a log message for background tasks when they start, so we can know what's happening when ceertain resources spike (cpu/memory/meta ops).
> Exit compact timely and log a message when long-running background tasks start

- pkg/winfsp/winfs.go
From the previous [test ](https://github.com/juicedata/juicefs/issues/5252)we did, lots of getattr requests were made due to the parsing of the potential symbol link. Since we don't support symbolic links on the Windows platform for now, we can disable this feature to gain a small performance boost.
According to the source code of WinFsp, to disable the symbolic link feature, we need to return the ENOSYS for the readlink("/") request.
```
if (0 != f->ops.readlink)
{
char buf[FSP_FSCTL_TRANSACT_PATH_SIZEMAX / sizeof(WCHAR)];
int err;
/* this should always fail with ENOSYS or EINVAL */
err = f->ops.readlink("/", buf, sizeof buf);
f->has_symlinks = -ENOSYS_(f->env) != err;
```
Since this is a temporary workaround before we add the symbol link support, this PR uses an environment variable …
> windows: disable symbollink by default

- cmd/info.go
Currently the `offset` field in cmd/info output is hard coded to `0` - it doesn't provide any useful information. It's better to display absolute offsets in the file, so when some chunk is corrupted, we can easily identify which part of the file is affected.
> cmd/info: add file offset column

- cmd/warmup.go
> cmd/warmup: prevent division by zero when checking for empty files/directories

- .gitignore
- pkg/winfsp/winfs.go
When the source file was deleted, the symbol link file could not be deleted; this PR fixes this issue.
> windows: fix symbol link cannot be deleted

- pkg/fs/fs.go
- pkg/fs/fs_test.go
- pkg/fs/http.go
- pkg/gateway/gateway.go
- sdk/java/libjfs/main.go
Many tools (e.g., rclone) use multipart upload to split files into smaller chunks when uploading. This amplifies number of inodes for those files, which can easily cause users to exceed their inode quota. We should promptly delete these intermediate files.
> gateway: delete intermediate temporary files timely to reduce inode sage

- pkg/meta/redis.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
We have conflicts on `cleanupZeroRef`
> meta/doCleanupSlices: should exit timely as other cleanup routines

- pkg/meta/base.go
- pkg/meta/random_test.go
The inode name cannot contain the characters '/' and '\0'.
Meta module will check the inode name when `Mknod()`, `Link()`, `Rename()` are called.
> chore: Meta module will check the inode name

- .github/workflows/wintest.yml
- cmd/bench.go
- cmd/mount_windows.go
- pkg/fs/fs.go
- pkg/winfsp/winfs.go
**NO CACHE**
**DEFAULT CACHE && DISABLE SYMBOLINK(not in this pr)**
**ANOTHER LINUX MACHINE WITH THE SAME HARDWARE & SOFTWARE CONFIGURATION (8C16G)**
**In short:**
* The large-file write speed improved from 320MB/s to 430MB/s, but it is still much slower than the Linux version.
* Small-file read and write performance became 2 to 5 times faster.
* The speed of stat operations also increased significantly.
1. The current implementation behaves inconsistently: some calls in WinFS pass through the FS layer, while others bypass it via the vfs layer. So after enabling caching, without adding a cache invalidation interface for the FS layer, certain winfsp-test cases will fail.
2. Additionally, during troubleshooting, it was found that when the system user (uid=18) attempts to start an .exe …
> windows: add attr, entry and dir-entry cache;

- pkg/meta/base.go
The doMknod method of the metadata engine for sql and tkv types has not updated the stat value.
> fix: update stats after creating trash time directory

- pkg/chunk/cached_store.go
- pkg/sync/sync.go
The capacity is used as a buffer for generated token, which could reduce the delay for incoming requests. But large capacity will cause burst traffic, which may cause packet loss.
> fix burst bandwidth

- pkg/object/eos.go
- pkg/object/minio.go
- pkg/object/oos.go
- pkg/object/qiniu.go
- pkg/object/s3.go
- pkg/object/scw.go
- pkg/object/space.go
- pkg/object/wasabi.go
Sha256 checksum in object storages are added again by #5968, costing ~30% cpu time:
Sha256 is too heavy for a file system, crc checksum is enough.
> Fix: sha256 checksum in s3 is added again

- pkg/object/eos.go
- pkg/object/minio.go
- pkg/object/oos.go
- pkg/object/qiniu.go
- pkg/object/s3.go
- pkg/object/scw.go
- pkg/object/space.go
- pkg/object/wasabi.go
Another breaking change after migrating to new sdk. Otherwise, we will have three times as many retries as before.
> Disable S3 SDK retries since JuiceFS has its own retry mechanism

- pkg/sync/sync.go
If the file does not exist, we return nil for the err here, and decrease the copied counter by -1. 
The checksum fails due to the non-existent file, resulting in a final negative number.
```
➜  JUICEFS1=redis://127.0.0.1:6379/0 JUICEFS2=redis://127.0.0.1:6379/1 ./juicefs sync jfs://JUICEFS1/ jfs://JUICEFS2/ --check-all
2025/05/19 14:52:36.803665 juicefs[95731] <INFO>: Meta address: redis://127.0.0.1:6379/0 [NewClient@interface.go:578]
2025/05/19 14:52:36.805974 juicefs[95731] <INFO>: Ping redis latency: 179.375µs [checkServerConfig@redis.go:3684]
2025/05/19 14:52:36.807000 juicefs[95731] <INFO>: Meta address: redis://127.0.0.1:6379/1 [NewClient@interface.go:578]
2025/05/19 14:52:36.810394 juicefs[95731] <INFO>: Ping redis latency: 308.625µs [checkServerConfig@redis.go:3684]
2025/05/19 …
```
> pkg/sync: fix copied counter

- pkg/object/object_storage.go
- pkg/sync/cluster_test.go
avoid precision issues caused by json
fix: https://github.com/juicedata/juicefs/issues/6126
> pkg/object: use string marshal object mtime

- pkg/sync/sync.go
For some objects, such as minio, head object, the milliseconds were removed, only retaining to the second.
Consider them equal if head time's millisecond part is 0 and there is the only difference
head: => https://github.com/minio/minio/blob/12a6ea89cc657eab17a01272892db4d3154eff48/cmd/api-headers.go#L117-L118
list: => https://github.com/minio/minio/blob/12a6ea89cc657eab17a01272892db4d3154eff48/cmd/api-response.go#L840-L841
fix: https://github.com/juicedata/juicefs/issues/6133
> pkg/sync: fix mtime comparison for check-change

- .github/workflows/integrationtests.yml
- pkg/meta/tkv.go
- pkg/meta/tkv_badger.go
- pkg/meta/tkv_etcd.go
- pkg/meta/tkv_fdb.go
- pkg/meta/tkv_mem.go
- pkg/meta/tkv_prefix.go
- pkg/meta/tkv_tikv.go
In the current implementation of TiKV, each transaction requires at least two RPCs: one to obtain start timestamp from PD, and another to read/write data from TiKV, even for the simplest point query scenarios such as `lookup/getattr`. Actually, TiKV has optimized for simple point query scenarios by allowing use of `math.MaxUint64` as a start timestamp, which internally means "to get the latest committed data." This way, we can eliminate one RPC call to PD, reducing latency and alleviating the load on PD.
This optimization corresponds to [simpleTxn](https://github.com/juicedata/juicefs/pull/5377) in SQL engine - to reduce transaction overhead for simple queries. It provides a significant improvement for read-heavy scenarios, such as LLM training. A simple `mdtest` benchmark shows that …
> meta/tikv: simplify transactions in point get scenarios by reducing one RPC call

- pkg/meta/sql.go
In the current implementation, the `sqlStr` of `setXattr()` is:
```sql
UPDATE `jfs_xattr` SET `inode` = ?, `name` = ?, `value` = ? WHERE `id`=? AND `inode`=? AND `name`=?"
```
The `inode` and `name` columns should not appear in the `SET` list.
This PR simply changes it to
```sql
UPDATE `jfs_xattr` SET `value` = ? WHERE `id`=? AND `inode`=? AND `name`=?
```
> meta/sql: setXattr only update necessary columns

- cmd/mount.go
- cmd/mount_unix.go
- cmd/mount_windows.go
- pkg/utils/utils_darwin.go
- pkg/utils/utils_linux.go
In our production env, MADV_HUGEPAGE is being used to indicate the application is willing to wait for work for thp memory to be available.
When numpy[1] consumes the most of the huge pages that are produced by kcompactd, juicefs may take minutes to get a one. All these eventually leading to IO hang issues. And some times kcompactd itself is waiting for juicefs to finish an IO:
kernel: INFO: task kcompactd0:1175 blocked for more than 120 seconds.
kernel:       Tainted: P           OE     5.15.0-88-generic #98-Ubuntu
kernel: "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
kernel: task:kcompactd0      state:D stack:    0 pid: 1175 ppid:     2 flags:0x00004000
kernel: Call Trace:
kernel:  <TASK>
kernel:  __schedule+0x24e/0x590
kernel:  ? …
> cmd/mount: disable transparent huge page

- pkg/meta/tkv_tikv.go
This PR adds support for two configuration parameters to control TSO (Timestamp Oracle) behavior in TiKV:
- `open-tso-follower-proxy=true`: Enables TSO follower proxy mode in the PD client.
- `max-tso-batch-wait-interval=10ms`: Sets the maximum batching wait interval for TSO requests.
These options help reduce TSO-related bottlenecks in large-scale deployments by offloading timestamp allocation to follower PD nodes.
Example usage:
`tikv://pd-1,pd-2,pd-3?open-tso-follower-proxy=true&max-tso-batch-wait-interval=10ms`
> tikv: support `open-tso-follower-proxy` and `max-tso-batch-wait-interval` options

- cmd/flags.go
- cmd/mount.go
- pkg/meta/base.go
- pkg/meta/config.go
- pkg/meta/tkv_tikv.go
In large-scale deployments with thousands of clients, the statRootFs method triggers high-concurrency access to two metadata counters:
```go
m.en.getCounter(usedSpace)
m.en.getCounter(totalInodes)
```
These counters are implemented as hot keys in TiKV. When each client frequently queries them, it results in:
- TiKV node QPS spiking to 50k–100k;
- TiKV nodes restarting due to overload;
- PD nodes being overwhelmed and becoming unstable.
This severely impacts the availability and performance of the metadata service.
This PR removes direct calls to getCounter(usedSpace) and getCounter(totalInodes). Instead, the values are now read only from in-memory atomic variables:
```go
used = atomic.LoadInt64(&m.usedSpace)
inodes = atomic.LoadInt64(&m.usedInodes)
```
These variables are already …
> meta: add a option `--fast-statfs` to speed up statfs

- cmd/objbench.go
Add a `--storage-class` flag to `objbench` to test various storage classes (e.g., Standard, Infrequent Access) across providers such as AWS S3, Alibaba OSS, and Ceph RGW."
> objbench: add `--storage-class` option to indicate storage class for object storage

- pkg/object/tos.go
tos endpoint: bucket.tos-cn-beijing.ivolces.com
> object: wrong region of TOS

- pkg/fs/fs.go
- pkg/vfs/accesslog.go
Currently, the latency range for object storage is [0.01, 168]s, but range for FUSE latency is [0.0001, 12.7]s. The gap is too large that FUSE latency p99 being very insensitive when object storage latency increases, and sometimes the p99 is even much smaller than average:
It is better to make FUSE latency range cover the range of object storage latency.
> vfs/metrics: histogram bucket range of FUSE latency should exceed range of object storage

- cmd/mount_unix.go
The new `readdir-cache` flag may conflict with `skip-dir-mtime` flag in some cases. Users should be warned about this possibility.
> cmd/mount: add a warning message when both `readdir-cache` and `skip-dir-mtime` are enabled

- pkg/sync/sync.go
In order to be able to handle the format `a//b`
> cmd/sync: clear the redundant delimiters in the files-from

- sdk/python/juicefs/juicefs/juicefs.py
When `jfs_init` fails, it returns `0`, but Python SDK does not raise an exception because `check_error()` only checks `r < 0`. I modified `check_error()` to handle `jfs_init` failure case when it returns `0`.
This aligns with Java SDK behavior:
https://github.com/juicedata/juicefs/blob/f26ce2b1d5edbc7ca498fc79dd123fae860fe371/sdk/java/src/main/java/io/juicefs/JuiceFileSystemImpl.java#L465-L468
Changes
- Added special case for `jfs_init` when `r == 0` in `check_error()`
- Error message follows Java SDK format for consistency
Tests
```python
import juicefs
try:
client = juicefs.Client(name='test', meta='redis://invalid-host:6379')
except OSError as e:
print(f"Exception raised: {e}")  # Now works correctly
```
Fixes #6331
> sdk/python: raise exception when jfs_init returns 0

- sdk/python/juicefs/juicefs/juicefs.py
fix: https://github.com/juicedata/juicefs/issues/6328
> sdk: fix Python clone method docstring to include directory support

- pkg/fuse/fuse.go
Add InodeNotify call in Open method to force kernel cache invalidation when files are opened. This ensures that clients get fresh inode attribute information instead of relying on potentially stale cached data.
The change calls fsserv.InodeNotify() with the opened file's inode ID to notify the kernel to invalidate its cached attribute information. This improves consistency across multiple clients accessing the same files.
Resolves: #6323
> fuse: add inode cache invalidation on file open

- docs/en/security/trash.md
- pkg/meta/base_test.go
- pkg/meta/interface.go
- pkg/meta/redis.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
- pkg/vfs/vfs_unix.go
This change adds support for the FlagSkipTrash in the VFS and meta portions of the code and maps to `FS_SECRM_FL` / secure removal / 's' in chattr. Setting the attribute on a file will prevent the file from being sent to trash. New files and sub-directories will inherit the flag if the directory has the flag set.
Closes #5385
> vfs: Add support to skip trash if 's' attribute is set

- cmd/config.go
- cmd/format.go
- pkg/meta/interface.go
- pkg/meta/quota.go
- pkg/meta/sql.go
This commit introduces automatic scanning and initialization of user group quota
when the user-group-quota configuration is enabled. The changes include:
- Add ScanUserGroupUsage interface method for triggering quota scan
- Automatically trigger quota scan when enabling user-group-quota config
- Clean up outdated user group quota data when enabling the feature
The implementation ensures that when users enable user-group-quota through the
config command, the system automatically scans and initializes the quota usage
data.
> cmd/config: support toggling configuration for user group quota

- pkg/meta/base.go
- pkg/meta/context.go
- pkg/meta/redis.go
- pkg/meta/sql.go
- pkg/meta/tkv.go
> meta: cancel background jobs on timeout using context
